import { ReconstructionService } from "./reconstructionService";
import { ReconstructionFootageService } from "./reconstructionFootageService";
import { RoadLayoutDetectionService } from "./roadLayoutDetectionService";

import type {
  AccidentCase,
  AccidentCaseCompletion,
  AccidentCaseFormValues,
  AccidentCaseStats,
  AccidentCaseStatus,
  CaseStatusUpdateResult,
} from "../types/accidentCase";

import type {
  AccidentReconstruction,
  RoadSceneSettings,
} from "../types/reconstruction";

import type { RoadLayoutDetection } from "../types/roadLayoutDetection";
import { createDefaultRoadSceneSettings } from "../types/reconstruction";

const STORAGE_KEY = "roadsafe-ar-accident-cases";

function createId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function getToday(): string {
  return new Date().toISOString().slice(0, 10);
}

function normaliseCase(record: AccidentCase): AccidentCase {
  const now = new Date().toISOString();

  return {
    ...record,
    id: record.id || createId("case"),
    caseNumber: record.caseNumber || "UNASSIGNED",
    title: record.title || "Untitled Accident Case",
    accidentDate: record.accidentDate || getToday(),
    accidentTime: record.accidentTime || "12:00",
    location: record.location || "Location not recorded",
    junctionId: record.junctionId || undefined,
    investigatingOfficer: record.investigatingOfficer || "",
    policeStation: record.policeStation || "",
    status: record.status || "Open",
    reconstructionId: record.reconstructionId || undefined,
    roadLayoutDetection: record.roadLayoutDetection
      ? RoadLayoutDetectionService.normalise(record.roadLayoutDetection)
      : undefined,
    footageIds: Array.isArray(record.footageIds) ? record.footageIds : [],
    primaryFootageId: record.primaryFootageId || undefined,
    summary: record.summary || "",
    createdAt: record.createdAt || now,
    updatedAt: record.updatedAt || now,
  };
}

function readCases(): AccidentCase[] {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (!stored) return [];

    const parsed = JSON.parse(stored) as AccidentCase[];
    if (!Array.isArray(parsed)) return [];

    return parsed.map(normaliseCase);
  } catch (error) {
    console.error("Failed to read accident cases:", error);
    return [];
  }
}

function writeCases(cases: AccidentCase[]): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(cases));
}

function createEmptyReconstruction(
  accidentCase: AccidentCase,
  sceneSettings: RoadSceneSettings = createDefaultRoadSceneSettings(),
  roadLayoutDetection?: RoadLayoutDetection,
): AccidentReconstruction {
  const now = new Date().toISOString();

  return {
    id: createId("reconstruction"),
    accidentId: accidentCase.caseNumber,
    junctionId: accidentCase.junctionId ?? "",
    title: `${accidentCase.caseNumber} Reconstruction`,
    description: accidentCase.summary,
    durationSeconds: 6,
    vehicles: [],
    collisionPoint: { x: 50, y: 50 },
    scene: sceneSettings,
    roadLayoutDetection,
    sceneObjects: [],
    timelineEvents: [],
    measurements: [],
    evidenceRecords: [],
    photos: [],
    fieldPlacements: [],
    fieldWalkingTracks: [],
    createdAt: now,
    updatedAt: now,
    status: "Draft",
  };
}

function isAutoGeneratedReconstructionTitle(title: string): boolean {
  return /^RSA-\d{4}-\d{4}\s+Reconstruction$/i.test(title.trim());
}

function synchroniseReconstructionMetadata(
  accidentCase: AccidentCase,
  reconstruction: AccidentReconstruction,
): AccidentReconstruction {
  const nextTitle =
    !reconstruction.title.trim() ||
    isAutoGeneratedReconstructionTitle(reconstruction.title)
      ? `${accidentCase.caseNumber} Reconstruction`
      : reconstruction.title;

  return {
    ...reconstruction,
    accidentId: accidentCase.caseNumber,
    junctionId: accidentCase.junctionId ?? "",
    title: nextTitle,
    description:
      reconstruction.description.trim() || accidentCase.summary || "",
    roadLayoutDetection:
      reconstruction.roadLayoutDetection ?? accidentCase.roadLayoutDetection,
  };
}

function persistCase(record: AccidentCase): AccidentCase {
  const records = readCases();
  const updated = normaliseCase(record);
  const index = records.findIndex((item) => item.id === updated.id);

  if (index >= 0) records[index] = updated;
  else records.push(updated);

  writeCases(records);
  return updated;
}

function getLinkedReconstructionFromRecord(
  record: AccidentCase,
): AccidentReconstruction | null {
  if (!record.reconstructionId) return null;
  return ReconstructionService.getById(record.reconstructionId);
}

export const AccidentCaseService = {
  getAll(): AccidentCase[] {
    return readCases().sort(
      (left, right) =>
        new Date(right.updatedAt).getTime() -
        new Date(left.updatedAt).getTime(),
    );
  },

  getById(caseId: string): AccidentCase | null {
    return this.getAll().find((record) => record.id === caseId) ?? null;
  },

  generateNextCaseNumber(): string {
    const year = new Date().getFullYear();
    const prefix = `RSA-${year}-`;

    const highest = this.getAll().reduce((currentHighest, record) => {
      if (!record.caseNumber.startsWith(prefix)) return currentHighest;
      const sequence = Number(record.caseNumber.slice(prefix.length));
      return Number.isFinite(sequence)
        ? Math.max(currentHighest, sequence)
        : currentHighest;
    }, 0);

    return `${prefix}${String(highest + 1).padStart(4, "0")}`;
  },

  create(values: AccidentCaseFormValues): AccidentCase {
    const now = new Date().toISOString();

    const baseRecord = normaliseCase({
      id: createId("case"),
      ...values,
      junctionId: values.junctionId.trim() || undefined,
      reconstructionId: undefined,
      roadLayoutDetection: undefined,
      footageIds: [],
      primaryFootageId: undefined,
      createdAt: now,
      updatedAt: now,
    });

    const reconstruction = ReconstructionService.save(
      createEmptyReconstruction(baseRecord),
    );

    const linkedRecord = {
      ...baseRecord,
      reconstructionId: reconstruction.id,
    };

    return persistCase(linkedRecord);
  },

  createWithRoadLayout(
    values: AccidentCaseFormValues,
    roadLayoutDetection: RoadLayoutDetection,
    sceneSettings: RoadSceneSettings,
  ): AccidentCase {
    const now = new Date().toISOString();
    const normalisedDetection =
      RoadLayoutDetectionService.normalise(roadLayoutDetection);

    const baseRecord = normaliseCase({
      id: createId("case"),
      ...values,
      junctionId: values.junctionId.trim() || undefined,
      reconstructionId: undefined,
      roadLayoutDetection: normalisedDetection,
      footageIds: [],
      primaryFootageId: undefined,
      createdAt: now,
      updatedAt: now,
    });

    const reconstruction = ReconstructionService.save(
      createEmptyReconstruction(
        baseRecord,
        sceneSettings,
        normalisedDetection,
      ),
    );

    return persistCase({
      ...baseRecord,
      reconstructionId: reconstruction.id,
    });
  },

  save(record: AccidentCase): AccidentCase {
    const updated = persistCase({
      ...record,
      updatedAt: new Date().toISOString(),
    });

    const linkedReconstruction = getLinkedReconstructionFromRecord(updated);

    if (linkedReconstruction) {
      ReconstructionService.save(
        synchroniseReconstructionMetadata(updated, linkedReconstruction),
      );
    }

    return updated;
  },

  delete(caseId: string): void {
    const record = this.getById(caseId);

    if (record?.reconstructionId) {
      ReconstructionService.delete(record.reconstructionId);
    }

    if (record) {
      void ReconstructionFootageService.deleteByCaseId(record.id).catch(
        (error) => console.error("Failed to delete linked case footage:", error),
      );
    }

    writeCases(readCases().filter((item) => item.id !== caseId));
  },

  duplicate(caseId: string): AccidentCase | null {
    const source = this.getById(caseId);
    if (!source) return null;

    const values: AccidentCaseFormValues = {
      caseNumber: this.generateNextCaseNumber(),
      title: `${source.title} Copy`,
      accidentDate: source.accidentDate,
      accidentTime: source.accidentTime,
      location: source.location,
      junctionId: source.junctionId ?? "",
      investigatingOfficer: source.investigatingOfficer,
      policeStation: source.policeStation,
      status: "Open",
      summary: source.summary,
    };

    const sourceReconstruction = getLinkedReconstructionFromRecord(source);

    return source.roadLayoutDetection && sourceReconstruction
      ? this.createWithRoadLayout(
          values,
          source.roadLayoutDetection,
          sourceReconstruction.scene,
        )
      : this.create(values);
  },

  archive(caseId: string): AccidentCase | null {
    const record = this.getById(caseId);
    if (!record) return null;
    return this.save({ ...record, status: "Archived" });
  },

  getLinkedReconstruction(
    caseOrId: AccidentCase | string,
  ): AccidentReconstruction | null {
    const record =
      typeof caseOrId === "string" ? this.getById(caseOrId) : caseOrId;

    return record ? getLinkedReconstructionFromRecord(record) : null;
  },

  ensureReconstruction(caseId: string): AccidentReconstruction | null {
    const record = this.getById(caseId);
    if (!record) return null;

    const existing = getLinkedReconstructionFromRecord(record);

    if (existing) {
      const synchronised = synchroniseReconstructionMetadata(record, existing);
      const metadataChanged =
        synchronised.accidentId !== existing.accidentId ||
        synchronised.junctionId !== existing.junctionId ||
        synchronised.title !== existing.title ||
        synchronised.description !== existing.description ||
        synchronised.roadLayoutDetection !== existing.roadLayoutDetection;

      // Opening a reconstruction must remain a read operation whenever possible.
      // Previously this method saved every existing reconstruction during render,
      // which could throw a localStorage quota error and leave a white page.
      if (!metadataChanged) {
        return existing;
      }

      try {
        return ReconstructionService.save(synchronised);
      } catch (error) {
        console.error(
          "Unable to synchronise reconstruction metadata while opening it:",
          error,
        );

        // The editor can still open with the normalised in-memory record. The
        // user will receive the normal save error if browser storage remains full.
        return synchronised;
      }
    }

    try {
      const reconstruction = ReconstructionService.save(
        createEmptyReconstruction(
          record,
          record.roadLayoutDetection?.suggestedSceneSettings ??
            createDefaultRoadSceneSettings(),
          record.roadLayoutDetection,
        ),
      );

      persistCase({
        ...record,
        reconstructionId: reconstruction.id,
        status:
          record.status === "Open" ||
          record.status === "Reconstruction Complete"
            ? "Under Investigation"
            : record.status,
        updatedAt: new Date().toISOString(),
      });

      return reconstruction;
    } catch (error) {
      console.error("Failed to create the linked reconstruction:", error);
      return null;
    }
  },

  registerReconstructionSave(
    caseId: string,
    reconstruction: AccidentReconstruction,
  ): AccidentCase | null {
    const record = this.getById(caseId);
    if (!record) return null;

    const synchronised = synchroniseReconstructionMetadata(
      record,
      reconstruction,
    );

    if (
      synchronised.accidentId !== reconstruction.accidentId ||
      synchronised.junctionId !== reconstruction.junctionId ||
      synchronised.title !== reconstruction.title ||
      synchronised.description !== reconstruction.description
    ) {
      ReconstructionService.save(synchronised);
    }

    return persistCase({
      ...record,
      reconstructionId: reconstruction.id,
      status:
        record.status === "Open" || record.status === "Reconstruction Complete"
          ? "Under Investigation"
          : record.status,
      updatedAt: new Date().toISOString(),
    });
  },

  getStats(record: AccidentCase): AccidentCaseStats {
    const reconstruction = getLinkedReconstructionFromRecord(record);
    const movementPointCount =
      reconstruction?.vehicles.reduce(
        (total, participant) => total + participant.pathPoints.length,
        0,
      ) ?? 0;

    return {
      hasReconstruction: Boolean(reconstruction),
      participantCount: reconstruction?.vehicles.length ?? 0,
      movementPointCount,
      evidenceCount: reconstruction?.evidenceRecords.length ?? 0,
      measurementCount: reconstruction?.measurements.length ?? 0,
      photoCount: reconstruction?.photos.length ?? 0,
      sceneObjectCount: reconstruction?.sceneObjects.length ?? 0,
      timelineEventCount:
        (reconstruction?.timelineEvents.length ?? 0) + movementPointCount,
      footageCount: ReconstructionFootageService.getByCaseId(record.id).length,
      reconstructionStatus: reconstruction?.status ?? "Not Created",
      reconstructionLastSavedAt: reconstruction?.updatedAt,
    };
  },

  getCompletion(record: AccidentCase): AccidentCaseCompletion {
    const reconstruction = getLinkedReconstructionFromRecord(record);
    const participants = reconstruction?.vehicles ?? [];
    const movementPointCount = participants.reduce(
      (total, participant) => total + participant.pathPoints.length,
      0,
    );

    const caseInformationComplete = Boolean(
      record.caseNumber.trim() &&
        record.title.trim() &&
        record.accidentDate &&
        record.accidentTime &&
        record.location.trim(),
    );

    const participantsComplete = participants.length > 0;

    const routesComplete =
      participants.length > 0 &&
      participants.every(
        (participant) =>
          participant.originLocation.trim().length > 0 &&
          participant.destinationLocation.trim().length > 0,
      );

    const sequenceComplete =
      participants.length > 0 &&
      participants.every((participant) => participant.pathPoints.length >= 2) &&
      movementPointCount >= 3;

    const collisionComplete = Boolean(
      reconstruction &&
        (participants.some((participant) =>
          participant.pathPoints.some((point) => point.action === "Impact"),
        ) ||
          reconstruction.timelineEvents.some(
            (event) => event.type === "Collision",
          )),
    );

    const evidenceComplete = Boolean(
      reconstruction &&
        (reconstruction.evidenceRecords.length > 0 ||
          reconstruction.measurements.length > 0 ||
          reconstruction.photos.length > 0),
    );

    const reconstructionSaved = Boolean(
      reconstruction && record.reconstructionId === reconstruction.id,
    );

    const checks = [
      {
        key: "case-information" as const,
        label: "Case information completed",
        complete: caseInformationComplete,
        detail: caseInformationComplete
          ? "Required case details have been recorded."
          : "Add the case number, title, date, time and location.",
      },
      {
        key: "participants" as const,
        label: "At least one participant added",
        complete: participantsComplete,
        detail: participantsComplete
          ? `${participants.length} participant(s) are in the scene.`
          : "Add a vehicle, pedestrian, cyclist or another participant.",
      },
      {
        key: "participant-routes" as const,
        label: "Participant origins and destinations recorded",
        complete: routesComplete,
        detail: routesComplete
          ? "Every participant has a recorded origin and destination."
          : "Complete the Came From and Heading To fields for every participant.",
      },
      {
        key: "accident-sequence" as const,
        label: "Accident movement sequence defined",
        complete: sequenceComplete,
        detail: sequenceComplete
          ? `${movementPointCount} movement point(s) define the sequence.`
          : "Add and time movement points for each participant.",
      },
      {
        key: "collision-event" as const,
        label: "Collision or key impact event recorded",
        complete: collisionComplete,
        detail: collisionComplete
          ? "An impact or collision event is present."
          : "Add an Impact movement point or a Collision timeline event.",
      },
      {
        key: "evidence" as const,
        label: "Evidence or measurements documented",
        complete: evidenceComplete,
        detail: evidenceComplete
          ? "The case contains evidence, measurements or photographs."
          : "Add at least one evidence record, measurement or photograph.",
      },
      {
        key: "reconstruction-saved" as const,
        label: "Reconstruction linked and saved",
        complete: reconstructionSaved,
        detail: reconstructionSaved
          ? `Linked reconstruction last saved ${new Date(
              reconstruction!.updatedAt,
            ).toLocaleString()}.`
          : "Open and save the reconstruction for this case.",
      },
    ];

    const completedCount = checks.filter((check) => check.complete).length;
    const totalCount = checks.length;

    return {
      complete: completedCount === totalCount,
      completedCount,
      totalCount,
      percentage: Math.round((completedCount / totalCount) * 100),
      checks,
    };
  },

  registerFootage(
    caseId: string,
    footageId: string,
    makePrimary = false,
  ): AccidentCase | null {
    const record = this.getById(caseId);
    if (!record) return null;

    const footageIds = Array.from(new Set([...record.footageIds, footageId]));
    const primaryFootageId =
      makePrimary || !record.primaryFootageId
        ? footageId
        : record.primaryFootageId;

    return persistCase({
      ...record,
      footageIds,
      primaryFootageId,
      status: record.status === "Open" ? "Under Investigation" : record.status,
      updatedAt: new Date().toISOString(),
    });
  },

  removeFootage(caseId: string, footageId: string): AccidentCase | null {
    const record = this.getById(caseId);
    if (!record) return null;

    const footageIds = record.footageIds.filter((id) => id !== footageId);
    const remaining = ReconstructionFootageService.getByCaseId(caseId);
    const nextPrimary = remaining.find((item) => item.isPrimary)?.id ?? remaining[0]?.id;

    return persistCase({
      ...record,
      footageIds,
      primaryFootageId:
        record.primaryFootageId === footageId
          ? nextPrimary
          : record.primaryFootageId,
      updatedAt: new Date().toISOString(),
    });
  },

  setPrimaryFootage(caseId: string, footageId: string): AccidentCase | null {
    const record = this.getById(caseId);
    if (!record || !record.footageIds.includes(footageId)) return null;

    return persistCase({
      ...record,
      primaryFootageId: footageId,
      updatedAt: new Date().toISOString(),
    });
  },

  setStatus(
    caseId: string,
    status: AccidentCaseStatus,
  ): CaseStatusUpdateResult | null {
    const record = this.getById(caseId);
    if (!record) return null;

    const completion = this.getCompletion(record);

    if (status === "Reconstruction Complete" && !completion.complete) {
      return {
        record,
        completion,
        blocked: true,
        message:
          "The case cannot be marked Reconstruction Complete until every completion check passes.",
      };
    }

    const saved = this.save({ ...record, status });

    const reconstruction = getLinkedReconstructionFromRecord(saved);
    if (reconstruction) {
      ReconstructionService.save({
        ...reconstruction,
        status:
          status === "Reconstruction Complete"
            ? "Completed"
            : status === "Open" || status === "Under Investigation"
              ? "Draft"
              : reconstruction.status,
      });
    }

    return {
      record: saved,
      completion: this.getCompletion(saved),
      blocked: false,
    };
  },
};