import type {
  MovementAction,
  MovementPathPoint,
  ReconstructionSceneObject,
  ReconstructionVehicle,
} from "../../types/reconstruction";

interface ParticipantPathPanelProps {
  participant: ReconstructionVehicle;
  durationSeconds: number;
  sceneObjects: ReconstructionSceneObject[];
  selectedPointId: string | null;
  onSelectPoint: (pointId: string) => void;
  onParticipantChange: (
    updates: Partial<ReconstructionVehicle>,
  ) => void;
  onPointChange: (
    pointId: string,
    updates: Partial<MovementPathPoint>,
  ) => void;
  onAddPoint: () => void;
  onDeletePoint: (pointId: string) => void;
  onPlacePointWithGps: (pointId: string) => void;
  onJumpToTime: (timeSeconds: number) => void;
  onHeadingChange: (heading: string, degrees: number) => void;
}

const MOVEMENT_ACTIONS: MovementAction[] = [
  "Start",
  "Enter Scene",
  "Accelerate",
  "Cruise",
  "Brake",
  "Turn Left",
  "Turn Right",
  "Swerve",
  "Impact",
  "Ricochet",
  "Deflect",
  "Slide",
  "Fall",
  "Stop",
  "Exit Scene",
];

function getActionClasses(action: MovementAction): string {
  switch (action) {
    case "Start":
    case "Enter Scene":
      return "bg-green-100 text-green-700";

    case "Brake":
      return "bg-amber-100 text-amber-700";

    case "Impact":
      return "bg-red-100 text-red-700";

    case "Swerve":
    case "Turn Left":
    case "Turn Right":
    case "Deflect":
      return "bg-cyan-100 text-cyan-700";

    case "Ricochet":
      return "bg-orange-100 text-orange-700";

    case "Slide":
    case "Fall":
      return "bg-purple-100 text-purple-700";

    case "Stop":
    case "Exit Scene":
      return "bg-gray-200 text-gray-700";

    default:
      return "bg-blue-100 text-blue-700";
  }
}

export default function ParticipantPathPanel({
  participant,
  durationSeconds,
  sceneObjects,
  selectedPointId,
  onSelectPoint,
  onParticipantChange,
  onPointChange,
  onAddPoint,
  onDeletePoint,
  onPlacePointWithGps,
  onJumpToTime,
  onHeadingChange,
}: ParticipantPathPanelProps) {
  const [showPhysicsSamples, setShowPhysicsSamples] = useState(false);
  const allPoints = [...participant.pathPoints].sort(
    (first, second) => first.timeSeconds - second.timeSeconds,
  );
  const isPhysicsSample = (point: MovementPathPoint) =>
    point.id.startsWith("physics-point") ||
    point.notes?.includes("Generated by the RoadSafe deterministic 2D physics preview.");
  const points = showPhysicsSamples
    ? allPoints
    : allPoints.filter((point) =>
        !isPhysicsSample(point) ||
        point.action === "Ricochet" ||
        point.action === "Deflect" ||
        point.action === "Stop",
      );
  const hiddenPhysicsSamples = allPoints.length - points.length;
  const headings = [
    ["NW", -135], ["N", -90], ["NE", -45],
    ["W", 180], ["", 0], ["E", 0],
    ["SW", 135], ["S", 90], ["SE", 45],
  ] as const;

  return (
    <div className="mt-5 border-t border-gray-200 pt-5">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="font-bold text-gray-900">Route & movement path</h3>
          <p className="mt-1 text-xs leading-5 text-gray-500">
            State where the participant came from, where they were heading,
            then edit each timed movement point.
          </p>
        </div>

        <button
          type="button"
          onClick={onAddPoint}
          className="shrink-0 rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white hover:bg-blue-700"
        >
          Add point
        </button>
      </div>

      <div className="mt-4 grid gap-3">
        <label className="block">
          <span className="text-sm font-medium text-gray-700">Came from</span>
          <input
            value={participant.originLocation}
            onChange={(event) =>
              onParticipantChange({ originLocation: event.target.value })
            }
            placeholder="e.g. Chipadze residential area"
            className="mt-1.5 w-full rounded-sm border border-gray-300 px-3 py-2.5 text-sm outline-none focus:border-blue-500"
          />
        </label>

        <label className="block">
          <span className="text-sm font-medium text-gray-700">Heading to</span>
          <input
            value={participant.destinationLocation}
            onChange={(event) =>
              onParticipantChange({ destinationLocation: event.target.value })
            }
            placeholder="e.g. Bindura CBD"
            className="mt-1.5 w-full rounded-sm border border-gray-300 px-3 py-2.5 text-sm outline-none focus:border-blue-500"
          />
        </label>

        <div className="rounded-sm border border-cyan-200 bg-cyan-50 p-3">
          <div className="flex items-center justify-between gap-3">
            <div>
              <p className="text-sm font-black text-cyan-950">Pick heading direction</p>
              <p className="mt-1 text-[11px] text-cyan-800">Moves the final route point toward the selected direction.</p>
            </div>
            <div className="grid h-28 w-28 shrink-0 grid-cols-3 gap-1">
              {headings.map(([heading, degrees], index) => heading ? (
                <button
                  key={heading}
                  type="button"
                  onClick={() => onHeadingChange(heading, degrees)}
                  className="rounded-lg border border-cyan-300 bg-white text-[11px] font-black text-cyan-900 shadow-sm hover:bg-cyan-700 hover:text-white"
                  title={`Head ${heading}`}
                >
                  {heading}
                </button>
              ) : (
                <span key={`centre-${index}`} className="flex items-center justify-center rounded-lg bg-cyan-900 text-sm text-white">●</span>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="mt-4 space-y-3">
        {hiddenPhysicsSamples > 0 && (
          <div className="flex items-center justify-between gap-3 rounded-sm border border-violet-200 bg-violet-50 p-3">
            <p className="text-xs leading-5 text-violet-900"><strong>{hiddenPhysicsSamples} physics samples hidden.</strong> They keep playback smooth and accurate but are not primary editing dots.</p>
            <button type="button" onClick={() => setShowPhysicsSamples(true)} className="shrink-0 rounded-lg bg-violet-700 px-3 py-2 text-[10px] font-black text-white">Show all</button>
          </div>
        )}
        {showPhysicsSamples && allPoints.some(isPhysicsSample) && (
          <button type="button" onClick={() => setShowPhysicsSamples(false)} className="w-full rounded-lg border border-violet-200 px-3 py-2 text-xs font-black text-violet-800">Hide physics samples</button>
        )}
        {points.map((point, index) => {
          const selected = selectedPointId === point.id;

          return (
            <div
              key={point.id}
              className={`rounded-sm border p-3 transition ${
                selected
                  ? "border-blue-500 bg-blue-50"
                  : "border-gray-200 bg-white"
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <button
                  type="button"
                  onClick={() => onSelectPoint(point.id)}
                  className="min-w-0 flex-1 text-left"
                >
                  <span className="flex items-center gap-2">
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gray-900 text-[10px] font-bold text-white">
                      {index + 1}
                    </span>
                    <span className="truncate text-sm font-bold text-gray-900">
                      {point.label}
                    </span>
                  </span>

                  <span
                    className={`mt-2 inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${getActionClasses(
                      point.action,
                    )}`}
                  >
                    {point.action}
                  </span>
                </button>

                <div className="flex items-center gap-1">
                  <button
                    type="button"
                    onClick={() => onJumpToTime(point.timeSeconds)}
                    className="rounded-lg border border-gray-300 px-2 py-1 text-[10px] font-bold text-gray-600 hover:bg-gray-100"
                  >
                    Jump
                  </button>

                  <button
                    type="button"
                    onClick={() => onDeletePoint(point.id)}
                    disabled={allPoints.length <= 2}
                    className="rounded-lg border border-red-200 px-2 py-1 text-[10px] font-bold text-red-600 hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-40"
                  >
                    Delete
                  </button>
                </div>
              </div>

              {selected && (
                <div className="mt-4 space-y-3 border-t border-blue-200 pt-3">
                  <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3">
                    <p className="text-xs font-black text-emerald-950">
                      Real-world position
                    </p>
                    <p className="mt-1 text-[11px] leading-5 text-emerald-800">
                      Walk to this participant's position at this point in the
                      accident sequence, then confirm the device GPS reading.
                    </p>
                    <button
                      type="button"
                      onClick={() => onPlacePointWithGps(point.id)}
                      className="mt-2 w-full rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white hover:bg-emerald-700"
                    >
                      Place This Point Using GPS
                    </button>
                  </div>

                  <label className="block">
                    <span className="text-xs font-medium text-gray-600">
                      Point label
                    </span>
                    <input
                      value={point.label}
                      onChange={(event) =>
                        onPointChange(point.id, { label: event.target.value })
                      }
                      className="mt-1 w-full rounded-lg border border-gray-300 px-2.5 py-2 text-sm"
                    />
                  </label>

                  <label className="block">
                    <span className="text-xs font-medium text-gray-600">
                      Action
                    </span>
                    <select
                      value={point.action}
                      onChange={(event) =>
                        onPointChange(point.id, {
                          action: event.target.value as MovementAction,
                        })
                      }
                      className="mt-1 w-full rounded-lg border border-gray-300 px-2.5 py-2 text-sm"
                    >
                      {MOVEMENT_ACTIONS.map((action) => (
                        <option key={action} value={action}>
                          {action}
                        </option>
                      ))}
                    </select>
                  </label>

                  <div className="grid grid-cols-3 gap-2">
                    <label>
                      <span className="text-[11px] font-medium text-gray-600">
                        Time (s)
                      </span>
                      <input
                        type="number"
                        min={0}
                        max={durationSeconds}
                        step={0.1}
                        value={Number(point.timeSeconds.toFixed(1))}
                        onChange={(event) =>
                          onPointChange(point.id, {
                            timeSeconds: Math.min(
                              durationSeconds,
                              Math.max(0, Number(event.target.value)),
                            ),
                          })
                        }
                        className="mt-1 w-full rounded-lg border border-gray-300 px-2 py-2 text-sm"
                      />
                    </label>

                    <label>
                      <span className="text-[11px] font-medium text-gray-600">
                        Speed
                      </span>
                      <input
                        type="number"
                        min={0}
                        max={220}
                        step={1}
                        value={Number(point.speedKmh.toFixed(1))}
                        onChange={(event) =>
                          onPointChange(point.id, {
                            speedKmh: Math.max(0, Number(event.target.value)),
                          })
                        }
                        className="mt-1 w-full rounded-lg border border-gray-300 px-2 py-2 text-sm"
                      />
                    </label>

                    <label>
                      <span className="text-[11px] font-medium text-gray-600">
                        Rotation°
                      </span>
                      <input
                        type="number"
                        value={Number(point.rotation.toFixed(1))}
                        onChange={(event) =>
                          onPointChange(point.id, {
                            rotation: Number(event.target.value),
                          })
                        }
                        className="mt-1 w-full rounded-lg border border-gray-300 px-2 py-2 text-sm"
                      />
                    </label>
                  </div>

                  <div className="grid grid-cols-2 gap-2">
                    <label>
                      <span className="text-[11px] font-medium text-gray-600">
                        X position
                      </span>
                      <input
                        type="number"
                        min={0}
                        max={100}
                        step={0.1}
                        value={Number(point.position.x.toFixed(1))}
                        onChange={(event) =>
                          onPointChange(point.id, {
                            position: {
                              ...point.position,
                              x: Math.min(
                                100,
                                Math.max(0, Number(event.target.value)),
                              ),
                            },
                          })
                        }
                        className="mt-1 w-full rounded-lg border border-gray-300 px-2 py-2 text-sm"
                      />
                    </label>

                    <label>
                      <span className="text-[11px] font-medium text-gray-600">
                        Y position
                      </span>
                      <input
                        type="number"
                        min={0}
                        max={100}
                        step={0.1}
                        value={Number(point.position.y.toFixed(1))}
                        onChange={(event) =>
                          onPointChange(point.id, {
                            position: {
                              ...point.position,
                              y: Math.min(
                                100,
                                Math.max(0, Number(event.target.value)),
                              ),
                            },
                          })
                        }
                        className="mt-1 w-full rounded-lg border border-gray-300 px-2 py-2 text-sm"
                      />
                    </label>
                  </div>

                  <label className="block">
                    <span className="text-xs font-medium text-gray-600">
                      Related scene object
                    </span>
                    <select
                      value={point.linkedSceneObjectId ?? ""}
                      onChange={(event) =>
                        onPointChange(point.id, {
                          linkedSceneObjectId: event.target.value || undefined,
                        })
                      }
                      className="mt-1 w-full rounded-lg border border-gray-300 px-2.5 py-2 text-sm"
                    >
                      <option value="">None</option>
                      {sceneObjects.map((object) => (
                        <option key={object.id} value={object.id}>
                          {object.label}
                        </option>
                      ))}
                    </select>
                  </label>

                  <label className="block">
                    <span className="text-xs font-medium text-gray-600">
                      Point notes
                    </span>
                    <textarea
                      value={point.notes ?? ""}
                      onChange={(event) =>
                        onPointChange(point.id, { notes: event.target.value })
                      }
                      rows={2}
                      className="mt-1 w-full resize-none rounded-lg border border-gray-300 px-2.5 py-2 text-sm"
                    />
                  </label>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
import { useState } from "react";
