/*
 * [RoadSafe:RapierDynamicsV1]
 *
 * Rapier is the rigid-body dynamics layer.
 * RoadSafe Physics V2 remains the forensic calculation/audit layer.
 *
 * The canonical reconstruction stays 2D (scene x/y percentages). Rapier runs
 * a metre-based 3D world using x/z as the road plane and y as vertical.
 * Hidden Rapier trajectory samples are projected back into the same canonical
 * 2D path format, so 2D, 3D, Timeline, AR and reports continue sharing state.
 */

import RAPIER from "@dimforge/rapier3d-deterministic-compat";

import type {
  AccidentReconstruction,
  MovementPathPoint,
  ParticipantPhysicsProfile,
  ReconstructionPosition,
  ReconstructionSceneObject,
  ReconstructionVehicle,
  SceneObjectPhysicsProfile,
} from "../types/reconstruction";

import {
  DEFAULT_PHYSICS_SETTINGS,
  applyPhysicsSimulation,
  getDefaultParticipantPhysics,
  getDefaultSceneObjectPhysics,
} from "./reconstructionPhysicsService";

import {
  clamp,
  isPhysicsGeneratedPathPoint,
  sortMovementPathPoints,
  syncLegacyParticipantFields,
} from "../utils/reconstructionGeometry";

import {
  getReconstructionWorldDimensions,
} from "../utils/reconstructionWorldScale";

import {
  normaliseReconstructionPhysicsSettings,
} from "../utils/reconstructionPhysicsFoundation";

import {
  getParticipantAssetDefinition,
  getParticipantPhysicalDimensions,
} from "../engine/assets/participantAssetCatalog";

import {
  deriveParticipantVisualDamage,
} from "../utils/reconstructionDamageModel";

import {
  getParticipantAccidentReactionState,
} from "../utils/reconstructionReactionModel";

const RAPIER_PACKAGE =
  "@dimforge/rapier3d-deterministic-compat";

const RAPIER_VERSION =
  "0.19.3";

const RAPIIER_GENERATED_NOTE =
  "Generated by RoadSafe Rapier 3D deterministic dynamics.";

interface Vector2 {
  x: number;
  y: number;
}

interface Vector3 {
  x: number;
  y: number;
  z: number;
}

interface QuaternionLike {
  x: number;
  y: number;
  z: number;
  w: number;
}

interface RapierBodyLike {
  translation(): Vector3;
  linvel(): Vector3;
  setLinvel(
    velocity: Vector3,
    wakeUp: boolean,
  ): void;
  rotation(): QuaternionLike;
  isSleeping(): boolean;
}

interface RapierSample {
  timeSeconds: number;
  position: ReconstructionPosition;
  speedKmh: number;
  rotationDegrees: number;
  sleeping: boolean;
}

interface ParticipantRuntime {
  participant: ReconstructionVehicle;
  profile: ParticipantPhysicsProfile;
  body: RapierBodyLike;
  samples: RapierSample[];
}

type ColliderMeta =
  | {
      kind: "participant";
      id: string;
    }
  | {
      kind: "sceneObject";
      id: string;
    }
  | {
      kind: "ground";
      id: "ground";
    };

let rapierInitPromise:
  Promise<void> | null = null;

function ensureRapierReady(): Promise<void> {
  if (!rapierInitPromise) {
    rapierInitPromise =
      RAPIER.init().then(
        () => undefined,
      );
  }

  return rapierInitPromise;
}

function degreesToRadians(
  degrees: number,
): number {
  return (
    degrees *
    Math.PI /
    180
  );
}

function radiansToDegrees(
  radians: number,
): number {
  return (
    radians *
    180 /
    Math.PI
  );
}

function normaliseDegrees(
  degrees: number,
): number {
  return (
    (degrees % 360) +
    360
  ) % 360;
}

function interpolate(
  start: number,
  end: number,
  progress: number,
): number {
  return (
    start +
    (end - start) *
      progress
  );
}

function interpolateAngle(
  start: number,
  end: number,
  progress: number,
): number {
  const difference =
    (
      (
        end -
        start +
        540
      ) %
        360
    ) -
    180;

  return (
    start +
    difference *
      progress
  );
}

function magnitude2(
  vector: Vector2,
): number {
  return Math.hypot(
    vector.x,
    vector.y,
  );
}

function normalise2(
  vector: Vector2,
  fallback: Vector2 = {
    x: 1,
    y: 0,
  },
): Vector2 {
  const length =
    magnitude2(vector);

  if (
    length <
    0.000001
  ) {
    const fallbackLength =
      magnitude2(fallback) ||
      1;

    return {
      x:
        fallback.x /
        fallbackLength,
      y:
        fallback.y /
        fallbackLength,
    };
  }

  return {
    x:
      vector.x /
      length,
    y:
      vector.y /
      length,
  };
}

function isHumanParticipant(
  participant:
    ReconstructionVehicle,
): boolean {
  return (
    participant.type ===
      "Pedestrian" ||
    participant.type ===
      "Officer" ||
    participant.type ===
      "Witness"
  );
}

interface ParticipantBodyColliderDimensions {
  lengthMetres: number;
  widthMetres: number;
  heightMetres: number;
  borderRadiusMetres: number;
}

function participantBodyColliderDimensions(
  participant:
    ReconstructionVehicle,
  profile:
    ParticipantPhysicsProfile,
): ParticipantBodyColliderDimensions {
  const asset =
    getParticipantAssetDefinition(
      participant,
    );

  const physical =
    getParticipantPhysicalDimensions(
      participant,
    );

  const defaults =
    getDefaultParticipantPhysics(
      participant,
    );

  const hasCustomLength =
    participant.physics
      ?.lengthMetres !==
      undefined &&
    Math.abs(
      participant.physics
        .lengthMetres -
        (
          defaults
            .lengthMetres ??
          participant.physics
            .lengthMetres
        ),
    ) >
      0.001;

  const hasCustomWidth =
    participant.physics
      ?.widthMetres !==
      undefined &&
    Math.abs(
      participant.physics
        .widthMetres -
        (
          defaults
            .widthMetres ??
          participant.physics
            .widthMetres
        ),
    ) >
      0.001;

  const length =
    Math.max(
      0.2,
      hasCustomLength
        ? (
            profile
              .lengthMetres ??
            physical
              .lengthMetres
          )
        : asset
            .collision
            .lengthMetres,
    );

  const width =
    Math.max(
      0.2,
      hasCustomWidth
        ? (
            profile
              .widthMetres ??
            physical
              .widthMetres
          )
        : asset
            .collision
            .widthMetres,
    );

  const height =
    isHumanParticipant(
      participant,
    )
      ? Math.max(
          0.4,
          physical
            .heightMetres,
        )
      : Math.max(
          0.3,
          physical
            .heightMetres *
            0.72,
        );

  const borderRadius =
    clamp(
      Math.min(
        length *
          0.055,
        width *
          0.12,
        height *
          0.16,
      ),
      0.04,
      0.2,
    );

  return {
    lengthMetres:
      length,
    widthMetres:
      width,
    heightMetres:
      height,
    borderRadiusMetres:
      borderRadius,
  };
}

function sceneObjectHeightMetres(
  object:
    ReconstructionSceneObject,
): number {
  switch (
    object.type
  ) {
    case "Traffic Cone":
      return 0.75;

    case "Road Barrier":
      return 0.9;

    case "Stop Sign":
    case "Give Way Sign":
    case "Speed Limit Sign":
      return 2.2;

    case "Traffic Light":
      return 3.5;

    case "Street Light":
      return 5;

    case "Guardrail":
      return 0.8;

    case "Bus Stop":
      return 2.6;

    case "Parked Vehicle":
      return 1.6;

    case "Tree":
      return 4;

    case "Bush":
      return 1.2;

    case "Wall":
      return 2;

    case "Fence":
      return 1.5;

    case "CCTV Camera":
      return 2.8;

    case "Debris":
    case "Broken Glass":
    case "Vehicle Part":
    case "Fallen Branch":
      return 0.35;

    default:
      return 0.5;
  }
}

function scenePositionToWorld(
  position:
    ReconstructionPosition,
  widthMetres: number,
  heightMetres: number,
): Vector2 {
  return {
    x:
      (
        clamp(
          position.x,
          0,
          100,
        ) /
        100
      ) *
      widthMetres,

    y:
      (
        clamp(
          position.y,
          0,
          100,
        ) /
        100
      ) *
      heightMetres,
  };
}

function worldPositionToScene(
  position: Vector2,
  widthMetres: number,
  heightMetres: number,
): ReconstructionPosition {
  return {
    x: clamp(
      (
        position.x /
        Math.max(
          0.001,
          widthMetres,
        )
      ) *
        100,
      0,
      100,
    ),

    y: clamp(
      (
        position.y /
        Math.max(
          0.001,
          heightMetres,
        )
      ) *
        100,
      0,
      100,
    ),
  };
}

function yawQuaternionFromRoadSafeRotation(
  rotationDegrees: number,
): QuaternionLike {
  /*
   * RoadSafe's canonical 2D positive angle rotates +X toward +sceneY.
   * Rapier/Three use a right-handed X/Z plane, so the Y-axis yaw sign is
   * inverted when sceneY is projected onto +Z.
   */
  const yaw =
    -degreesToRadians(
      rotationDegrees,
    );

  const half =
    yaw / 2;

  return {
    x: 0,
    y: Math.sin(half),
    z: 0,
    w: Math.cos(half),
  };
}

function roadSafeRotationFromQuaternion(
  rotation:
    QuaternionLike,
): number {
  const yaw =
    Math.atan2(
      2 *
        (
          rotation.w *
            rotation.y +
          rotation.x *
            rotation.z
        ),
      1 -
        2 *
          (
            rotation.y *
              rotation.y +
            rotation.z *
              rotation.z
          ),
    );

  return normaliseDegrees(
    -radiansToDegrees(
      yaw,
    ),
  );
}

function stripPhysicsPoints(
  participant:
    ReconstructionVehicle,
): MovementPathPoint[] {
  return sortMovementPathPoints(
    participant.pathPoints,
  ).filter(
    (point) =>
      !isPhysicsGeneratedPathPoint(
        point,
      ),
  );
}

function sampleAuthoredParticipant(
  participant:
    ReconstructionVehicle,
  timeSeconds: number,
  widthMetres: number,
  heightMetres: number,
): {
  position:
    ReconstructionPosition;
  rotationDegrees: number;
  speedKmh: number;
  velocityWorld:
    Vector2;
} {
  const points =
    stripPhysicsPoints(
      participant,
    );

  if (
    points.length === 0
  ) {
    const rotation =
      participant
        .startRotation;

    const direction = {
      x:
        Math.cos(
          degreesToRadians(
            rotation,
          ),
        ),

      y:
        Math.sin(
          degreesToRadians(
            rotation,
          ),
        ),
    };

    const speedKmh =
      participant.physics
        ?.inputSpeedKmh ??
      participant
        .estimatedSpeedKmh;

    const speedMps =
      speedKmh /
      3.6;

    return {
      position: {
        ...participant
          .startPosition,
      },
      rotationDegrees:
        rotation,
      speedKmh,
      velocityWorld: {
        x:
          direction.x *
          speedMps,
        y:
          direction.y *
          speedMps,
      },
    };
  }

  if (
    points.length === 1 ||
    timeSeconds <=
      points[0]
        .timeSeconds
  ) {
    const point =
      points[0];

    const next =
      points[1] ??
      point;

    const startWorld =
      scenePositionToWorld(
        point.position,
        widthMetres,
        heightMetres,
      );

    const endWorld =
      scenePositionToWorld(
        next.position,
        widthMetres,
        heightMetres,
      );

    const direction =
      normalise2(
        {
          x:
            endWorld.x -
            startWorld.x,

          y:
            endWorld.y -
            startWorld.y,
        },
        {
          x:
            Math.cos(
              degreesToRadians(
                point.rotation,
              ),
            ),

          y:
            Math.sin(
              degreesToRadians(
                point.rotation,
              ),
            ),
        },
      );

    const speedKmh =
      participant.physics
        ?.inputSpeedKmh ??
      point.speedKmh ??
      participant
        .estimatedSpeedKmh;

    const speedMps =
      speedKmh /
      3.6;

    return {
      position: {
        ...point.position,
      },
      rotationDegrees:
        point.rotation,
      speedKmh,
      velocityWorld: {
        x:
          direction.x *
          speedMps,
        y:
          direction.y *
          speedMps,
      },
    };
  }

  const last =
    points[
      points.length -
      1
    ];

  if (
    timeSeconds >=
    last.timeSeconds
  ) {
    const previous =
      points[
        Math.max(
          0,
          points.length -
            2,
        )
      ];

    const previousWorld =
      scenePositionToWorld(
        previous.position,
        widthMetres,
        heightMetres,
      );

    const lastWorld =
      scenePositionToWorld(
        last.position,
        widthMetres,
        heightMetres,
      );

    const direction =
      normalise2(
        {
          x:
            lastWorld.x -
            previousWorld.x,

          y:
            lastWorld.y -
            previousWorld.y,
        },
        {
          x:
            Math.cos(
              degreesToRadians(
                last.rotation,
              ),
            ),

          y:
            Math.sin(
              degreesToRadians(
                last.rotation,
              ),
            ),
        },
      );

    const speedKmh =
      participant.physics
        ?.inputSpeedKmh ??
      last.speedKmh ??
      participant
        .estimatedSpeedKmh;

    const speedMps =
      speedKmh /
      3.6;

    return {
      position: {
        ...last.position,
      },
      rotationDegrees:
        last.rotation,
      speedKmh,
      velocityWorld: {
        x:
          direction.x *
          speedMps,
        y:
          direction.y *
          speedMps,
      },
    };
  }

  let start =
    points[0];

  let end =
    points[1];

  for (
    let index = 0;
    index <
      points.length -
        1;
    index += 1
  ) {
    const candidateStart =
      points[index];

    const candidateEnd =
      points[index + 1];

    if (
      timeSeconds >=
        candidateStart
          .timeSeconds &&
      timeSeconds <=
        candidateEnd
          .timeSeconds
    ) {
      start =
        candidateStart;

      end =
        candidateEnd;

      break;
    }
  }

  const duration =
    Math.max(
      0.0001,
      end.timeSeconds -
        start.timeSeconds,
    );

  const progress =
    clamp(
      (
        timeSeconds -
        start.timeSeconds
      ) /
        duration,
      0,
      1,
    );

  const position = {
    x:
      interpolate(
        start.position.x,
        end.position.x,
        progress,
      ),

    y:
      interpolate(
        start.position.y,
        end.position.y,
        progress,
      ),
  };

  const startWorld =
    scenePositionToWorld(
      start.position,
      widthMetres,
      heightMetres,
    );

  const endWorld =
    scenePositionToWorld(
      end.position,
      widthMetres,
      heightMetres,
    );

  const direction =
    normalise2(
      {
        x:
          endWorld.x -
          startWorld.x,

        y:
          endWorld.y -
          startWorld.y,
      },
      {
        x:
          Math.cos(
            degreesToRadians(
              start.rotation,
            ),
          ),

        y:
          Math.sin(
            degreesToRadians(
              start.rotation,
            ),
          ),
      },
    );

  const authoredSpeed =
    interpolate(
      start.speedKmh,
      end.speedKmh,
      progress,
    );

  const speedKmh =
    participant.physics
      ?.inputSpeedKmh ??
    authoredSpeed ??
    participant
      .estimatedSpeedKmh;

  const speedMps =
    speedKmh /
    3.6;

  return {
    position,
    rotationDegrees:
      interpolateAngle(
        start.rotation,
        end.rotation,
        progress,
      ),
    speedKmh,
    velocityWorld: {
      x:
        direction.x *
        speedMps,
      y:
        direction.y *
        speedMps,
    },
  };
}

function sampleAuthoredParticipantWithReaction(
  participant:
    ReconstructionVehicle,
  timeSeconds: number,
  widthMetres: number,
  heightMetres: number,
  impactTimeOverrideSeconds?: number,
): {
  position:
    ReconstructionPosition;
  rotationDegrees: number;
  speedKmh: number;
  velocityWorld:
    Vector2;
} {
  const sample =
    sampleAuthoredParticipant(
      participant,
      timeSeconds,
      widthMetres,
      heightMetres,
    );

  const reaction =
    getParticipantAccidentReactionState(
      participant,
      timeSeconds,
      sample.position,
      sample.rotationDegrees,
      sample.speedKmh,
      impactTimeOverrideSeconds,
    );

  const speedMps =
    reaction
      .adjustedSpeedKmh /
    3.6;

  const directionRadians =
    degreesToRadians(
      reaction
        .suggestedHeadingDegrees,
    );

  return {
    position:
      sample.position,
    rotationDegrees:
      reaction
        .suggestedHeadingDegrees,
    speedKmh:
      reaction
        .adjustedSpeedKmh,
    velocityWorld: {
      x:
        Math.cos(
          directionRadians,
        ) *
        speedMps,
      y:
        Math.sin(
          directionRadians,
        ) *
        speedMps,
    },
  };
}

function groundSurfaceFriction(
  surface:
    AccidentReconstruction["scene"]["groundSurface"],
): number {
  switch (
    surface
  ) {
    case "Firm Soil":
      return 0.62;

    case "Loose Soil":
      return 0.42;

    case "Grass":
      return 0.45;

    case "Gravel":
      return 0.5;

    case "Sand":
      return 0.35;

    case "Mud":
      return 0.28;

    case "Concrete":
      return 0.82;

    case "Paved Yard":
      return 0.75;

    case "Mixed Surface":
      return 0.5;

    case "Unclassified Ground":
    default:
      return 0.5;
  }
}

function sceneSurfaceFriction(
  reconstruction:
    AccidentReconstruction,
): number {
  const scene =
    reconstruction.scene;

  const road =
    scene.roadSurface ===
    "Wet"
      ? 0.52
      : scene.roadSurface ===
          "Damaged"
        ? 0.62
        : 0.78;

  const ground =
    groundSurfaceFriction(
      scene.groundSurface,
    );

  let coefficient =
    scene.sceneEnvironment ===
      "Road / Junction"
      ? road
      : scene.sceneEnvironment ===
          "Mixed Site"
        ? (
            road +
            ground
          ) /
          2
        : ground;

  if (
    scene.weather ===
    "Rain"
  ) {
    coefficient *= 0.82;
  }

  if (
    scene.weather ===
    "Dust"
  ) {
    coefficient *= 0.9;
  }

  return coefficient;
}

function participantProfile(
  participant:
    ReconstructionVehicle,
): ParticipantPhysicsProfile {
  return {
    ...getDefaultParticipantPhysics(
      participant,
    ),
    ...(participant.physics ??
      {}),
  };
}

function objectProfile(
  object:
    ReconstructionSceneObject,
): SceneObjectPhysicsProfile {
  return {
    ...getDefaultSceneObjectPhysics(
      object,
    ),
    ...(object.physics ??
      {}),
  };
}

function participantContactRestitution(
  participant:
    ReconstructionVehicle,
  profile:
    ParticipantPhysicsProfile,
): number {
  if (
    participant.type ===
      "Car" ||
    participant.type ===
      "Bus" ||
    participant.type ===
      "Truck"
  ) {
    return clamp(
      Math.min(
        profile.restitution,
        0.07,
      ),
      0,
      1,
    );
  }

  if (
    participant.type ===
      "Motorcycle" ||
    participant.type ===
      "Bicycle"
  ) {
    return clamp(
      Math.min(
        profile.restitution,
        0.1,
      ),
      0,
      1,
    );
  }

  return clamp(
    profile.restitution,
    0,
    1,
  );
}

function createParticipantCollider(
  participant:
    ReconstructionVehicle,
  profile:
    ParticipantPhysicsProfile,
) {
  const dimensions =
    participantBodyColliderDimensions(
      participant,
      profile,
    );

  const halfHeight =
    Math.max(
      0.08,
      dimensions
        .heightMetres /
        2,
    );

  if (
    isHumanParticipant(
      participant,
    )
  ) {
    return RAPIER
      .ColliderDesc
      .roundCylinder(
        Math.max(
          0.08,
          halfHeight -
            0.05,
        ),
        Math.max(
          0.08,
          Math.min(
            dimensions
              .lengthMetres,
            dimensions
              .widthMetres,
          ) /
            2,
        ),
        0.05,
      );
  }

  const border =
    dimensions
      .borderRadiusMetres;

  return RAPIER
    .ColliderDesc
    .roundCuboid(
      Math.max(
        0.05,
        dimensions
          .lengthMetres /
            2 -
          border,
      ),
      Math.max(
        0.05,
        halfHeight -
          border,
      ),
      Math.max(
        0.05,
        dimensions
          .widthMetres /
            2 -
          border,
      ),
      border,
    );
}

function createSceneObjectCollider(
  object:
    ReconstructionSceneObject,
  profile:
    SceneObjectPhysicsProfile,
  heightMetres: number,
) {
  const length =
    Math.max(
      0.1,
      profile.lengthMetres ??
        object.lengthMetres ??
        profile
          .collisionRadiusMetres *
          2,
    );

  const width =
    Math.max(
      0.1,
      profile.widthMetres ??
        object.widthMetres ??
        profile
          .collisionRadiusMetres *
          2,
    );

  const halfHeight =
    Math.max(
      0.05,
      heightMetres /
        2,
    );

  if (
    profile.collisionShape ===
    "Circle"
  ) {
    return RAPIER
      .ColliderDesc
      .cylinder(
        halfHeight,
        Math.max(
          0.05,
          profile
            .collisionRadiusMetres,
        ),
      );
  }

  return RAPIER
    .ColliderDesc
    .cuboid(
      length / 2,
      halfHeight,
      width / 2,
    );
}

function makeRapierPoint(
  participantId: string,
  sample:
    RapierSample,
  index: number,
  action:
    MovementPathPoint["action"],
  label: string,
): MovementPathPoint {
  return {
    id:
      `physics-point-rapier-${participantId}-${index}`,

    label,

    position: {
      ...sample.position,
    },

    timeSeconds:
      Number(
        sample.timeSeconds
          .toFixed(4),
      ),

    speedKmh:
      Number(
        sample.speedKmh
          .toFixed(2),
      ),

    rotation:
      Number(
        sample
          .rotationDegrees
          .toFixed(2),
      ),

    action,

    notes:
      RAPIIER_GENERATED_NOTE,
  };
}

function addWarning(
  warnings: string[],
  warning: string,
): string[] {
  return warnings.includes(
    warning,
  )
    ? warnings
    : [
        ...warnings,
        warning,
      ];
}

export function isRapierDynamicsResult(
  reconstruction:
    AccidentReconstruction,
): boolean {
  return (
    reconstruction
      .lastPhysicsSimulation
      ?.dynamicsEngine ===
    "Rapier 3D Deterministic"
  );
}

export async function applyRapierDynamicsSimulation(
  input:
    AccidentReconstruction,
): Promise<AccidentReconstruction> {
  /*
   * First calculate RoadSafe's transparent forensic quantities. This also
   * gives us the current primary-impact estimate and keeps all existing
   * collision/kinematics reporting intact.
   */
  const forensic =
    applyPhysicsSimulation(
      input,
    );

  const settings =
    normaliseReconstructionPhysicsSettings({
      ...DEFAULT_PHYSICS_SETTINGS,
      ...(input.physicsSettings ??
        {}),
    });

  if (
    !settings.enabled ||
    settings.mode ===
      "Guided Paths" ||
    input.vehicles.length ===
      0
  ) {
    return forensic;
  }

  await ensureRapierReady();

  const {
    widthMetres,
    heightMetres,
  } =
    getReconstructionWorldDimensions(
      input,
    );

  const primaryImpactTime =
    forensic
      .lastPhysicsSimulation
      ?.primaryImpactTimeSeconds ??
    input.durationSeconds /
      2;

  /*
   * Rapier gets a short authored approach window so CCD can discover actual
   * contact instead of starting from bodies that are already interpenetrating.
   */
  const startTime =
    Math.max(
      0,
      primaryImpactTime -
        0.4,
    );

  /*
   * [RoadSafe:RapierContactStabilityV1]
   *
   * Run collision dynamics at no slower than 120 Hz. This gives CCD/contact
   * resolution and the exported playback trajectory enough temporal resolution
   * that the rendered vehicle bodies don't appear to jump through each other
   * between coarse samples.
   */
  const fixedTimeStep =
    clamp(
      Math.min(
        settings
          .timeStepSeconds,
        1 / 120,
      ),
      1 / 240,
      1 / 120,
    );

  const maximumSimulationTime =
    Math.max(
      input.durationSeconds,
      primaryImpactTime +
        30,
    );

  const world =
    new RAPIER.World({
      x: 0,
      y: -9.81,
      z: 0,
    });

  world.timestep =
    fixedTimeStep;

  world.maxCcdSubsteps =
    8;

  const events =
    new RAPIER.EventQueue(
      true,
    );

  const colliderMeta =
    new Map<
      number,
      ColliderMeta
    >();

  const groundFriction =
    clamp(
      sceneSurfaceFriction(
        input,
      ) *
        settings
          .globalFrictionMultiplier,
      0.02,
      2.5,
    );

  /*
   * Fixed ground: the top surface is exactly y=0.
   * Dynamic bodies sit on it under real gravity, allowing Rapier's contact
   * solver/friction to slow them instead of RoadSafe manually translating them.
   */
  const groundBody =
    world.createRigidBody(
      RAPIER
        .RigidBodyDesc
        .fixed()
        .setTranslation(
          widthMetres /
            2,
          -0.15,
          heightMetres /
            2,
        ),
    );

  const groundCollider =
    world.createCollider(
      RAPIER
        .ColliderDesc
        .cuboid(
          widthMetres /
              2 +
            25,
          0.15,
          heightMetres /
              2 +
            25,
        )
        .setFriction(
          groundFriction,
        )
        .setRestitution(
          0,
        ),
      groundBody,
    );

  colliderMeta.set(
    groundCollider.handle,
    {
      kind: "ground",
      id: "ground",
    },
  );

  const participantRuntimes:
    ParticipantRuntime[] = [];

  for (
    const participant
    of input.vehicles
  ) {
    const profile =
      participantProfile(
        participant,
      );

    if (!profile.enabled) {
      continue;
    }

    const initial =
      sampleAuthoredParticipantWithReaction(
        participant,
        startTime,
        widthMetres,
        heightMetres,
        primaryImpactTime,
      );

    const worldPosition =
      scenePositionToWorld(
        initial.position,
        widthMetres,
        heightMetres,
      );

    const bodyColliderDimensions =
      participantBodyColliderDimensions(
        participant,
        profile,
      );

    const rapierBody =
      world.createRigidBody(
        RAPIER
          .RigidBodyDesc
          .dynamic()
          .setTranslation(
            worldPosition.x,
            bodyColliderDimensions
              .heightMetres /
                2 +
              0.015,
            worldPosition.y,
          )
          .setRotation(
            yawQuaternionFromRoadSafeRotation(
              initial
                .rotationDegrees,
            ),
          )
          .setLinvel(
            initial
              .velocityWorld
              .x,
            0,
            initial
              .velocityWorld
              .y,
          )
          /*
           * V1 keeps vehicles upright while still allowing yaw rotation.
           * This gives RoadSafe stable top-down reconstruction motion now;
           * free 3-axis rotation/ragdolls are the next Rapier phase.
           */
          .enabledRotations(
            false,
            true,
            false,
          )
          .setLinearDamping(
            Math.max(
              0,
              settings.airDrag *
                0.35,
            ),
          )
          .setAngularDamping(
            Math.max(
              0.35,
              1.2 +
                profile
                  .lateralGrip *
                  1.4,
            ),
          )
          .setCcdEnabled(
            true,
          )
          .setAdditionalSolverIterations(
            4,
          )
          .setCanSleep(
            true,
          ),
      );

    const body =
      rapierBody as unknown as
        RapierBodyLike;

    const friction =
      clamp(
        profile
          .collisionFriction ??
          profile
            .rollingFriction,
        0,
        2.5,
      );

    const collider =
      world.createCollider(
        createParticipantCollider(
          participant,
          profile,
        )
          .setMass(
            Math.max(
              0.1,
              profile.massKg,
            ),
          )
          .setFriction(
            friction,
          )
          .setRestitution(
            participantContactRestitution(
              participant,
              profile,
            ),
          )
          /*
           * 15 mm contact skin per participant gives the solver a tiny
           * stabilization margin. Because the collider footprint already sits
           * slightly inside the visible model shell, this margin is visually
           * hidden instead of creating a noticeable gap.
           */
          .setContactSkin(
            0.015,
          )
          .setRestitutionCombineRule(
            RAPIER
              .CoefficientCombineRule
              .Min,
          )
          .setActiveEvents(
            RAPIER
              .ActiveEvents
              .COLLISION_EVENTS |
              RAPIER
                .ActiveEvents
                .CONTACT_FORCE_EVENTS,
          )
          .setContactForceEventThreshold(
            1,
          ),
        rapierBody,
      );

    colliderMeta.set(
      collider.handle,
      {
        kind:
          "participant",
        id:
          participant.id,
      },
    );

    participantRuntimes.push({
      participant,
      profile,
      body,
      samples: [],
    });
  }

  let fixedSceneObjectColliders =
    0;

  for (
    const object
    of input.sceneObjects
  ) {
    if (
      !object.visible
    ) {
      continue;
    }

    const profile =
      objectProfile(
        object,
      );

    /*
     * V1 includes solid object geometry. Potholes, oil/gravel and other
     * surface-region modifiers remain in the RoadSafe forensic layer until
     * Rapier material regions are added.
     */
    if (
      !profile.enabled ||
      !profile.collidable
    ) {
      continue;
    }

    const position =
      scenePositionToWorld(
        object.position,
        widthMetres,
        heightMetres,
      );

    const objectHeight =
      sceneObjectHeightMetres(
        object,
      );

    const body =
      world.createRigidBody(
        RAPIER
          .RigidBodyDesc
          .fixed()
          .setTranslation(
            position.x,
            objectHeight /
              2,
            position.y,
          )
          .setRotation(
            yawQuaternionFromRoadSafeRotation(
              object.rotation,
            ),
          ),
      );

    const collider =
      world.createCollider(
        createSceneObjectCollider(
          object,
          profile,
          objectHeight,
        )
          .setFriction(
            clamp(
              profile
                .collisionFriction ??
                0.7,
              0,
              2.5,
            ),
          )
          .setRestitution(
            clamp(
              profile
                .restitution,
              0,
              1,
            ),
          )
          .setContactSkin(
            0.01,
          )
          .setRestitutionCombineRule(
            RAPIER
              .CoefficientCombineRule
              .Min,
          )
          .setActiveEvents(
            RAPIER
              .ActiveEvents
              .COLLISION_EVENTS |
              RAPIER
                .ActiveEvents
                .CONTACT_FORCE_EVENTS,
          )
          .setContactForceEventThreshold(
            1,
          ),
        body,
      );

    colliderMeta.set(
      collider.handle,
      {
        kind:
          "sceneObject",
        id:
          object.id,
      },
    );

    fixedSceneObjectColliders +=
      1;
  }

  const collisionPairs =
    new Set<string>();

  const participantParticipantPairs =
    new Set<string>();

  const participantObjectPairs =
    new Set<string>();

  const participantIdsWithRigidBodyContact =
    new Set<string>();

  const emergencyBrakeParticipantIds =
    new Set<string>();

  const emergencyBrakeStartTimes =
    new Map<
      string,
      number
    >();

  let firstContactTime:
    number | undefined;

  let maximumContactForceNewtons =
    0;

  let currentSimulationTime =
    startTime;

  const normalSampleEverySteps =
    Math.max(
      1,
      Math.round(
        0.05 /
          fixedTimeStep,
      ),
    );

  const impactSampleEverySteps =
    Math.max(
      1,
      Math.round(
        (1 / 60) /
          fixedTimeStep,
      ),
    );

  let highFrequencySamplingUntil =
    Number.NEGATIVE_INFINITY;

  let stepIndex = 0;

  const collectSamples = (
    force = false,
  ) => {
    const highFrequency =
      currentSimulationTime <=
      highFrequencySamplingUntil;

    const interval =
      highFrequency
        ? impactSampleEverySteps
        : normalSampleEverySteps;

    if (
      !force &&
      stepIndex %
        interval !==
        0
    ) {
      return;
    }

    participantRuntimes.forEach(
      (runtime) => {
        const translation =
          runtime.body
            .translation();

        const velocity =
          runtime.body
            .linvel();

        const rotation =
          runtime.body
            .rotation();

        const sample: RapierSample = {
          timeSeconds:
            currentSimulationTime,

          position:
            worldPositionToScene(
              {
                x:
                  translation.x,
                y:
                  translation.z,
              },
              widthMetres,
              heightMetres,
            ),

          speedKmh:
            Math.hypot(
              velocity.x,
              velocity.z,
            ) *
            3.6,

          rotationDegrees:
            roadSafeRotationFromQuaternion(
              rotation,
            ),

          sleeping:
            runtime.body
              .isSleeping(),
        };

        const previous =
          runtime.samples[
            runtime.samples.length -
              1
          ];

        /*
         * Forced contact-frame sampling can occur on a normal sample step.
         * Replace an equal-time sample rather than creating duplicate
         * keyframes with the same timestamp.
         */
        if (
          previous &&
          Math.abs(
            previous.timeSeconds -
            sample.timeSeconds,
          ) <
            0.000001
        ) {
          runtime.samples[
            runtime.samples.length -
              1
          ] = sample;

          return;
        }

        runtime.samples.push(
          sample,
        );
      },
    );
  };

  collectSamples(
    true,
  );

  for (
    currentSimulationTime =
      startTime +
      fixedTimeStep;
    currentSimulationTime <=
      maximumSimulationTime +
        0.000001;
    currentSimulationTime +=
      fixedTimeStep
  ) {
    stepIndex += 1;

    let emergencyBrakeStartedThisStep =
      false;

    /*
     * [RoadSafe:RapierEmergencyBrakingV2]
     *
     * Before first contact, each vehicle can execute the deterministic
     * pre-impact emergency-braking window. Velocity is reduced by the
     * participant's brakingDecelerationMps2 at the fixed Rapier timestep.
     *
     * Once a real contact starts, Rapier owns post-impact motion and this
     * braking layer stops interfering.
     */
    if (
      firstContactTime ===
      undefined
    ) {
      participantRuntimes.forEach(
        (runtime) => {
          const translation =
            runtime.body
              .translation();

          const velocity =
            runtime.body
              .linvel();

          const horizontalSpeedMps =
            Math.hypot(
              velocity.x,
              velocity.z,
            );

          const horizontalSpeedKmh =
            horizontalSpeedMps *
            3.6;

          const scenePosition =
            worldPositionToScene(
              {
                x:
                  translation.x,
                y:
                  translation.z,
              },
              widthMetres,
              heightMetres,
            );

          const rotationDegrees =
            roadSafeRotationFromQuaternion(
              runtime.body
                .rotation(),
            );

          const reaction =
            getParticipantAccidentReactionState(
              runtime.participant,
              currentSimulationTime,
              scenePosition,
              rotationDegrees,
              horizontalSpeedKmh,
              primaryImpactTime,
            );

          if (
            !reaction
              .emergencyBraking ||
            horizontalSpeedMps <=
              0.001
          ) {
            return;
          }

          const participantId =
            runtime
              .participant
              .id;

          emergencyBrakeParticipantIds.add(
            participantId,
          );

          if (
            !emergencyBrakeStartTimes.has(
              participantId,
            )
          ) {
            emergencyBrakeStartTimes.set(
              participantId,
              currentSimulationTime,
            );

            emergencyBrakeStartedThisStep =
              true;

            highFrequencySamplingUntil =
              Math.max(
                highFrequencySamplingUntil,
                primaryImpactTime +
                  0.25,
              );
          }

          const nextSpeedMps =
            Math.max(
              0,
              horizontalSpeedMps -
              reaction
                .brakingDecelerationMps2 *
                fixedTimeStep,
            );

          const ratio =
            horizontalSpeedMps >
              0.000001
              ? nextSpeedMps /
                horizontalSpeedMps
              : 0;

          runtime.body.setLinvel(
            {
              x:
                velocity.x *
                ratio,
              y:
                velocity.y,
              z:
                velocity.z *
                ratio,
            },
            true,
          );
        },
      );
    }

    world.step(
      events,
    );

    let relevantContactStartedThisStep =
      false;

    events.drainCollisionEvents(
      (
        firstHandle,
        secondHandle,
        started,
      ) => {
        if (!started) {
          return;
        }

        const first =
          colliderMeta.get(
            firstHandle,
          );

        const second =
          colliderMeta.get(
            secondHandle,
          );

        if (
          !first ||
          !second ||
          first.kind ===
            "ground" ||
          second.kind ===
            "ground"
        ) {
          return;
        }

        const pairKey = [
          `${first.kind}:${first.id}`,
          `${second.kind}:${second.id}`,
        ]
          .sort()
          .join("|");

        collisionPairs.add(
          pairKey,
        );

        relevantContactStartedThisStep =
          true;

        if (
          firstContactTime ===
          undefined
        ) {
          firstContactTime =
            currentSimulationTime;

          highFrequencySamplingUntil =
            currentSimulationTime +
            0.75;
        }

        if (
          first.kind ===
            "participant" &&
          second.kind ===
            "participant"
        ) {
          participantParticipantPairs.add(
            pairKey,
          );

          participantIdsWithRigidBodyContact.add(
            first.id,
          );

          participantIdsWithRigidBodyContact.add(
            second.id,
          );
        } else if (
          first.kind ===
            "participant" ||
          second.kind ===
            "participant"
        ) {
          participantObjectPairs.add(
            pairKey,
          );

          participantIdsWithRigidBodyContact.add(
            first.kind ===
              "participant"
              ? first.id
              : second.id,
          );
        }
      },
    );

    events.drainContactForceEvents(
      (event) => {
        const first =
          colliderMeta.get(
            event.collider1(),
          );

        const second =
          colliderMeta.get(
            event.collider2(),
          );

        if (
          !first ||
          !second ||
          first.kind ===
            "ground" ||
          second.kind ===
            "ground"
        ) {
          return;
        }

        maximumContactForceNewtons =
          Math.max(
            maximumContactForceNewtons,
            event
              .totalForceMagnitude(),
          );
      },
    );

    /*
     * Always export the exact solver state from the first actual contact step.
     * This eliminates the visible interpolation jump/penetration caused by a
     * trajectory whose first post-impact sample was tens of milliseconds late.
     */
    collectSamples(
      relevantContactStartedThisStep ||
      emergencyBrakeStartedThisStep,
    );

    const afterImpact =
      currentSimulationTime >=
      primaryImpactTime;

    const allSettled =
      participantRuntimes
        .length >
        0 &&
      participantRuntimes.every(
        (runtime) => {
          const velocity =
            runtime.body
              .linvel();

          const horizontalSpeedKmh =
            Math.hypot(
              velocity.x,
              velocity.z,
            ) *
            3.6;

          return (
            runtime.body
              .isSleeping() ||
            horizontalSpeedKmh <=
              settings
                .stopSpeedKmh
          );
        },
      );

    if (
      afterImpact &&
      allSettled
    ) {
      collectSamples(
        true,
      );

      break;
    }
  }

  const actualEndTime =
    Math.min(
      currentSimulationTime,
      maximumSimulationTime,
    );

  const takeoverTime =
    firstContactTime ??
    primaryImpactTime;

  /*
   * Do not let a no-contact Rapier pass silently replace RoadSafe's existing
   * deterministic path. That situation is diagnostic: it means the authored
   * approach geometry did not produce a rigid-body contact in the Rapier world.
   */
  const useRapierTrajectories =
    firstContactTime !==
    undefined;

  let generatedPathPoints =
    0;

  let vehicles =
    forensic.vehicles;

  if (
    useRapierTrajectories
  ) {
    vehicles =
      forensic.vehicles.map(
        (participant) => {
          const runtime =
            participantRuntimes.find(
              (candidate) =>
                candidate
                  .participant
                  .id ===
                participant.id,
            );

          const authored =
            stripPhysicsPoints(
              participant,
            );

          if (
            !runtime ||
            runtime.samples
              .length ===
              0
          ) {
            return syncLegacyParticipantFields({
              ...participant,
              pathPoints:
                authored,
            });
          }

          const brakeStartTime =
            emergencyBrakeStartTimes.get(
              participant.id,
            );

          const trajectoryStartTime =
            brakeStartTime ??
            takeoverTime;

          const samples =
            runtime.samples.filter(
              (sample) =>
                sample.timeSeconds >=
                trajectoryStartTime -
                  fixedTimeStep *
                    1.5,
            );

          if (
            samples.length ===
            0
          ) {
            return syncLegacyParticipantFields({
              ...participant,
              pathPoints:
                authored,
            });
          }

          let impactPointWritten =
            false;

          const rapierPoints =
            samples.map(
              (
                sample,
                index,
              ) => {
                const beforeContact =
                  sample.timeSeconds <
                  takeoverTime -
                    fixedTimeStep *
                      0.5;

                const firstImpactSample =
                  !beforeContact &&
                  !impactPointWritten;

                if (
                  firstImpactSample
                ) {
                  impactPointWritten =
                    true;
                }

                const last =
                  index ===
                    samples.length -
                      1 &&
                  (
                    sample.sleeping ||
                    sample.speedKmh <=
                      settings
                        .stopSpeedKmh
                  );

                const action:
                  MovementPathPoint["action"] =
                    beforeContact
                      ? "Brake"
                      : firstImpactSample
                        ? "Impact"
                        : last
                          ? "Stop"
                          : "Slide";

                const label =
                  beforeContact
                    ? "Rapier emergency braking"
                    : firstImpactSample
                      ? "Rapier rigid-body contact"
                      : last
                        ? "Rapier natural rest"
                        : "Rapier post-impact motion";

                return makeRapierPoint(
                  participant.id,
                  sample,
                  index,
                  action,
                  label,
                );
              },
            );

          generatedPathPoints +=
            rapierPoints.length;

          return syncLegacyParticipantFields({
            ...participant,
            physics:
              runtime.profile,
            pathPoints:
              sortMovementPathPoints([
                ...authored,
                ...rapierPoints,
              ]),
            /*
             * Keep visual/model scale entirely independent. Only canonical
             * route/playback motion is being replaced by Rapier here.
             */
          });
        },
      );
  }

  let warnings =
    forensic
      .lastPhysicsSimulation
      ?.warnings ??
    [];

  warnings =
    addWarning(
      warnings,
      "Rapier 3D deterministic rigid-body dynamics is active with asset-matched rounded participant body colliders, 120 Hz-or-faster stepping, contact skin stabilization, and high-frequency impact sampling. RoadSafe Physics V2 remains the forensic calculation and audit layer.",
    );

  warnings =
    addWarning(
      warnings,
      "Rapier V1 keeps participant bodies upright and allows yaw rotation only. Full 3-axis vehicle rollover and articulated human ragdolls are not enabled yet.",
    );

  if (
    useRapierTrajectories
  ) {
    warnings =
      addWarning(
        warnings,
        `Rapier detected the first relevant rigid-body contact at ${takeoverTime.toFixed(
          3,
        )} s and generated the shared braking/contact/post-impact trajectory used by 2D, 3D and AR playback.`,
      );
  } else {
    warnings =
      addWarning(
        warnings,
        "Rapier did not find a participant/solid-object contact in the short authored approach window, so the existing RoadSafe deterministic post-impact path was retained. Review approach geometry, dimensions, headings and speeds.",
      );
  }

  if (
    currentSimulationTime >
      maximumSimulationTime
  ) {
    warnings =
      addWarning(
        warnings,
        "Rapier reached the post-impact safety time limit before every body settled.",
      );
  }

  if (
    emergencyBrakeParticipantIds.size >
    0
  ) {
    warnings =
      addWarning(
        warnings,
        `Emergency braking was applied before first Rapier contact for ${emergencyBrakeParticipantIds.size} participant(s), using each participant's configured braking deceleration and the deterministic split-second reaction window.`,
      );
  }

  const forensicSummary =
    forensic
      .lastPhysicsSimulation;

  const participantVisualDamage =
    useRapierTrajectories
      ? deriveParticipantVisualDamage({
          summary:
            forensicSummary,
          participants:
            input.vehicles,
          participantIdsWithRigidBodyContact,
        })
      : [];

  if (
    participantVisualDamage.length >
    0
  ) {
    warnings =
      addWarning(
        warnings,
        "Visible crush/damage is a simplified RoadSafe visualization derived from a confirmed Rapier body contact plus the existing forensic impact response. It is not a validated structural crashworthiness or repair-damage calculation.",
      );
  }

  const lastPhysicsSimulation =
    forensicSummary
      ? {
          ...forensicSummary,

          dynamicsEngine:
            "Rapier 3D Deterministic" as const,

          dynamicsEngineVersion:
            `${RAPIER_PACKAGE}@${RAPIER_VERSION}`,

          ranAt:
            new Date()
              .toISOString(),

          generatedPathPoints:
            useRapierTrajectories
              ? generatedPathPoints
              : forensicSummary
                  .generatedPathPoints,

          simulatedDurationSeconds:
            useRapierTrajectories
              ? Number(
                  actualEndTime
                    .toFixed(
                      4,
                    ),
                )
              : forensicSummary
                  .simulatedDurationSeconds,

          warnings,

          participantVisualDamage,

          rapierDynamics: {
            engine:
              "Rapier 3D Deterministic" as const,

            packageName:
              RAPIER_PACKAGE as
                "@dimforge/rapier3d-deterministic-compat",

            packageVersion:
              RAPIER_VERSION as
                "0.19.3",

            fixedTimeStepSeconds:
              Number(
                fixedTimeStep
                  .toFixed(
                    6,
                  ),
              ),

            maxCcdSubsteps:
              8,

            dynamicParticipantBodies:
              participantRuntimes
                .length,

            fixedSceneObjectColliders,

            collisionStarts:
              collisionPairs.size,

            participantParticipantContacts:
              participantParticipantPairs
                .size,

            participantObjectContacts:
              participantObjectPairs
                .size,

            maximumContactForceNewtons:
              Number(
                maximumContactForceNewtons
                  .toFixed(
                    2,
                  ),
              ),

            firstContactTimeSeconds:
              firstContactTime ===
              undefined
                ? undefined
                : Number(
                    firstContactTime
                      .toFixed(
                        4,
                      ),
                  ),

            takeoverTimeSeconds:
              Number(
                takeoverTime
                  .toFixed(
                    4,
                  ),
              ),

            generatedPathPoints:
              useRapierTrajectories
                ? generatedPathPoints
                : 0,

            simulatedDurationSeconds:
              Number(
                actualEndTime
                  .toFixed(
                    4,
                  ),
              ),

            usedForPostImpactTrajectories:
              useRapierTrajectories,

            participantColliderModel:
              "Asset-matched rounded body" as const,
          },
        }
      : undefined;

  events.free();
  world.free();

  return {
    ...forensic,
    vehicles,
    lastPhysicsSimulation,
  };
}
