import type {
  MovementPathPoint,
  ReconstructionPosition,
  ReconstructionVehicleType,
} from "../types/reconstruction";
import type {
  FieldSceneCalibration,
  GeoCoordinate,
} from "../types/fieldPlacement";

const EARTH_RADIUS_METRES = 6_371_008.8;
const PHYSICS_POINT_PREFIXES = [
  "physics-point-",
  "detected-impact-",
  "physics-transition-",
  "legacy-impact-",
];

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.min(maximum, Math.max(minimum, value));
}

function distance(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
): number {
  return Math.hypot(second.x - first.x, second.y - first.y);
}

function headingDegrees(
  from: ReconstructionPosition,
  to: ReconstructionPosition,
  fallback = 0,
): number {
  const x = to.x - from.x;
  const y = to.y - from.y;
  if (Math.hypot(x, y) < 0.000001) return fallback;
  return ((Math.atan2(y, x) * 180) / Math.PI + 360) % 360;
}

function isPhysicsPoint(point: MovementPathPoint): boolean {
  return (
    PHYSICS_POINT_PREFIXES.some((prefix) => point.id.startsWith(prefix)) ||
    point.notes?.includes("Generated by the RoadSafe deterministic 2D physics preview.") ||
    point.notes?.includes("Physics-generated event.") ||
    false
  );
}

function catmullRomMidpoint(
  previous: ReconstructionPosition,
  start: ReconstructionPosition,
  end: ReconstructionPosition,
  following: ReconstructionPosition,
): ReconstructionPosition {
  const t = 0.5;
  const t2 = t * t;
  const t3 = t2 * t;

  return {
    x: clamp(
      0.5 *
        (2 * start.x +
          (-previous.x + end.x) * t +
          (2 * previous.x - 5 * start.x + 4 * end.x - following.x) * t2 +
          (-previous.x + 3 * start.x - 3 * end.x + following.x) * t3),
      0,
      100,
    ),
    y: clamp(
      0.5 *
        (2 * start.y +
          (-previous.y + end.y) * t +
          (2 * previous.y - 5 * start.y + 4 * end.y - following.y) * t2 +
          (-previous.y + 3 * start.y - 3 * end.y + following.y) * t3),
      0,
      100,
    ),
  };
}

function relabelAuthoredPoints(points: MovementPathPoint[]): MovementPathPoint[] {
  return points.map((point, index) => ({
    ...point,
    label:
      point.action === "Impact"
        ? `Point ${index + 1} · Primary collision`
        : point.action === "Start" || point.action === "Enter Scene"
          ? `Point ${index + 1} · Start`
          : point.action === "Stop"
            ? `Point ${index + 1} · Observed rest`
            : `Point ${index + 1}`,
  }));
}

export function alignAuthoredRouteToTangents(
  pathPoints: MovementPathPoint[],
): MovementPathPoint[] {
  const authored = pathPoints
    .filter((point) => !isPhysicsPoint(point))
    .slice()
    .sort((first, second) => first.timeSeconds - second.timeSeconds);
  const physics = pathPoints
    .filter(isPhysicsPoint)
    .slice()
    .sort((first, second) => first.timeSeconds - second.timeSeconds);

  const aligned = authored.map((point, index) => {
    const previous = authored[Math.max(0, index - 1)] ?? point;
    const next = authored[Math.min(authored.length - 1, index + 1)] ?? point;
    let rotation = point.rotation;

    if (authored.length > 1) {
      if (index === 0) {
        rotation = headingDegrees(point.position, next.position, rotation);
      } else if (index === authored.length - 1) {
        rotation = headingDegrees(previous.position, point.position, rotation);
      } else {
        rotation = headingDegrees(previous.position, next.position, rotation);
      }
    }

    return {
      ...point,
      rotation,
    };
  });

  return [...relabelAuthoredPoints(aligned), ...physics].sort(
    (first, second) => first.timeSeconds - second.timeSeconds,
  );
}

export function createProgressiveParticipantRoute({
  startPosition,
  impactPosition,
  durationSeconds,
  speedKmh,
  participantType,
  createId,
  pointCount = 8,
}: {
  startPosition: ReconstructionPosition;
  impactPosition: ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType: ReconstructionVehicleType;
  createId: (prefix: string) => string;
  pointCount?: number;
}): MovementPathPoint[] {
  const count = Math.max(3, Math.min(18, Math.round(pointCount)));
  const impactTimeSeconds = clamp(durationSeconds * 0.55, 0.8, durationSeconds - 0.1);
  const route: MovementPathPoint[] = [];

  for (let index = 0; index < count; index += 1) {
    const progress = index / Math.max(1, count - 1);
    const smoothProgress = progress * progress * (3 - 2 * progress);
    const position = {
      x: startPosition.x + (impactPosition.x - startPosition.x) * smoothProgress,
      y: startPosition.y + (impactPosition.y - startPosition.y) * smoothProgress,
    };
    const finalPoint = index === count - 1;

    route.push({
      id: createId(finalPoint ? "path-impact" : index === 0 ? "path-start" : "path-point"),
      label: finalPoint
        ? `Point ${index + 1} · Primary collision`
        : index === 0
          ? "Point 1 · Start"
          : `Point ${index + 1}`,
      position,
      timeSeconds: Number((impactTimeSeconds * progress).toFixed(3)),
      speedKmh: finalPoint ? Math.max(0, speedKmh * 0.92) : speedKmh,
      rotation: 0,
      action: finalPoint
        ? "Impact"
        : index === 0
          ? participantType === "Pedestrian" ||
            participantType === "Officer" ||
            participantType === "Witness"
            ? "Enter Scene"
            : "Start"
          : "Cruise",
      notes: "",
    });
  }

  return alignAuthoredRouteToTangents(route);
}

export function insertProgressiveRoutePoint({
  pathPoints,
  selectedPointId,
  durationSeconds,
  createId,
}: {
  pathPoints: MovementPathPoint[];
  selectedPointId: string | null;
  durationSeconds: number;
  createId: (prefix: string) => string;
}): {
  pathPoints: MovementPathPoint[];
  insertedPointId: string;
} {
  const authored = pathPoints
    .filter((point) => !isPhysicsPoint(point))
    .slice()
    .sort((first, second) => first.timeSeconds - second.timeSeconds);
  const physics = pathPoints.filter(isPhysicsPoint);

  if (authored.length < 2) {
    throw new Error("At least two authored route points are required.");
  }

  let segmentIndex = selectedPointId
    ? authored.findIndex((point) => point.id === selectedPointId)
    : -1;

  if (segmentIndex < 0 || segmentIndex >= authored.length - 1) {
    let largestDistance = -1;
    segmentIndex = 0;
    for (let index = 0; index < authored.length - 1; index += 1) {
      const segmentDistance = distance(
        authored[index].position,
        authored[index + 1].position,
      );
      if (segmentDistance > largestDistance) {
        largestDistance = segmentDistance;
        segmentIndex = index;
      }
    }
  }

  const start = authored[segmentIndex];
  const end = authored[segmentIndex + 1];
  const previous = authored[Math.max(0, segmentIndex - 1)] ?? start;
  const following = authored[Math.min(authored.length - 1, segmentIndex + 2)] ?? end;
  const position = catmullRomMidpoint(
    previous.position,
    start.position,
    end.position,
    following.position,
  );
  const insertedPointId = createId("path-point");
  const inserted: MovementPathPoint = {
    id: insertedPointId,
    label: "New route point",
    position,
    timeSeconds: clamp(
      (start.timeSeconds + end.timeSeconds) / 2,
      0.01,
      Math.max(0.01, durationSeconds - 0.01),
    ),
    speedKmh: (start.speedKmh + end.speedKmh) / 2,
    rotation: headingDegrees(start.position, end.position, start.rotation),
    action: "Cruise",
    notes: "",
  };

  const nextAuthored = [
    ...authored.slice(0, segmentIndex + 1),
    inserted,
    ...authored.slice(segmentIndex + 1),
  ];

  return {
    insertedPointId,
    pathPoints: alignAuthoredRouteToTangents([...nextAuthored, ...physics]),
  };
}

export function setParticipantImpactPoint({
  pathPoints,
  pointId,
  durationSeconds,
}: {
  pathPoints: MovementPathPoint[];
  pointId: string;
  durationSeconds: number;
}): MovementPathPoint[] {
  const authored = pathPoints
    .filter((point) => !isPhysicsPoint(point))
    .slice()
    .sort((first, second) => first.timeSeconds - second.timeSeconds);
  const physics = pathPoints.filter(isPhysicsPoint);
  const selectedIndex = authored.findIndex((point) => point.id === pointId);

  if (selectedIndex < 0) return pathPoints;

  const impactTime = clamp(
    authored[selectedIndex].timeSeconds,
    0.05,
    Math.max(0.05, durationSeconds - 0.05),
  );

  const updated = authored.map((point, index) => {
    if (index === selectedIndex) {
      return {
        ...point,
        action: "Impact" as const,
        timeSeconds: impactTime,
      };
    }

    if (point.action === "Impact") {
      return {
        ...point,
        action: index === 0 ? ("Start" as const) : ("Cruise" as const),
      };
    }

    return point;
  });

  return alignAuthoredRouteToTangents([...updated, ...physics]);
}

export function getAuthoredImpactPoint(
  pathPoints: MovementPathPoint[],
): MovementPathPoint | null {
  return (
    pathPoints
      .filter((point) => !isPhysicsPoint(point))
      .find((point) => point.action === "Impact") ?? null
  );
}

export function geoCoordinateToScenePosition(
  calibration: FieldSceneCalibration,
  coordinate: GeoCoordinate,
): ReconstructionPosition {
  const originLatitudeRadians =
    (calibration.origin.latitude * Math.PI) / 180;
  const coordinateLatitudeRadians =
    (coordinate.latitude * Math.PI) / 180;
  const deltaLatitudeRadians =
    ((coordinate.latitude - calibration.origin.latitude) * Math.PI) / 180;
  const deltaLongitudeRadians =
    ((coordinate.longitude - calibration.origin.longitude) * Math.PI) / 180;
  const averageLatitude =
    (originLatitudeRadians + coordinateLatitudeRadians) / 2;

  const eastMetres =
    deltaLongitudeRadians * EARTH_RADIUS_METRES * Math.cos(averageLatitude);
  const northMetres = deltaLatitudeRadians * EARTH_RADIUS_METRES;
  const rotationRadians = (calibration.rotationDegrees * Math.PI) / 180;
  const xAxis = {
    east: Math.sin(rotationRadians),
    north: Math.cos(rotationRadians),
  };
  const rightAxis = {
    east: Math.cos(rotationRadians),
    north: -Math.sin(rotationRadians),
  };
  const ySign = calibration.yAxisSide === "Left" ? -1 : 1;
  const xMetres = eastMetres * xAxis.east + northMetres * xAxis.north;
  const yMetres =
    (eastMetres * rightAxis.east + northMetres * rightAxis.north) * ySign;

  return {
    x: clamp((xMetres / Math.max(0.01, calibration.sceneWidthMetres)) * 100, 0, 100),
    y: clamp((yMetres / Math.max(0.01, calibration.sceneHeightMetres)) * 100, 0, 100),
  };
}
