import {
  solveMetricRouteTiming,
  type MetricSceneDimensions,
} from "./reconstructionMotionKinematics";
import type {
  MovementAction,
  MovementPathPoint,
  ReconstructionPosition,
  ReconstructionVehicleType,
} from "../types/reconstruction";

import type {
  FieldSceneCalibration,
  GeoCoordinate,
} from "../types/fieldPlacement";

import {
  AUTO_ROAD_CURVE_NOTE_MARKER,
  createRoadAlignedParticipantRoute,
  stabiliseAutomaticRoadMovementRoute,
  isAutoRoadCurvePoint,
  learnFromInvestigatorRoadRoute,
} from "./reconstructionRoadRouting";

const EARTH_RADIUS_METRES = 6_371_008.8;

export const POINT_Z_ID_PREFIX = "path-impact-z-";
export const POINT_Z_NOTE_MARKER = "[RoadSafe:PointZ]";
export const POINT_ONE_NOTE_MARKER = "[RoadSafe:Point1]";

/*
 * These markers distinguish deliberate investigator anchors from the temporary
 * samples created while a route is drawn with the pointer.
 */
export const FREEHAND_ROUTE_NOTE_MARKER =
  "[RoadSafe:FreehandRouteSample]";

export const MANUAL_ROUTE_ANCHOR_NOTE_MARKER =
  "[RoadSafe:ManualRouteAnchor]";

const PHYSICS_POINT_PREFIXES = [
  "physics-point-",
  "detected-impact-",
  "physics-transition-",
  "legacy-impact-",
] as const;

const PHYSICS_NOTE_MARKERS = [
  "Generated by the RoadSafe deterministic 2D physics preview.",
  "Generated at the first swept body contact found along the participant routes.",
  "Physics takes over from the participant's guided route",
  "Physics-generated event.",
] as const;

const POST_IMPACT_ONLY_ACTIONS =
  new Set<MovementAction>([
    "Ricochet",
    "Deflect",
    "Slide",
    "Fall",
  ]);

const HUMAN_TYPES =
  new Set<ReconstructionVehicleType>([
    "Pedestrian",
    "Officer",
    "Witness",
  ]);

export type AuthoredRoutePointRole =
  | "PointOne"
  | "Intermediate"
  | "PointZ"
  | "Physics";

export interface NormalisePointZRouteOptions {
  pathPoints: MovementPathPoint[];
  collisionPosition?: ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType: ReconstructionVehicleType;
  worldDimensions?: MetricSceneDimensions;
  createId?: (prefix: string) => string;
}

export interface CreateLockedParticipantRouteOptions {
  startPosition: ReconstructionPosition;
  collisionPosition: ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType: ReconstructionVehicleType;
  worldDimensions?: MetricSceneDimensions;
  createId: (prefix: string) => string;
  impactTimeSeconds?: number;
}

export interface InsertProgressiveRoutePointOptions {
  pathPoints: MovementPathPoint[];
  selectedPointId: string | null;
  durationSeconds: number;
  worldDimensions?: MetricSceneDimensions;
  createId: (prefix: string) => string;
}

function defaultCreateId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random()
    .toString(36)
    .slice(2, 8)}`;
}

function clamp(
  value: number,
  minimum: number,
  maximum: number,
): number {
  return Math.min(
    maximum,
    Math.max(minimum, value),
  );
}

function samePosition(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
): boolean {
  return (
    Math.abs(first.x - second.x) <= 0.000001 &&
    Math.abs(first.y - second.y) <= 0.000001
  );
}

function distance(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
): number {
  return Math.hypot(
    second.x - first.x,
    second.y - first.y,
  );
}

function headingDegrees(
  from: ReconstructionPosition,
  to: ReconstructionPosition,
  fallback = 0,
): number {
  const x = to.x - from.x;
  const y = to.y - from.y;

  if (Math.hypot(x, y) < 0.000001) {
    return fallback;
  }

  return (
    (
      Math.atan2(y, x) *
      180
    ) /
      Math.PI +
    360
  ) % 360;
}

function normaliseNotes(
  notes: string | undefined,
  marker: string,
): string {
  const cleaned = (notes ?? "")
    .replace(POINT_Z_NOTE_MARKER, "")
    .replace(POINT_ONE_NOTE_MARKER, "")
    .trim();

  return cleaned
    ? `${marker}\n${cleaned}`
    : marker;
}

function addNoteMarker(
  notes: string | undefined,
  marker: string,
): string {
  const current = (notes ?? "").trim();

  if (current.includes(marker)) {
    return current;
  }

  return current
    ? `${marker}\n${current}`
    : marker;
}

export function isPhysicsGeneratedRoutePoint(
  point: MovementPathPoint,
): boolean {
  return (
    PHYSICS_POINT_PREFIXES.some(
      (prefix) =>
        point.id.startsWith(prefix),
    ) ||
    PHYSICS_NOTE_MARKERS.some(
      (marker) =>
        point.notes?.includes(marker),
    )
  );
}

export function isPointZ(
  point: MovementPathPoint,
): boolean {
  return (
    point.id.startsWith(
      POINT_Z_ID_PREFIX,
    ) ||
    point.notes?.includes(
      POINT_Z_NOTE_MARKER,
    ) === true ||
    /^point\s*z\b/i.test(
      point.label.trim(),
    )
  );
}

export function isPointOne(
  point: MovementPathPoint,
): boolean {
  return (
    point.notes?.includes(
      POINT_ONE_NOTE_MARKER,
    ) === true ||
    /^point\s*1\b/i.test(
      point.label.trim(),
    )
  );
}

export function getAuthoredRoutePointRole(
  point: MovementPathPoint,
  authoredPoints?: MovementPathPoint[],
): AuthoredRoutePointRole {
  if (
    isPhysicsGeneratedRoutePoint(point)
  ) {
    return "Physics";
  }

  if (isPointZ(point)) {
    return "PointZ";
  }

  if (
    isPointOne(point) ||
    authoredPoints?.[0]?.id === point.id
  ) {
    return "PointOne";
  }

  return "Intermediate";
}

export function canDeleteAuthoredRoutePoint(
  point: MovementPathPoint,
  authoredPoints?: MovementPathPoint[],
): boolean {
  return (
    getAuthoredRoutePointRole(
      point,
      authoredPoints,
    ) === "Intermediate"
  );
}

export function canMoveAuthoredRoutePoint(
  point: MovementPathPoint,
): boolean {
  return (
    !isPointZ(point) &&
    !isPhysicsGeneratedRoutePoint(point)
  );
}

function catmullRomMidpoint(
  previous: ReconstructionPosition,
  start: ReconstructionPosition,
  end: ReconstructionPosition,
  following: ReconstructionPosition,
): ReconstructionPosition {
  const t = 0.5;
  const t2 = t * t;
  const t3 = t2 * t;

  return {
    x: clamp(
      0.5 *
        (
          2 * start.x +
          (
            -previous.x +
            end.x
          ) *
            t +
          (
            2 * previous.x -
            5 * start.x +
            4 * end.x -
            following.x
          ) *
            t2 +
          (
            -previous.x +
            3 * start.x -
            3 * end.x +
            following.x
          ) *
            t3
        ),
      0,
      100,
    ),
    y: clamp(
      0.5 *
        (
          2 * start.y +
          (
            -previous.y +
            end.y
          ) *
            t +
          (
            2 * previous.y -
            5 * start.y +
            4 * end.y -
            following.y
          ) *
            t2 +
          (
            -previous.y +
            3 * start.y -
            3 * end.y +
            following.y
          ) *
            t3
        ),
      0,
      100,
    ),
  };
}

function findLegacyImpactIndex(
  authored: MovementPathPoint[],
): number {
  const explicitPointZIndex =
    authored.findIndex(isPointZ);

  if (explicitPointZIndex >= 0) {
    return explicitPointZIndex;
  }

  const impactIndex =
    authored.findIndex(
      (point) =>
        point.action === "Impact",
    );

  return impactIndex >= 0
    ? impactIndex
    : Math.max(
        1,
        authored.length - 1,
      );
}

function getStartAction(
  type: ReconstructionVehicleType,
): MovementAction {
  return HUMAN_TYPES.has(type)
    ? "Enter Scene"
    : "Start";
}

function sanitiseIntermediateAction(
  action: MovementAction,
): MovementAction {
  if (
    action === "Impact" ||
    action === "Start" ||
    action === "Enter Scene" ||
    POST_IMPACT_ONLY_ACTIONS.has(action)
  ) {
    return "Cruise";
  }

  return action;
}

function relabelPointZRoute(
  authored: MovementPathPoint[],
): MovementPathPoint[] {
  if (authored.length === 0) {
    return authored;
  }

  return authored.map(
    (point, index) => {
      if (index === 0) {
        return {
          ...point,
          label: "Point 1 · Start",
          notes: normaliseNotes(
            point.notes,
            POINT_ONE_NOTE_MARKER,
          ),
        };
      }

      if (
        index ===
        authored.length - 1
      ) {
        return {
          ...point,
          label:
            "Point Z · Primary collision",
          notes: normaliseNotes(
            point.notes,
            POINT_Z_NOTE_MARKER,
          ),
        };
      }

      return {
        ...point,
        label: `Point ${index + 1}`,
        notes: (point.notes ?? "")
          .replace(
            POINT_Z_NOTE_MARKER,
            "",
          )
          .replace(
            POINT_ONE_NOTE_MARKER,
            "",
          )
          .trim(),
      };
    },
  );
}

function alignAuthoredOnlyToTangents(
  authored: MovementPathPoint[],
): MovementPathPoint[] {
  return authored.map(
    (point, index) => {
      const previous =
        authored[
          Math.max(0, index - 1)
        ] ?? point;

      const next =
        authored[
          Math.min(
            authored.length - 1,
            index + 1,
          )
        ] ?? point;

      let rotation = point.rotation;

      if (authored.length > 1) {
        rotation =
          index === 0
            ? headingDegrees(
                point.position,
                next.position,
                rotation,
              )
            : index ===
                authored.length - 1
              ? headingDegrees(
                  previous.position,
                  point.position,
                  rotation,
                )
              : headingDegrees(
                  previous.position,
                  next.position,
                  rotation,
                );
      }

      return {
        ...point,
        rotation,
      };
    },
  );
}

/*
 * [RoadSafe:MetricAuthoredRouteTimingV1]
 *
 * Point Z time remains authoritative so all participants can share one
 * collision instant. Point speeds are scaled together so the entered relative
 * speed profile, physical distance and authored timestamps agree.
 */
function redistributeAuthoredTimes(
  authored: MovementPathPoint[],
  durationSeconds: number,
  fallbackSpeedKmh: number,
  worldDimensions?:
    MetricSceneDimensions,
): MovementPathPoint[] {
  if (authored.length <= 1) {
    return authored;
  }

  const finalIndex =
    authored.length - 1;

  const existingImpactTime =
    authored[finalIndex]
      .timeSeconds;

  const impactTimeSeconds =
    clamp(
      Number.isFinite(
        existingImpactTime,
      )
        ? existingImpactTime
        : durationSeconds * 0.55,
      0.1,
      Math.max(
        0.1,
        durationSeconds - 0.05,
      ),
    );

  const timing =
    solveMetricRouteTiming(
      authored.map(
        (point) => ({
          position:
            point.position,

          speedKmh:
            point.speedKmh,

          stopped:
            point.action ===
            "Stop",
        }),
      ),
      impactTimeSeconds,
      fallbackSpeedKmh,
      worldDimensions,
    );

  return authored.map(
    (point, index) => ({
      ...point,

      timeSeconds:
        timing.timesSeconds[index] ??
        (
          index === finalIndex
            ? impactTimeSeconds
            : point.timeSeconds
        ),

      speedKmh:
        point.action === "Stop"
          ? 0
          : (
              timing.speedsKmh[index] ??
              point.speedKmh
            ),
    }),
  );
}

function ensureDifferentStartAndImpact(
  startPosition: ReconstructionPosition,
  impactPosition: ReconstructionPosition,
): ReconstructionPosition {
  if (
    !samePosition(
      startPosition,
      impactPosition,
    )
  ) {
    return startPosition;
  }

  return {
    x: clamp(
      startPosition.x - 12,
      0,
      100,
    ),
    y: startPosition.y,
  };
}

function distanceFromPointToSegment(
  point: ReconstructionPosition,
  start: ReconstructionPosition,
  end: ReconstructionPosition,
): number {
  const segmentX =
    end.x - start.x;

  const segmentY =
    end.y - start.y;

  const segmentLengthSquared =
    segmentX * segmentX +
    segmentY * segmentY;

  if (
    segmentLengthSquared <
    0.000001
  ) {
    return distance(point, start);
  }

  const projection = clamp(
    (
      (
        point.x -
        start.x
      ) *
        segmentX +
      (
        point.y -
        start.y
      ) *
        segmentY
    ) /
      segmentLengthSquared,
    0,
    1,
  );

  const projected = {
    x:
      start.x +
      segmentX * projection,
    y:
      start.y +
      segmentY * projection,
  };

  return distance(
    point,
    projected,
  );
}

function isProtectedRouteAnchor(
  point: MovementPathPoint,
  index: number,
  points: MovementPathPoint[],
): boolean {
  if (
    index === 0 ||
    index === points.length - 1
  ) {
    return true;
  }

  if (
    point.notes?.includes(
      MANUAL_ROUTE_ANCHOR_NOTE_MARKER,
    ) === true
  ) {
    return true;
  }

  if (point.linkedSceneObjectId) {
    return true;
  }

  return point.action !== "Cruise";
}

function simplifyRouteSection(
  points: MovementPathPoint[],
  tolerance: number,
): MovementPathPoint[] {
  if (points.length <= 2) {
    return points;
  }

  const first = points[0];
  const last =
    points[
      points.length - 1
    ];

  let furthestIndex = -1;
  let furthestDistance = 0;

  for (
    let index = 1;
    index <
    points.length - 1;
    index += 1
  ) {
    const pointDistance =
      distanceFromPointToSegment(
        points[index].position,
        first.position,
        last.position,
      );

    if (
      pointDistance >
      furthestDistance
    ) {
      furthestDistance =
        pointDistance;

      furthestIndex = index;
    }
  }

  if (
    furthestIndex < 0 ||
    furthestDistance <= tolerance
  ) {
    return [first, last];
  }

  const left =
    simplifyRouteSection(
      points.slice(
        0,
        furthestIndex + 1,
      ),
      tolerance,
    );

  const right =
    simplifyRouteSection(
      points.slice(
        furthestIndex,
      ),
      tolerance,
    );

  return [
    ...left.slice(0, -1),
    ...right,
  ];
}

function removeLeastImportantPoint(
  points: MovementPathPoint[],
): MovementPathPoint[] {
  let removeIndex = -1;
  let smallestDeviation =
    Number.POSITIVE_INFINITY;

  for (
    let index = 1;
    index <
    points.length - 1;
    index += 1
  ) {
    if (
      isProtectedRouteAnchor(
        points[index],
        index,
        points,
      )
    ) {
      continue;
    }

    const deviation =
      distanceFromPointToSegment(
        points[index].position,
        points[index - 1].position,
        points[index + 1].position,
      );

    if (
      deviation <
      smallestDeviation
    ) {
      smallestDeviation =
        deviation;

      removeIndex = index;
    }
  }

  if (removeIndex < 0) {
    return points;
  }

  return points.filter(
    (_, index) =>
      index !== removeIndex,
  );
}

function angleDifferenceDegrees(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
  third: ReconstructionPosition,
): number {
  const incoming = {
    x: second.x - first.x,
    y: second.y - first.y,
  };

  const outgoing = {
    x: third.x - second.x,
    y: third.y - second.y,
  };

  const incomingLength =
    Math.hypot(
      incoming.x,
      incoming.y,
    );

  const outgoingLength =
    Math.hypot(
      outgoing.x,
      outgoing.y,
    );

  if (
    incomingLength < 0.000001 ||
    outgoingLength < 0.000001
  ) {
    return 0;
  }

  const dot = clamp(
    (
      incoming.x * outgoing.x +
      incoming.y * outgoing.y
    ) /
      (
        incomingLength *
        outgoingLength
      ),
    -1,
    1,
  );

  return (
    Math.acos(dot) *
    180
  ) / Math.PI;
}

function markAutomaticRoadTurns(
  points: MovementPathPoint[],
): MovementPathPoint[] {
  return points.map(
    (point, index) => {
      if (
        index === 0 ||
        index === points.length - 1 ||
        point.notes?.includes(
          AUTO_ROAD_CURVE_NOTE_MARKER,
        ) !== true
      ) {
        return point;
      }

      const previous =
        points[index - 1];

      const next =
        points[index + 1];

      const turnDegrees =
        angleDifferenceDegrees(
          previous.position,
          point.position,
          next.position,
        );

      if (turnDegrees < 7) {
        return {
          ...point,
          action: "Cruise",
        };
      }

      const incoming = {
        x:
          point.position.x -
          previous.position.x,
        y:
          point.position.y -
          previous.position.y,
      };

      const outgoing = {
        x:
          next.position.x -
          point.position.x,
        y:
          next.position.y -
          point.position.y,
      };

      const cross =
        incoming.x * outgoing.y -
        incoming.y * outgoing.x;

      return {
        ...point,
        action:
          cross >= 0
            ? "Turn Right"
            : "Turn Left",
      };
    },
  );
}

function getRouteSimplificationTolerance(
  participantType:
    ReconstructionVehicleType,
  roadGraphControlled: boolean,
): number {
  if (roadGraphControlled) {
    switch (participantType) {
      case "Bus":
      case "Truck":
        return 0.58;

      case "Motorcycle":
      case "Bicycle":
        return 0.34;

      case "Car":
      default:
        return 0.46;
    }
  }

  switch (participantType) {
    case "Bus":
    case "Truck":
      return 1.05;

    case "Motorcycle":
    case "Bicycle":
      return 0.62;

    case "Car":
      return 0.82;

    default:
      return 0.42;
  }
}

function stabiliseAuthoredVehicleRoute(
  authored: MovementPathPoint[],
  participantType:
    ReconstructionVehicleType,
): MovementPathPoint[] {
  if (
    HUMAN_TYPES.has(
      participantType,
    ) ||
    authored.length <= 7
  ) {
    return authored;
  }

  const hasRoadGraphPoints =
    authored
      .slice(1, -1)
      .some(
        (point) =>
          point.notes?.includes(
            AUTO_ROAD_CURVE_NOTE_MARKER,
          ) === true,
      );

  const hasFreehandSamples =
    authored.some(
      (point) =>
        point.notes?.includes(
          FREEHAND_ROUTE_NOTE_MARKER,
        ) === true,
    );

  const looksLikeLegacyFreehandRoute =
    authored.length > 9 &&
    authored
      .slice(1, -1)
      .filter(
        (point, index) =>
          !isProtectedRouteAnchor(
            point,
            index + 1,
            authored,
          ),
      )
      .every(
        (point) =>
          point.action === "Cruise" &&
          !point.linkedSceneObjectId,
      );

  if (
    !hasRoadGraphPoints &&
    !hasFreehandSamples &&
    !looksLikeLegacyFreehandRoute
  ) {
    return authored;
  }

  const tolerance =
    getRouteSimplificationTolerance(
      participantType,
      hasRoadGraphPoints,
    );

  const protectedIndices =
    authored
      .map(
        (point, index) => ({
          point,
          index,
        }),
      )
      .filter(
        ({ point, index }) =>
          isProtectedRouteAnchor(
            point,
            index,
            authored,
          ),
      )
      .map(
        ({ index }) => index,
      );

  const uniqueProtectedIndices = [
    ...new Set(
      protectedIndices,
    ),
  ].sort(
    (left, right) =>
      left - right,
  );

  const simplified:
    MovementPathPoint[] = [];

  for (
    let segmentIndex = 0;
    segmentIndex <
    uniqueProtectedIndices.length - 1;
    segmentIndex += 1
  ) {
    const startIndex =
      uniqueProtectedIndices[
        segmentIndex
      ];

    const endIndex =
      uniqueProtectedIndices[
        segmentIndex + 1
      ];

    const section =
      simplifyRouteSection(
        authored.slice(
          startIndex,
          endIndex + 1,
        ),
        tolerance,
      );

    simplified.push(
      ...(
        segmentIndex === 0
          ? section
          : section.slice(1)
      ),
    );
  }

  /*
   * Eight authored anchors are enough for a compound junction turn while
   * still remaining fully editable. Extra low-value samples recreate the
   * sharp polygon visible in the previous implementation.
   */
  let limited =
    simplified.length >= 2
      ? simplified
      : authored;

  const maximumPoints =
    hasRoadGraphPoints
      ? 8
      : 7;

  while (
    limited.length >
    maximumPoints
  ) {
    const next =
      removeLeastImportantPoint(
        limited,
      );

    if (
      next.length ===
      limited.length
    ) {
      break;
    }

    limited = next;
  }

  return hasRoadGraphPoints
    ? markAutomaticRoadTurns(
        limited,
      )
    : limited;
}

function generateRoadCurveIfNeeded(
  input: {
    authored: MovementPathPoint[];
    participantType:
      ReconstructionVehicleType;
    durationSeconds: number;
    createId:
      (prefix: string) => string;
  },
): MovementPathPoint[] {
  const {
    authored,
    participantType,
    durationSeconds,
    createId,
  } = input;

  if (authored.length < 2) {
    return authored;
  }

  /*
   * [RoadSafe:ManualBezierRouteOwnershipV1]
   *
   * Once an investigator explicitly shapes any segment, automatic road-curve
   * generation must not replace those anchors/handles.
   */
  const hasManualBezier =
    authored.some(
      (point) =>
        point.pathInterpolation ===
          "Bezier" ||
        Boolean(
          point.bezierIn,
        ) ||
        Boolean(
          point.bezierOut,
        ),
    );

  if (
    hasManualBezier
  ) {
    learnFromInvestigatorRoadRoute(
      authored,
      participantType,
    );

    return authored;
  }

  const pointOne = authored[0];

  const pointZ =
    authored[
      authored.length - 1
    ];

  const intermediates =
    authored.slice(1, -1);

  const mayRegenerate =
    intermediates.length === 0 ||
    intermediates.every(
      isAutoRoadCurvePoint,
    );

  if (!mayRegenerate) {
    learnFromInvestigatorRoadRoute(
      authored,
      participantType,
    );

    return authored;
  }

  const generated =
    createRoadAlignedParticipantRoute({
      startPoint: pointOne,
      impactPoint: pointZ,
      participantType,
      durationSeconds,
      createId,
    });

  return generated
    ? [
        generated.startPoint,
        ...generated.intermediatePoints,
        pointZ,
      ]
    : authored;
}


/*
 * [RoadSafe:CollisionTerminatedRouteV1]
 *
 * Point Z is the authoritative end of every investigator-authored approach.
 * Auto-generated road points may never continue through the collision and
 * return from the opposite side.
 */
/*
 * [RoadSafe:MetricCollisionTerminatedRouteV2]
 *
 * Point Z is the authoritative end of an approach. Automatic-road anchors are
 * filtered through the active scene's metre-based topology engine before
 * Point Z is appended.
 */
function enforceCollisionTerminatedRoute(
  route:
    MovementPathPoint[],
  collisionPosition:
    ReconstructionPosition,
  participantType:
    ReconstructionVehicleType,
): MovementPathPoint[] {
  if (
    route.length < 2
  ) {
    return route;
  }

  let pointZIndex =
    route.findIndex(
      isPointZ,
    );

  if (
    pointZIndex < 0
  ) {
    pointZIndex =
      route.findIndex(
        (point) =>
          point.action ===
          "Impact",
      );
  }

  if (
    pointZIndex < 1
  ) {
    pointZIndex =
      route.length -
      1;
  }

  const pointZSource =
    route[
      pointZIndex
    ];

  let approach =
    route
      .slice(
        0,
        pointZIndex,
      )
      .filter(
        (point) =>
          !isPointZ(
            point,
          ) &&
          point.action !==
            "Impact",
      );

  if (
    approach.length === 0
  ) {
    approach = [
      route[0],
    ];
  }

  const automaticRoadRoute =
    approach.some(
      (point) =>
        point.notes
          ?.includes(
            AUTO_ROAD_CURVE_NOTE_MARKER,
          ) === true,
    );

  if (
    automaticRoadRoute
  ) {
    approach =
      stabiliseAutomaticRoadMovementRoute(
        approach,
        collisionPosition,
        participantType,
      );
  }

  const pointZ:
    MovementPathPoint = {
    ...pointZSource,

    position: {
      ...collisionPosition,
    },

    action:
      "Impact",

    notes:
      normaliseNotes(
        pointZSource
          .notes,
        POINT_Z_NOTE_MARKER,
      ),
  };

  let terminatedRoute = [
    ...approach,
    pointZ,
  ];

  if (
    automaticRoadRoute &&
    terminatedRoute.length >
      3
  ) {
    terminatedRoute =
      simplifyRouteSection(
        terminatedRoute,
        getRouteSimplificationTolerance(
          participantType,
          true,
        ),
      );

    terminatedRoute =
      markAutomaticRoadTurns(
        terminatedRoute,
      );
  }

  return terminatedRoute;
}


export function createLockedParticipantRoute({
  startPosition,
  collisionPosition,
  durationSeconds,
  speedKmh,
  participantType,
  worldDimensions,
  createId,
  impactTimeSeconds,
}: CreateLockedParticipantRouteOptions): MovementPathPoint[] {
  const safeStart =
    ensureDifferentStartAndImpact(
      startPosition,
      collisionPosition,
    );

  const heading =
    headingDegrees(
      safeStart,
      collisionPosition,
      0,
    );

  const pointOne:
    MovementPathPoint = {
      id: createId("path-start"),
      label: "Point 1 · Start",
      position: safeStart,
      timeSeconds: 0,
      speedKmh: Math.max(
        0,
        speedKmh,
      ),
      rotation: heading,
      action:
        getStartAction(
          participantType,
        ),
      notes:
        POINT_ONE_NOTE_MARKER,
    };

  const pointZ:
    MovementPathPoint = {
      id: createId(
        POINT_Z_ID_PREFIX.slice(
          0,
          -1,
        ),
      ),
      label:
        "Point Z · Primary collision",
      position: {
        ...collisionPosition,
      },
      timeSeconds: clamp(
        impactTimeSeconds ??
          durationSeconds * 0.55,
        0.1,
        Math.max(
          0.1,
          durationSeconds - 0.05,
        ),
      ),
      speedKmh: Math.max(
        0,
        speedKmh * 0.92,
      ),
      rotation: heading,
      action: "Impact",
      notes:
        POINT_Z_NOTE_MARKER,
    };

  const roadAligned =
    generateRoadCurveIfNeeded({
      authored: [
        pointOne,
        pointZ,
      ],
      participantType,
      durationSeconds,
      createId,
    });

  const stabilised =
    stabiliseAuthoredVehicleRoute(
      roadAligned,
      participantType,
    );

  const collisionTerminated =
    enforceCollisionTerminatedRoute(
      stabilised,
      collisionPosition,
      participantType,
    );

  return alignAuthoredOnlyToTangents(
    redistributeAuthoredTimes(
      relabelPointZRoute(
        collisionTerminated,
      ),
      durationSeconds,
      speedKmh,
      worldDimensions,
    ),
  );
}

export function normalisePointZRoute({
  pathPoints,
  collisionPosition,
  durationSeconds,
  speedKmh,
  participantType,
  worldDimensions,
  createId = defaultCreateId,
}: NormalisePointZRouteOptions): MovementPathPoint[] {
  const physicsPoints = pathPoints
    .filter(
      isPhysicsGeneratedRoutePoint,
    )
    .slice()
    .sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    );

  const originalAuthored =
    pathPoints
      .filter(
        (point) =>
          !isPhysicsGeneratedRoutePoint(
            point,
          ),
      )
      .slice()
      .sort(
        (a, b) =>
          a.timeSeconds -
          b.timeSeconds,
      );

  if (
    originalAuthored.length < 2
  ) {
    const fallbackStart =
      originalAuthored[0]
        ?.position ?? {
        x: clamp(
          (
            collisionPosition
              ?.x ?? 50
          ) - 25,
          0,
          100,
        ),
        y:
          collisionPosition
            ?.y ?? 50,
      };

    return [
      ...createLockedParticipantRoute({
        startPosition:
          fallbackStart,
        collisionPosition:
          collisionPosition ??
          originalAuthored[0]
            ?.position ?? {
            x: 50,
            y: 50,
          },
        durationSeconds,
        speedKmh:
          originalAuthored[0]
            ?.speedKmh ??
          speedKmh,
        participantType,
        worldDimensions,
        createId,
      }),
      ...physicsPoints,
    ].sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    );
  }

  const impactIndex =
    findLegacyImpactIndex(
      originalAuthored,
    );

  const startSource =
    originalAuthored[0];

  const pointZSource =
    originalAuthored[
      clamp(
        impactIndex,
        1,
        originalAuthored.length - 1,
      )
    ];

  const intermediateSources =
    originalAuthored
      .slice(
        1,
        Math.max(
          1,
          impactIndex,
        ),
      )
      .filter(
        (point) =>
          point.id !==
            pointZSource.id &&
          !isPointZ(point),
      );

  const pointOne:
    MovementPathPoint = {
      ...startSource,
      action:
        getStartAction(
          participantType,
        ),
      notes: normaliseNotes(
        startSource.notes,
        POINT_ONE_NOTE_MARKER,
      ),
    };

  const intermediates =
    intermediateSources.map(
      (point) => ({
        ...point,
        action:
          sanitiseIntermediateAction(
            point.action,
          ),
        notes: (
          point.notes ?? ""
        )
          .replace(
            POINT_Z_NOTE_MARKER,
            "",
          )
          .replace(
            POINT_ONE_NOTE_MARKER,
            "",
          )
          .trim(),
      }),
    );

  const pointZPosition =
    collisionPosition ??
    pointZSource.position;

  const pointZHandleDelta = {
    x:
      pointZPosition.x -
      pointZSource
        .position.x,

    y:
      pointZPosition.y -
      pointZSource
        .position.y,
  };

  const pointZ:
    MovementPathPoint = {
      ...pointZSource,
      id:
        pointZSource.id.startsWith(
          POINT_Z_ID_PREFIX,
        )
          ? pointZSource.id
          : createId(
              POINT_Z_ID_PREFIX.slice(
                0,
                -1,
              ),
            ),
      position: {
        ...pointZPosition,
      },

      bezierIn:
        pointZSource
          .bezierIn
          ? {
              x:
                clamp(
                  pointZSource
                    .bezierIn
                    .x +
                  pointZHandleDelta.x,
                  0,
                  100,
                ),

              y:
                clamp(
                  pointZSource
                    .bezierIn
                    .y +
                  pointZHandleDelta.y,
                  0,
                  100,
                ),
            }
          : undefined,

      action: "Impact",
      notes: normaliseNotes(
        pointZSource.notes,
        POINT_Z_NOTE_MARKER,
      ),
    };

  const stabilised =
    stabiliseAuthoredVehicleRoute(
      [
        pointOne,
        ...intermediates,
        pointZ,
      ],
      participantType,
    );

  const roadAligned =
    generateRoadCurveIfNeeded({
      authored: stabilised,
      participantType,
      durationSeconds,
      createId,
    });

  const finalRoute =
    stabiliseAuthoredVehicleRoute(
      roadAligned,
      participantType,
    );

  const collisionTerminatedRoute =
    enforceCollisionTerminatedRoute(
      finalRoute,
      pointZPosition,
      participantType,
    );

  const authored =
    alignAuthoredOnlyToTangents(
      redistributeAuthoredTimes(
        relabelPointZRoute(
          collisionTerminatedRoute,
        ),
        durationSeconds,
        speedKmh,
        worldDimensions,
      ),
    );

  return [
    ...authored,
    ...physicsPoints,
  ].sort(
    (a, b) =>
      a.timeSeconds -
      b.timeSeconds,
  );
}

export function alignAuthoredRouteToTangents(
  pathPoints: MovementPathPoint[],
): MovementPathPoint[] {
  const physics = pathPoints
    .filter(
      isPhysicsGeneratedRoutePoint,
    )
    .slice();

  const authored = pathPoints
    .filter(
      (point) =>
        !isPhysicsGeneratedRoutePoint(
          point,
        ),
    )
    .slice()
    .sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    );

  if (authored.length === 0) {
    return physics.sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    );
  }

  const impactIndex =
    findLegacyImpactIndex(
      authored,
    );

  const protectedPoints =
    authored
      .slice(
        0,
        Math.max(
          2,
          impactIndex + 1,
        ),
      )
      .map(
        (
          point,
          index,
          list,
        ) => {
          if (index === 0) {
            return {
              ...point,
              action:
                point.action ===
                "Enter Scene"
                  ? (
                      "Enter Scene" as const
                    )
                  : (
                      "Start" as const
                    ),
            };
          }

          if (
            index ===
            list.length - 1
          ) {
            return {
              ...point,
              action:
                "Impact" as const,
            };
          }

          return {
            ...point,
            action:
              sanitiseIntermediateAction(
                point.action,
              ),
          };
        },
      );

  return [
    ...alignAuthoredOnlyToTangents(
      relabelPointZRoute(
        protectedPoints,
      ),
    ),
    ...physics,
  ].sort(
    (a, b) =>
      a.timeSeconds -
      b.timeSeconds,
  );
}

export function createProgressiveParticipantRoute({
  startPosition,
  impactPosition,
  durationSeconds,
  speedKmh,
  participantType,
  worldDimensions,
  createId,
}: {
  startPosition: ReconstructionPosition;
  impactPosition: ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType: ReconstructionVehicleType;
  worldDimensions?: MetricSceneDimensions;
  createId: (prefix: string) => string;
  pointCount?: number;
}): MovementPathPoint[] {
  return createLockedParticipantRoute({
    startPosition,
    collisionPosition:
      impactPosition,
    durationSeconds,
    speedKmh,
    participantType,
    worldDimensions,
    createId,
  });
}

export function insertProgressiveRoutePoint({
  pathPoints,
  selectedPointId,
  durationSeconds,
  worldDimensions,
  createId,
}: InsertProgressiveRoutePointOptions): {
  pathPoints: MovementPathPoint[];
  insertedPointId: string;
} {
  const physics = pathPoints
    .filter(
      isPhysicsGeneratedRoutePoint,
    )
    .slice();

  const authored =
    alignAuthoredRouteToTangents(
      pathPoints,
    ).filter(
      (point) =>
        !isPhysicsGeneratedRoutePoint(
          point,
        ),
    );

  if (authored.length < 2) {
    throw new Error(
      "Point 1 and Point Z are required before adding an intermediate point.",
    );
  }

  let segmentIndex =
    selectedPointId
      ? authored.findIndex(
          (point) =>
            point.id ===
            selectedPointId,
        )
      : -1;

  if (
    segmentIndex ===
    authored.length - 1
  ) {
    segmentIndex =
      authored.length - 2;
  }

  if (
    segmentIndex < 0 ||
    segmentIndex >=
      authored.length - 1
  ) {
    let largestDistance = -1;
    segmentIndex = 0;

    for (
      let index = 0;
      index <
      authored.length - 1;
      index += 1
    ) {
      const currentDistance =
        distance(
          authored[index]
            .position,
          authored[index + 1]
            .position,
        );

      if (
        currentDistance >
        largestDistance
      ) {
        largestDistance =
          currentDistance;

        segmentIndex = index;
      }
    }
  }

  const start =
    authored[segmentIndex];

  const end =
    authored[
      segmentIndex + 1
    ];

  const previous =
    authored[
      Math.max(
        0,
        segmentIndex - 1,
      )
    ] ?? start;

  const following =
    authored[
      Math.min(
        authored.length - 1,
        segmentIndex + 2,
      )
    ] ?? end;

  const insertedPointId =
    createId("path-point");

  const inserted:
    MovementPathPoint = {
      id: insertedPointId,
      label: "New route point",
      position:
        catmullRomMidpoint(
          previous.position,
          start.position,
          end.position,
          following.position,
        ),
      timeSeconds: clamp(
        (
          start.timeSeconds +
          end.timeSeconds
        ) / 2,
        0.01,
        Math.max(
          0.01,
          durationSeconds - 0.01,
        ),
      ),
      speedKmh:
        (
          start.speedKmh +
          end.speedKmh
        ) / 2,
      rotation:
        headingDegrees(
          start.position,
          end.position,
          start.rotation,
        ),
      action: "Cruise",
      notes: "",
    };

  const nextAuthored = [
    ...authored.slice(
      0,
      segmentIndex + 1,
    ),
    inserted,
    ...authored.slice(
      segmentIndex + 1,
    ),
  ];

  const aligned =
    alignAuthoredOnlyToTangents(
      redistributeAuthoredTimes(
        relabelPointZRoute(
          nextAuthored,
        ),
        durationSeconds,
        authored[0]
          ?.speedKmh ??
          1,
        worldDimensions,
      ),
    );

  return {
    insertedPointId,
    pathPoints: [
      ...aligned,
      ...physics,
    ].sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    ),
  };
}

export function removeIntermediateRoutePoint({
  pathPoints,
  pointId,
}: {
  pathPoints: MovementPathPoint[];
  pointId: string;
}): MovementPathPoint[] {
  const authored = pathPoints
    .filter(
      (point) =>
        !isPhysicsGeneratedRoutePoint(
          point,
        ),
    )
    .sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    );

  const target =
    authored.find(
      (point) =>
        point.id === pointId,
    );

  if (
    !target ||
    !canDeleteAuthoredRoutePoint(
      target,
      authored,
    )
  ) {
    return pathPoints;
  }

  return alignAuthoredRouteToTangents(
    pathPoints.filter(
      (point) =>
        point.id !== pointId,
    ),
  );
}

export function applySafeAuthoredPointUpdate({
  pathPoints,
  pointId,
  updates,
  collisionPosition,
  durationSeconds,
  speedKmh,
  participantType,
  worldDimensions,
  createId = defaultCreateId,
}: {
  pathPoints: MovementPathPoint[];
  pointId: string;
  updates: Partial<MovementPathPoint>;
  collisionPosition:
    ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType:
    ReconstructionVehicleType;
  worldDimensions?:
    MetricSceneDimensions;
  createId?:
    (prefix: string) => string;
}): MovementPathPoint[] {
  /*
   * Work from the current authored IDs so an editable auto-curve point is not
   * regenerated before the requested drag/update is applied.
   */
  const materialised =
    pathPoints;

  const authored = materialised
    .filter(
      (point) =>
        !isPhysicsGeneratedRoutePoint(
          point,
        ),
    )
    .sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    );

  const target =
    authored.find(
      (point) =>
        point.id === pointId,
    );

  if (!target) {
    return materialised;
  }

  const role =
    getAuthoredRoutePointRole(
      target,
      authored,
    );

  const safeUpdates:
    Partial<MovementPathPoint> = {
      ...updates,
    };

  delete safeUpdates.id;

  if (role === "PointZ") {
    delete safeUpdates.position;
    delete safeUpdates.label;
    delete safeUpdates.action;

    safeUpdates.notes =
      updates.notes
        ? normaliseNotes(
            updates.notes,
            POINT_Z_NOTE_MARKER,
          )
        : target.notes;
  } else if (
    role === "PointOne"
  ) {
    delete safeUpdates.label;

    if (
      updates.action !== undefined &&
      updates.action !== "Start" &&
      updates.action !==
        "Enter Scene"
    ) {
      delete safeUpdates.action;
    }
  } else if (
    updates.action === "Impact"
  ) {
    safeUpdates.action =
      "Cruise";
  }

  if (
    role === "Intermediate" &&
    (
      updates.position !==
        undefined ||
      updates.rotation !==
        undefined
    )
  ) {
    const cleanedNotes = (
      updates.notes ??
      target.notes ??
      ""
    )
      .replace(
        AUTO_ROAD_CURVE_NOTE_MARKER,
        "",
      )
      .replace(
        FREEHAND_ROUTE_NOTE_MARKER,
        "",
      )
      .trim();

    safeUpdates.notes =
      addNoteMarker(
        cleanedNotes,
        MANUAL_ROUTE_ANCHOR_NOTE_MARKER,
      );
  }

  const updated =
    materialised.map(
      (point) =>
        point.id === pointId
          ? {
              ...point,
              ...safeUpdates,
            }
          : point,
    );

  return normalisePointZRoute({
    pathPoints: updated,
    collisionPosition,
    durationSeconds,
    speedKmh,
    participantType,
    worldDimensions,
    createId,
  });
}

export function updatePointZPosition({
  pathPoints,
  collisionPosition,
  durationSeconds,
  speedKmh,
  participantType,
  worldDimensions,
  createId = defaultCreateId,
}: Omit<
  NormalisePointZRouteOptions,
  "collisionPosition"
> & {
  collisionPosition:
    ReconstructionPosition;
}): MovementPathPoint[] {
  return normalisePointZRoute({
    pathPoints,
    collisionPosition,
    durationSeconds,
    speedKmh,
    participantType,
    worldDimensions,
    createId,
  });
}

export function setParticipantImpactPoint({
  pathPoints,
  durationSeconds,
  worldDimensions,
}: {
  pathPoints: MovementPathPoint[];
  pointId: string;
  durationSeconds: number;
  worldDimensions?:
    MetricSceneDimensions;
}): MovementPathPoint[] {
  const authored = pathPoints
    .filter(
      (point) =>
        !isPhysicsGeneratedRoutePoint(
          point,
        ),
    )
    .sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    );

  if (authored.length < 2) {
    return pathPoints;
  }

  const pointZ =
    authored.find(isPointZ) ??
    authored.find(
      (point) =>
        point.action === "Impact",
    ) ??
    authored[
      authored.length - 1
    ];

  const protectedAuthored =
    authored
      .filter(
        (point) =>
          point.timeSeconds <=
            pointZ.timeSeconds ||
          point.id === pointZ.id,
      )
      .map(
        (
          point,
          index,
        ) => {
          if (
            point.id === pointZ.id
          ) {
            return {
              ...point,
              action:
                "Impact" as const,
              label:
                "Point Z · Primary collision",
              notes:
                normaliseNotes(
                  point.notes,
                  POINT_Z_NOTE_MARKER,
                ),
            };
          }

          if (index === 0) {
            return {
              ...point,
              action:
                point.action ===
                "Enter Scene"
                  ? (
                      "Enter Scene" as const
                    )
                  : (
                      "Start" as const
                    ),
            };
          }

          return {
            ...point,
            action:
              sanitiseIntermediateAction(
                point.action,
              ),
          };
        },
      );

  const physics =
    pathPoints.filter(
      isPhysicsGeneratedRoutePoint,
    );

  return [
    ...alignAuthoredOnlyToTangents(
      redistributeAuthoredTimes(
        relabelPointZRoute(
          protectedAuthored,
        ),
        durationSeconds,
        protectedAuthored[0]
          ?.speedKmh ??
          1,
        worldDimensions,
      ),
    ),
    ...physics,
  ].sort(
    (a, b) =>
      a.timeSeconds -
      b.timeSeconds,
  );
}

export function getAuthoredImpactPoint(
  pathPoints: MovementPathPoint[],
): MovementPathPoint | null {
  const authored = pathPoints
    .filter(
      (point) =>
        !isPhysicsGeneratedRoutePoint(
          point,
        ),
    )
    .sort(
      (a, b) =>
        a.timeSeconds -
        b.timeSeconds,
    );

  return (
    authored.find(isPointZ) ??
    authored.find(
      (point) =>
        point.action === "Impact",
    ) ??
    authored[
      authored.length - 1
    ] ??
    null
  );
}

export function geoCoordinateToScenePosition(
  calibration:
    FieldSceneCalibration,
  coordinate: GeoCoordinate,
): ReconstructionPosition {
  const originLatitudeRadians =
    (
      calibration.origin.latitude *
      Math.PI
    ) / 180;

  const coordinateLatitudeRadians =
    (
      coordinate.latitude *
      Math.PI
    ) / 180;

  const deltaLatitudeRadians =
    (
      (
        coordinate.latitude -
        calibration.origin.latitude
      ) *
      Math.PI
    ) / 180;

  const deltaLongitudeRadians =
    (
      (
        coordinate.longitude -
        calibration.origin.longitude
      ) *
      Math.PI
    ) / 180;

  const averageLatitude =
    (
      originLatitudeRadians +
      coordinateLatitudeRadians
    ) / 2;

  const eastMetres =
    deltaLongitudeRadians *
    EARTH_RADIUS_METRES *
    Math.cos(averageLatitude);

  const northMetres =
    deltaLatitudeRadians *
    EARTH_RADIUS_METRES;

  const rotationRadians =
    (
      calibration.rotationDegrees *
      Math.PI
    ) / 180;

  const xAxis = {
    east:
      Math.sin(
        rotationRadians,
      ),
    north:
      Math.cos(
        rotationRadians,
      ),
  };

  const rightAxis = {
    east:
      Math.cos(
        rotationRadians,
      ),
    north:
      -Math.sin(
        rotationRadians,
      ),
  };

  const ySign =
    calibration.yAxisSide ===
    "Left"
      ? -1
      : 1;

  const xMetres =
    eastMetres * xAxis.east +
    northMetres * xAxis.north;

  const yMetres =
    (
      eastMetres *
        rightAxis.east +
      northMetres *
        rightAxis.north
    ) *
    ySign;

  return {
    x: clamp(
      (
        xMetres /
        Math.max(
          0.01,
          calibration
            .sceneWidthMetres,
        )
      ) *
        100,
      0,
      100,
    ),
    y: clamp(
      (
        yMetres /
        Math.max(
          0.01,
          calibration
            .sceneHeightMetres,
        )
      ) *
        100,
      0,
      100,
    ),
  };
}
