import type {
  MovementAction,
  MovementPathPoint,
  ReconstructionPosition,
  ReconstructionVehicleType,
} from "../types/reconstruction";

import type {
  FieldSceneCalibration,
  GeoCoordinate,
} from "../types/fieldPlacement";

const EARTH_RADIUS_METRES = 6_371_008.8;

export const POINT_Z_ID_PREFIX = "path-impact-z-";
export const POINT_Z_NOTE_MARKER = "[RoadSafe:PointZ]";
export const POINT_ONE_NOTE_MARKER = "[RoadSafe:Point1]";

const PHYSICS_POINT_PREFIXES = [
  "physics-point-",
  "detected-impact-",
  "physics-transition-",
  "legacy-impact-",
] as const;

const PHYSICS_NOTE_MARKERS = [
  "Generated by the RoadSafe deterministic 2D physics preview.",
  "Generated at the first swept body contact found along the participant routes.",
  "Physics takes over from the participant's guided route",
  "Physics-generated event.",
] as const;

const POST_IMPACT_ONLY_ACTIONS = new Set<MovementAction>([
  "Ricochet",
  "Deflect",
  "Slide",
  "Fall",
]);

const HUMAN_TYPES = new Set<ReconstructionVehicleType>([
  "Pedestrian",
  "Officer",
  "Witness",
]);

export type AuthoredRoutePointRole =
  | "PointOne"
  | "Intermediate"
  | "PointZ"
  | "Physics";

export interface NormalisePointZRouteOptions {
  pathPoints: MovementPathPoint[];
  collisionPosition?: ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType: ReconstructionVehicleType;
  createId?: (prefix: string) => string;
}

export interface CreateLockedParticipantRouteOptions {
  startPosition: ReconstructionPosition;
  collisionPosition: ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType: ReconstructionVehicleType;
  createId: (prefix: string) => string;
  impactTimeSeconds?: number;
}

export interface InsertProgressiveRoutePointOptions {
  pathPoints: MovementPathPoint[];
  selectedPointId: string | null;
  durationSeconds: number;
  createId: (prefix: string) => string;
}

function defaultCreateId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function clamp(
  value: number,
  minimum: number,
  maximum: number,
): number {
  return Math.min(maximum, Math.max(minimum, value));
}

function samePosition(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
): boolean {
  return (
    Math.abs(first.x - second.x) <= 0.000001 &&
    Math.abs(first.y - second.y) <= 0.000001
  );
}

function distance(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
): number {
  return Math.hypot(
    second.x - first.x,
    second.y - first.y,
  );
}

function headingDegrees(
  from: ReconstructionPosition,
  to: ReconstructionPosition,
  fallback = 0,
): number {
  const x = to.x - from.x;
  const y = to.y - from.y;

  if (Math.hypot(x, y) < 0.000001) {
    return fallback;
  }

  return (
    ((Math.atan2(y, x) * 180) / Math.PI + 360) %
    360
  );
}

function normaliseNotes(
  notes: string | undefined,
  marker: string,
): string {
  const cleaned = (notes ?? "")
    .replace(POINT_Z_NOTE_MARKER, "")
    .replace(POINT_ONE_NOTE_MARKER, "")
    .trim();

  return cleaned ? `${marker}\n${cleaned}` : marker;
}

export function isPhysicsGeneratedRoutePoint(
  point: MovementPathPoint,
): boolean {
  return (
    PHYSICS_POINT_PREFIXES.some((prefix) =>
      point.id.startsWith(prefix),
    ) ||
    PHYSICS_NOTE_MARKERS.some((marker) =>
      point.notes?.includes(marker),
    )
  );
}

export function isPointZ(
  point: MovementPathPoint,
): boolean {
  return (
    point.id.startsWith(POINT_Z_ID_PREFIX) ||
    point.notes?.includes(POINT_Z_NOTE_MARKER) === true ||
    /^point\s*z\b/i.test(point.label.trim())
  );
}

export function isPointOne(
  point: MovementPathPoint,
): boolean {
  return (
    point.notes?.includes(POINT_ONE_NOTE_MARKER) === true ||
    /^point\s*1\b/i.test(point.label.trim())
  );
}

export function getAuthoredRoutePointRole(
  point: MovementPathPoint,
  authoredPoints?: MovementPathPoint[],
): AuthoredRoutePointRole {
  if (isPhysicsGeneratedRoutePoint(point)) {
    return "Physics";
  }

  if (isPointZ(point)) {
    return "PointZ";
  }

  if (
    isPointOne(point) ||
    authoredPoints?.[0]?.id === point.id
  ) {
    return "PointOne";
  }

  return "Intermediate";
}

export function canDeleteAuthoredRoutePoint(
  point: MovementPathPoint,
  authoredPoints?: MovementPathPoint[],
): boolean {
  return (
    getAuthoredRoutePointRole(point, authoredPoints) ===
    "Intermediate"
  );
}

export function canMoveAuthoredRoutePoint(
  point: MovementPathPoint,
): boolean {
  return !isPointZ(point) && !isPhysicsGeneratedRoutePoint(point);
}

function catmullRomMidpoint(
  previous: ReconstructionPosition,
  start: ReconstructionPosition,
  end: ReconstructionPosition,
  following: ReconstructionPosition,
): ReconstructionPosition {
  const t = 0.5;
  const t2 = t * t;
  const t3 = t2 * t;

  return {
    x: clamp(
      0.5 *
        (2 * start.x +
          (-previous.x + end.x) * t +
          (2 * previous.x -
            5 * start.x +
            4 * end.x -
            following.x) *
            t2 +
          (-previous.x +
            3 * start.x -
            3 * end.x +
            following.x) *
            t3),
      0,
      100,
    ),
    y: clamp(
      0.5 *
        (2 * start.y +
          (-previous.y + end.y) * t +
          (2 * previous.y -
            5 * start.y +
            4 * end.y -
            following.y) *
            t2 +
          (-previous.y +
            3 * start.y -
            3 * end.y +
            following.y) *
            t3),
      0,
      100,
    ),
  };
}

function findLegacyImpactIndex(
  authored: MovementPathPoint[],
): number {
  const explicitPointZIndex = authored.findIndex(isPointZ);

  if (explicitPointZIndex >= 0) {
    return explicitPointZIndex;
  }

  const authoredImpactIndex = authored.findIndex(
    (point) => point.action === "Impact",
  );

  if (authoredImpactIndex >= 0) {
    return authoredImpactIndex;
  }

  return Math.max(1, authored.length - 1);
}

function getStartAction(
  participantType: ReconstructionVehicleType,
): MovementAction {
  return HUMAN_TYPES.has(participantType)
    ? "Enter Scene"
    : "Start";
}

function sanitiseIntermediateAction(
  action: MovementAction,
): MovementAction {
  if (
    action === "Impact" ||
    action === "Start" ||
    action === "Enter Scene" ||
    POST_IMPACT_ONLY_ACTIONS.has(action)
  ) {
    return "Cruise";
  }

  return action;
}

function relabelPointZRoute(
  authored: MovementPathPoint[],
): MovementPathPoint[] {
  if (authored.length === 0) {
    return authored;
  }

  return authored.map((point, index) => {
    const finalPoint = index === authored.length - 1;

    if (index === 0) {
      return {
        ...point,
        label: "Point 1 · Start",
        notes: normaliseNotes(
          point.notes,
          POINT_ONE_NOTE_MARKER,
        ),
      };
    }

    if (finalPoint) {
      return {
        ...point,
        label: "Point Z · Primary collision",
        notes: normaliseNotes(
          point.notes,
          POINT_Z_NOTE_MARKER,
        ),
      };
    }

    return {
      ...point,
      label: `Point ${index + 1}`,
      notes: (point.notes ?? "")
        .replace(POINT_Z_NOTE_MARKER, "")
        .replace(POINT_ONE_NOTE_MARKER, "")
        .trim(),
    };
  });
}

function alignAuthoredOnlyToTangents(
  authored: MovementPathPoint[],
): MovementPathPoint[] {
  return authored.map((point, index) => {
    const previous =
      authored[Math.max(0, index - 1)] ?? point;
    const next =
      authored[
        Math.min(authored.length - 1, index + 1)
      ] ?? point;

    let rotation = point.rotation;

    if (authored.length > 1) {
      if (index === 0) {
        rotation = headingDegrees(
          point.position,
          next.position,
          rotation,
        );
      } else if (index === authored.length - 1) {
        rotation = headingDegrees(
          previous.position,
          point.position,
          rotation,
        );
      } else {
        rotation = headingDegrees(
          previous.position,
          next.position,
          rotation,
        );
      }
    }

    return {
      ...point,
      rotation,
    };
  });
}

function redistributeAuthoredTimes(
  authored: MovementPathPoint[],
  durationSeconds: number,
): MovementPathPoint[] {
  if (authored.length <= 1) {
    return authored;
  }

  const finalIndex = authored.length - 1;
  const existingImpactTime =
    authored[finalIndex].timeSeconds;

  const impactTimeSeconds = clamp(
    Number.isFinite(existingImpactTime)
      ? existingImpactTime
      : durationSeconds * 0.55,
    0.1,
    Math.max(0.1, durationSeconds - 0.05),
  );

  const segmentLengths = authored
    .slice(0, -1)
    .map((point, index) =>
      distance(
        point.position,
        authored[index + 1].position,
      ),
    );

  const totalLength = segmentLengths.reduce(
    (sum, segmentLength) => sum + segmentLength,
    0,
  );

  let travelled = 0;

  return authored.map((point, index) => {
    if (index === 0) {
      return {
        ...point,
        timeSeconds: 0,
      };
    }

    if (index === finalIndex) {
      return {
        ...point,
        timeSeconds: impactTimeSeconds,
      };
    }

    travelled += segmentLengths[index - 1] ?? 0;

    const progress =
      totalLength > 0.000001
        ? travelled / totalLength
        : index / finalIndex;

    return {
      ...point,
      timeSeconds: Number(
        (impactTimeSeconds * progress).toFixed(3),
      ),
    };
  });
}

function ensureDifferentStartAndImpact(
  startPosition: ReconstructionPosition,
  impactPosition: ReconstructionPosition,
): ReconstructionPosition {
  if (!samePosition(startPosition, impactPosition)) {
    return startPosition;
  }

  return {
    x: clamp(startPosition.x - 12, 0, 100),
    y: startPosition.y,
  };
}

export function createLockedParticipantRoute({
  startPosition,
  collisionPosition,
  durationSeconds,
  speedKmh,
  participantType,
  createId,
  impactTimeSeconds,
}: CreateLockedParticipantRouteOptions): MovementPathPoint[] {
  const safeStart = ensureDifferentStartAndImpact(
    startPosition,
    collisionPosition,
  );

  const startAction = getStartAction(participantType);
  const heading = headingDegrees(
    safeStart,
    collisionPosition,
    0,
  );

  const pointOne: MovementPathPoint = {
    id: createId("path-start"),
    label: "Point 1 · Start",
    position: safeStart,
    timeSeconds: 0,
    speedKmh: Math.max(0, speedKmh),
    rotation: heading,
    action: startAction,
    notes: POINT_ONE_NOTE_MARKER,
  };

  const pointZ: MovementPathPoint = {
    id: createId(POINT_Z_ID_PREFIX.slice(0, -1)),
    label: "Point Z · Primary collision",
    position: { ...collisionPosition },
    timeSeconds: clamp(
      impactTimeSeconds ?? durationSeconds * 0.55,
      0.1,
      Math.max(0.1, durationSeconds - 0.05),
    ),
    speedKmh: Math.max(0, speedKmh * 0.92),
    rotation: heading,
    action: "Impact",
    notes: POINT_Z_NOTE_MARKER,
  };

  return [pointOne, pointZ];
}

export function normalisePointZRoute({
  pathPoints,
  collisionPosition,
  durationSeconds,
  speedKmh,
  participantType,
  createId = defaultCreateId,
}: NormalisePointZRouteOptions): MovementPathPoint[] {
  const physicsPoints = pathPoints
    .filter(isPhysicsGeneratedRoutePoint)
    .slice()
    .sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );

  const originalAuthored = pathPoints
    .filter(
      (point) => !isPhysicsGeneratedRoutePoint(point),
    )
    .slice()
    .sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );

  if (originalAuthored.length < 2) {
    const fallbackStart =
      originalAuthored[0]?.position ?? {
        x: clamp((collisionPosition?.x ?? 50) - 25, 0, 100),
        y: collisionPosition?.y ?? 50,
      };

    return [
      ...createLockedParticipantRoute({
        startPosition: fallbackStart,
        collisionPosition:
          collisionPosition ??
          originalAuthored[0]?.position ?? {
            x: 50,
            y: 50,
          },
        durationSeconds,
        speedKmh:
          originalAuthored[0]?.speedKmh ?? speedKmh,
        participantType,
        createId,
      }),
      ...physicsPoints,
    ].sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );
  }

  const impactIndex =
    findLegacyImpactIndex(originalAuthored);

  const startSource = originalAuthored[0];

  const pointZSource =
    originalAuthored[
      clamp(
        impactIndex,
        1,
        originalAuthored.length - 1,
      )
    ];

  const intermediateSources = originalAuthored
    .slice(1, Math.max(1, impactIndex))
    .filter(
      (point) =>
        point.id !== pointZSource.id &&
        !isPointZ(point),
    );

  const pointOne: MovementPathPoint = {
    ...startSource,
    action: getStartAction(participantType),
    notes: normaliseNotes(
      startSource.notes,
      POINT_ONE_NOTE_MARKER,
    ),
  };

  const intermediates: MovementPathPoint[] =
    intermediateSources.map((point) => ({
      ...point,
      action: sanitiseIntermediateAction(point.action),
      notes: (point.notes ?? "")
        .replace(POINT_Z_NOTE_MARKER, "")
        .replace(POINT_ONE_NOTE_MARKER, "")
        .trim(),
    }));

  const pointZPosition =
    collisionPosition ?? pointZSource.position;

  const pointZ: MovementPathPoint = {
    ...pointZSource,
    id: pointZSource.id.startsWith(
      POINT_Z_ID_PREFIX,
    )
      ? pointZSource.id
      : createId(POINT_Z_ID_PREFIX.slice(0, -1)),
    position: { ...pointZPosition },
    action: "Impact",
    notes: normaliseNotes(
      pointZSource.notes,
      POINT_Z_NOTE_MARKER,
    ),
  };

  const authored = alignAuthoredOnlyToTangents(
    redistributeAuthoredTimes(
      relabelPointZRoute([
        pointOne,
        ...intermediates,
        pointZ,
      ]),
      durationSeconds,
    ),
  );

  return [...authored, ...physicsPoints].sort(
    (first, second) =>
      first.timeSeconds - second.timeSeconds,
  );
}

export function alignAuthoredRouteToTangents(
  pathPoints: MovementPathPoint[],
): MovementPathPoint[] {
  const physics = pathPoints
    .filter(isPhysicsGeneratedRoutePoint)
    .slice();

  const authored = pathPoints
    .filter(
      (point) => !isPhysicsGeneratedRoutePoint(point),
    )
    .slice()
    .sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );

  if (authored.length === 0) {
    return physics.sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );
  }

  const impactIndex = findLegacyImpactIndex(authored);

  const beforeAndIncludingImpact = authored.slice(
    0,
    Math.max(2, impactIndex + 1),
  );

  const lastIndex =
    beforeAndIncludingImpact.length - 1;

  const protectedActions =
    beforeAndIncludingImpact.map((point, index) => {
      if (index === 0) {
        return {
          ...point,
          action:
            point.action === "Enter Scene"
              ? ("Enter Scene" as const)
              : ("Start" as const),
        };
      }

      if (index === lastIndex) {
        return {
          ...point,
          action: "Impact" as const,
        };
      }

      return {
        ...point,
        action: sanitiseIntermediateAction(
          point.action,
        ),
      };
    });

  return [
    ...alignAuthoredOnlyToTangents(
      relabelPointZRoute(protectedActions),
    ),
    ...physics,
  ].sort(
    (first, second) =>
      first.timeSeconds - second.timeSeconds,
  );
}

/**
 * Backward-compatible name retained for the current editor.
 * The new route deliberately creates only Point 1 and Point Z.
 */
export function createProgressiveParticipantRoute({
  startPosition,
  impactPosition,
  durationSeconds,
  speedKmh,
  participantType,
  createId,
}: {
  startPosition: ReconstructionPosition;
  impactPosition: ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType: ReconstructionVehicleType;
  createId: (prefix: string) => string;
  pointCount?: number;
}): MovementPathPoint[] {
  return createLockedParticipantRoute({
    startPosition,
    collisionPosition: impactPosition,
    durationSeconds,
    speedKmh,
    participantType,
    createId,
  });
}

export function insertProgressiveRoutePoint({
  pathPoints,
  selectedPointId,
  durationSeconds,
  createId,
}: InsertProgressiveRoutePointOptions): {
  pathPoints: MovementPathPoint[];
  insertedPointId: string;
} {
  const physics = pathPoints
    .filter(isPhysicsGeneratedRoutePoint)
    .slice();

  const authored = alignAuthoredRouteToTangents(
    pathPoints,
  ).filter(
    (point) => !isPhysicsGeneratedRoutePoint(point),
  );

  if (authored.length < 2) {
    throw new Error(
      "Point 1 and Point Z are required before adding an intermediate point.",
    );
  }

  let segmentIndex = selectedPointId
    ? authored.findIndex(
        (point) => point.id === selectedPointId,
      )
    : -1;

  if (segmentIndex === authored.length - 1) {
    segmentIndex = authored.length - 2;
  }

  if (
    segmentIndex < 0 ||
    segmentIndex >= authored.length - 1
  ) {
    let largestDistance = -1;
    segmentIndex = 0;

    for (
      let index = 0;
      index < authored.length - 1;
      index += 1
    ) {
      const segmentDistance = distance(
        authored[index].position,
        authored[index + 1].position,
      );

      if (segmentDistance > largestDistance) {
        largestDistance = segmentDistance;
        segmentIndex = index;
      }
    }
  }

  const start = authored[segmentIndex];
  const end = authored[segmentIndex + 1];
  const previous =
    authored[Math.max(0, segmentIndex - 1)] ??
    start;
  const following =
    authored[
      Math.min(
        authored.length - 1,
        segmentIndex + 2,
      )
    ] ?? end;

  const position = catmullRomMidpoint(
    previous.position,
    start.position,
    end.position,
    following.position,
  );

  const insertedPointId = createId("path-point");

  const inserted: MovementPathPoint = {
    id: insertedPointId,
    label: "New route point",
    position,
    timeSeconds: clamp(
      (start.timeSeconds + end.timeSeconds) / 2,
      0.01,
      Math.max(0.01, durationSeconds - 0.01),
    ),
    speedKmh:
      (start.speedKmh + end.speedKmh) / 2,
    rotation: headingDegrees(
      start.position,
      end.position,
      start.rotation,
    ),
    action: "Cruise",
    notes: "",
  };

  const nextAuthored = [
    ...authored.slice(0, segmentIndex + 1),
    inserted,
    ...authored.slice(segmentIndex + 1),
  ];

  const aligned = alignAuthoredOnlyToTangents(
    redistributeAuthoredTimes(
      relabelPointZRoute(nextAuthored),
      durationSeconds,
    ),
  );

  return {
    insertedPointId,
    pathPoints: [...aligned, ...physics].sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    ),
  };
}

export function removeIntermediateRoutePoint({
  pathPoints,
  pointId,
}: {
  pathPoints: MovementPathPoint[];
  pointId: string;
}): MovementPathPoint[] {
  const authored = pathPoints
    .filter(
      (point) => !isPhysicsGeneratedRoutePoint(point),
    )
    .sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );

  const target = authored.find(
    (point) => point.id === pointId,
  );

  if (
    !target ||
    !canDeleteAuthoredRoutePoint(target, authored)
  ) {
    return pathPoints;
  }

  return alignAuthoredRouteToTangents(
    pathPoints.filter(
      (point) => point.id !== pointId,
    ),
  );
}

export function applySafeAuthoredPointUpdate({
  pathPoints,
  pointId,
  updates,
  collisionPosition,
  durationSeconds,
  speedKmh,
  participantType,
  createId = defaultCreateId,
}: {
  pathPoints: MovementPathPoint[];
  pointId: string;
  updates: Partial<MovementPathPoint>;
  collisionPosition: ReconstructionPosition;
  durationSeconds: number;
  speedKmh: number;
  participantType: ReconstructionVehicleType;
  createId?: (prefix: string) => string;
}): MovementPathPoint[] {
  const authored = pathPoints
    .filter(
      (point) => !isPhysicsGeneratedRoutePoint(point),
    )
    .sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );

  const target = authored.find(
    (point) => point.id === pointId,
  );

  if (!target) {
    return pathPoints;
  }

  const role = getAuthoredRoutePointRole(
    target,
    authored,
  );

  const safeUpdates: Partial<MovementPathPoint> = {
    ...updates,
  };

  delete safeUpdates.id;

  if (role === "PointZ") {
    delete safeUpdates.position;
    delete safeUpdates.label;
    delete safeUpdates.action;

    safeUpdates.notes = updates.notes
      ? normaliseNotes(
          updates.notes,
          POINT_Z_NOTE_MARKER,
        )
      : target.notes;
  } else if (role === "PointOne") {
    delete safeUpdates.label;

    if (
      updates.action !== undefined &&
      updates.action !== "Start" &&
      updates.action !== "Enter Scene"
    ) {
      delete safeUpdates.action;
    }
  } else if (updates.action === "Impact") {
    safeUpdates.action = "Cruise";
  }

  const updated = pathPoints.map((point) =>
    point.id === pointId
      ? {
          ...point,
          ...safeUpdates,
        }
      : point,
  );

  return normalisePointZRoute({
    pathPoints: updated,
    collisionPosition,
    durationSeconds,
    speedKmh,
    participantType,
    createId,
  });
}

export function updatePointZPosition({
  pathPoints,
  collisionPosition,
  durationSeconds,
  speedKmh,
  participantType,
  createId = defaultCreateId,
}: Omit<
  NormalisePointZRouteOptions,
  "collisionPosition"
> & {
  collisionPosition: ReconstructionPosition;
}): MovementPathPoint[] {
  return normalisePointZRoute({
    pathPoints,
    collisionPosition,
    durationSeconds,
    speedKmh,
    participantType,
    createId,
  });
}

/**
 * Impact reassignment is intentionally disabled.
 * Point Z is the only authored impact point.
 */
export function setParticipantImpactPoint({
  pathPoints,
  durationSeconds,
}: {
  pathPoints: MovementPathPoint[];
  pointId: string;
  durationSeconds: number;
}): MovementPathPoint[] {
  const authored = pathPoints
    .filter(
      (point) => !isPhysicsGeneratedRoutePoint(point),
    )
    .sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );

  if (authored.length < 2) {
    return pathPoints;
  }

  const pointZ =
    authored.find(isPointZ) ??
    authored.find(
      (point) => point.action === "Impact",
    ) ??
    authored[authored.length - 1];

  const protectedAuthored = authored
    .filter(
      (point) =>
        point.timeSeconds <= pointZ.timeSeconds ||
        point.id === pointZ.id,
    )
    .map((point, index) => {
      if (point.id === pointZ.id) {
        return {
          ...point,
          action: "Impact" as const,
          label: "Point Z · Primary collision",
          notes: normaliseNotes(
            point.notes,
            POINT_Z_NOTE_MARKER,
          ),
        };
      }

      if (index === 0) {
        return {
          ...point,
          action:
            point.action === "Enter Scene"
              ? ("Enter Scene" as const)
              : ("Start" as const),
        };
      }

      return {
        ...point,
        action: sanitiseIntermediateAction(
          point.action,
        ),
      };
    });

  const physics = pathPoints.filter(
    isPhysicsGeneratedRoutePoint,
  );

  return [
    ...alignAuthoredOnlyToTangents(
      redistributeAuthoredTimes(
        relabelPointZRoute(protectedAuthored),
        durationSeconds,
      ),
    ),
    ...physics,
  ].sort(
    (first, second) =>
      first.timeSeconds - second.timeSeconds,
  );
}

export function getAuthoredImpactPoint(
  pathPoints: MovementPathPoint[],
): MovementPathPoint | null {
  const authored = pathPoints
    .filter(
      (point) => !isPhysicsGeneratedRoutePoint(point),
    )
    .sort(
      (first, second) =>
        first.timeSeconds - second.timeSeconds,
    );

  return (
    authored.find(isPointZ) ??
    authored.find(
      (point) => point.action === "Impact",
    ) ??
    authored[authored.length - 1] ??
    null
  );
}

export function geoCoordinateToScenePosition(
  calibration: FieldSceneCalibration,
  coordinate: GeoCoordinate,
): ReconstructionPosition {
  const originLatitudeRadians =
    (calibration.origin.latitude * Math.PI) / 180;

  const coordinateLatitudeRadians =
    (coordinate.latitude * Math.PI) / 180;

  const deltaLatitudeRadians =
    ((coordinate.latitude -
      calibration.origin.latitude) *
      Math.PI) /
    180;

  const deltaLongitudeRadians =
    ((coordinate.longitude -
      calibration.origin.longitude) *
      Math.PI) /
    180;

  const averageLatitude =
    (originLatitudeRadians +
      coordinateLatitudeRadians) /
    2;

  const eastMetres =
    deltaLongitudeRadians *
    EARTH_RADIUS_METRES *
    Math.cos(averageLatitude);

  const northMetres =
    deltaLatitudeRadians * EARTH_RADIUS_METRES;

  const rotationRadians =
    (calibration.rotationDegrees * Math.PI) / 180;

  const xAxis = {
    east: Math.sin(rotationRadians),
    north: Math.cos(rotationRadians),
  };

  const rightAxis = {
    east: Math.cos(rotationRadians),
    north: -Math.sin(rotationRadians),
  };

  const ySign =
    calibration.yAxisSide === "Left" ? -1 : 1;

  const xMetres =
    eastMetres * xAxis.east +
    northMetres * xAxis.north;

  const yMetres =
    (eastMetres * rightAxis.east +
      northMetres * rightAxis.north) *
    ySign;

  return {
    x: clamp(
      (xMetres /
        Math.max(
          0.01,
          calibration.sceneWidthMetres,
        )) *
        100,
      0,
      100,
    ),
    y: clamp(
      (yMetres /
        Math.max(
          0.01,
          calibration.sceneHeightMetres,
        )) *
        100,
      0,
      100,
    ),
  };
}
