/*
 * [RoadSafe:ManualBezierParticipantPathV1]
 *
 * Investigator-authored cubic Bezier controls for participant approach paths.
 *
 * Design rules:
 * - Point 1 / intermediate points / Point Z remain the authoritative anchors.
 * - Handles are stored on those anchors and are auditable reconstruction data.
 * - Live GPS tracing remains a separate capture workflow.
 * - Physics-generated post-impact points are never converted into Bezier
 *   authoring points.
 * - Visual scale never affects route geometry.
 */

import type {
  MovementPathPoint,
  ReconstructionPosition,
  ReconstructionVehicle,
} from "../types/reconstruction";
import {
  getIntegratedKinematicDistanceProgress,
} from "./reconstructionMotionKinematics";

export const MANUAL_BEZIER_NOTE_MARKER =
  "[RoadSafe:ManualBezier]";

const MANUAL_ROUTE_ANCHOR_NOTE_MARKER =
  "[RoadSafe:ManualRouteAnchor]";

const PHYSICS_POINT_PREFIXES = [
  "physics-point-",
  "detected-impact-",
  "physics-transition-",
  "legacy-impact-",
] as const;

const PHYSICS_NOTE_MARKERS = [
  "Generated by the RoadSafe deterministic 2D physics preview.",
  "Generated at the first swept body contact found along the participant routes.",
  "Physics takes over from the participant's guided route",
  "Physics-generated event.",
  "Generated by RoadSafe Rapier",
] as const;

function clamp(
  value: number,
  minimum: number,
  maximum: number,
): number {
  return Math.min(
    maximum,
    Math.max(
      minimum,
      value,
    ),
  );
}

function clampPosition(
  position:
    ReconstructionPosition,
): ReconstructionPosition {
  return {
    x:
      clamp(
        position.x,
        0,
        100,
      ),

    y:
      clamp(
        position.y,
        0,
        100,
      ),
  };
}

function isPhysicsPoint(
  point:
    MovementPathPoint,
): boolean {
  return (
    PHYSICS_POINT_PREFIXES.some(
      (prefix) =>
        point.id.startsWith(
          prefix,
        ),
    ) ||
    PHYSICS_NOTE_MARKERS.some(
      (marker) =>
        point.notes?.includes(
          marker,
        ),
    )
  );
}

export function getManualBezierAuthoredPoints(
  pathPoints:
    MovementPathPoint[],
): MovementPathPoint[] {
  return [
    ...pathPoints,
  ]
    .filter(
      (point) =>
        !isPhysicsPoint(
          point,
        ),
    )
    .sort(
      (
        first,
        second,
      ) =>
        first.timeSeconds -
        second.timeSeconds,
    );
}

function addBezierNote(
  notes:
    string | undefined,
): string {
  const current =
    (
      notes ??
      ""
    )
      .replace(
        "[RoadSafe:AutoRoadCurve]",
        "",
      )
      .trim();

  const withBezier =
    current.includes(
      MANUAL_BEZIER_NOTE_MARKER,
    )
      ? current
      : current
        ? `${MANUAL_BEZIER_NOTE_MARKER}\n${current}`
        : MANUAL_BEZIER_NOTE_MARKER;

  return withBezier.includes(
    MANUAL_ROUTE_ANCHOR_NOTE_MARKER,
  )
    ? withBezier
    : `${MANUAL_ROUTE_ANCHOR_NOTE_MARKER}\n${withBezier}`;
}

function vector(
  from:
    ReconstructionPosition,
  to:
    ReconstructionPosition,
): ReconstructionPosition {
  return {
    x:
      to.x -
      from.x,

    y:
      to.y -
      from.y,
  };
}

function length(
  value:
    ReconstructionPosition,
): number {
  return Math.hypot(
    value.x,
    value.y,
  );
}

function normalise(
  value:
    ReconstructionPosition,
  fallback:
    ReconstructionPosition,
): ReconstructionPosition {
  const magnitude =
    length(
      value,
    );

  if (
    magnitude <
    0.000001
  ) {
    const fallbackMagnitude =
      Math.max(
        0.000001,
        length(
          fallback,
        ),
      );

    return {
      x:
        fallback.x /
        fallbackMagnitude,

      y:
        fallback.y /
        fallbackMagnitude,
    };
  }

  return {
    x:
      value.x /
      magnitude,

    y:
      value.y /
      magnitude,
  };
}

function addScaled(
  origin:
    ReconstructionPosition,
  direction:
    ReconstructionPosition,
  distance:
    number,
): ReconstructionPosition {
  return clampPosition({
    x:
      origin.x +
      direction.x *
      distance,

    y:
      origin.y +
      direction.y *
      distance,
  });
}

function distance(
  first:
    ReconstructionPosition,
  second:
    ReconstructionPosition,
): number {
  return Math.hypot(
    second.x -
      first.x,
    second.y -
      first.y,
  );
}

function selectedSegmentIndex(
  points:
    MovementPathPoint[],
  selectedPointId:
    string | null,
): number {
  if (
    points.length <
    2
  ) {
    return -1;
  }

  const selectedIndex =
    selectedPointId
      ? points.findIndex(
          (point) =>
            point.id ===
            selectedPointId,
        )
      : 0;

  if (
    selectedIndex <
    0
  ) {
    return 0;
  }

  if (
    selectedIndex >=
    points.length -
      1
  ) {
    return Math.max(
      0,
      points.length -
        2,
    );
  }

  return selectedIndex;
}

function defaultSegmentHandles(
  points:
    MovementPathPoint[],
  segmentIndex:
    number,
): {
  controlOne:
    ReconstructionPosition;
  controlTwo:
    ReconstructionPosition;
} {
  const start =
    points[
      segmentIndex
    ];

  const end =
    points[
      segmentIndex +
      1
    ];

  const previous =
    points[
      Math.max(
        0,
        segmentIndex -
          1,
      )
    ];

  const following =
    points[
      Math.min(
        points.length -
          1,
        segmentIndex +
          2,
      )
    ];

  const segmentVector =
    vector(
      start.position,
      end.position,
    );

  const segmentLength =
    Math.max(
      0.001,
      length(
        segmentVector,
      ),
    );

  const startDirection =
    normalise(
      vector(
        previous.position,
        end.position,
      ),
      segmentVector,
    );

  const endDirection =
    normalise(
      vector(
        start.position,
        following.position,
      ),
      segmentVector,
    );

  const previousLength =
    Math.max(
      0.001,
      distance(
        previous.position,
        start.position,
      ),
    );

  const nextLength =
    Math.max(
      0.001,
      distance(
        end.position,
        following.position,
      ),
    );

  /*
   * These defaults intentionally approximate the existing RoadSafe automatic
   * spline. Enabling Bezier therefore starts close to the current route rather
   * than snapping to an unrelated curve.
   */
  const outDistance =
    Math.min(
      segmentLength *
        0.24,
      Math.max(
        1.2,
        previousLength *
          0.38,
      ),
      segmentLength *
        0.42,
    );

  const inDistance =
    Math.min(
      segmentLength *
        0.24,
      Math.max(
        1.2,
        nextLength *
          0.38,
      ),
      segmentLength *
        0.42,
    );

  return {
    controlOne:
      addScaled(
        start.position,
        startDirection,
        outDistance,
      ),

    controlTwo:
      addScaled(
        end.position,
        endDirection,
        -inDistance,
      ),
  };
}

function stripPhysics(
  pathPoints:
    MovementPathPoint[],
): MovementPathPoint[] {
  return pathPoints.filter(
    (point) =>
      !isPhysicsPoint(
        point,
      ),
  );
}

export interface ManualBezierSegmentView {
  startPoint:
    MovementPathPoint;
  endPoint:
    MovementPathPoint;
  segmentIndex: number;
  enabled: boolean;
  controlOne:
    ReconstructionPosition;
  controlTwo:
    ReconstructionPosition;
}

export function getManualBezierSegmentView(
  pathPoints:
    MovementPathPoint[],
  selectedPointId:
    string | null,
): ManualBezierSegmentView | null {
  const points =
    getManualBezierAuthoredPoints(
      pathPoints,
    );

  const index =
    selectedSegmentIndex(
      points,
      selectedPointId,
    );

  if (
    index <
    0
  ) {
    return null;
  }

  const startPoint =
    points[index];

  const endPoint =
    points[
      index +
      1
    ];

  const defaults =
    defaultSegmentHandles(
      points,
      index,
    );

  return {
    startPoint,
    endPoint,
    segmentIndex:
      index,

    enabled:
      startPoint
        .pathInterpolation ===
      "Bezier",

    controlOne:
      startPoint
        .bezierOut ??
      defaults.controlOne,

    controlTwo:
      endPoint
        .bezierIn ??
      defaults.controlTwo,
  };
}

export function setManualBezierSegmentEnabled(
  pathPoints:
    MovementPathPoint[],
  selectedPointId:
    string | null,
  enabled:
    boolean,
): MovementPathPoint[] {
  const clean =
    stripPhysics(
      pathPoints,
    );

  const points = [
    ...clean,
  ].sort(
    (
      first,
      second,
    ) =>
      first.timeSeconds -
      second.timeSeconds,
  );

  const index =
    selectedSegmentIndex(
      points,
      selectedPointId,
    );

  if (
    index <
    0
  ) {
    return clean;
  }

  const start =
    points[index];

  const end =
    points[
      index +
      1
    ];

  const defaults =
    defaultSegmentHandles(
      points,
      index,
    );

  return points.map(
    (point) => {
      if (
        point.id ===
        start.id
      ) {
        return {
          ...point,

          pathInterpolation:
            enabled
              ? "Bezier"
              : "Auto",

          bezierOut:
            point.bezierOut ??
            defaults
              .controlOne,

          notes:
            enabled
              ? addBezierNote(
                  point.notes,
                )
              : point.notes,
        };
      }

      if (
        point.id ===
        end.id
      ) {
        return {
          ...point,

          bezierIn:
            point.bezierIn ??
            defaults
              .controlTwo,

          notes:
            enabled
              ? addBezierNote(
                  point.notes,
                )
              : point.notes,
        };
      }

      return point;
    },
  );
}

export function resetManualBezierSegment(
  pathPoints:
    MovementPathPoint[],
  selectedPointId:
    string | null,
): MovementPathPoint[] {
  const clean =
    stripPhysics(
      pathPoints,
    );

  const points = [
    ...clean,
  ].sort(
    (
      first,
      second,
    ) =>
      first.timeSeconds -
      second.timeSeconds,
  );

  const index =
    selectedSegmentIndex(
      points,
      selectedPointId,
    );

  if (
    index <
    0
  ) {
    return clean;
  }

  const start =
    points[index];

  const end =
    points[
      index +
      1
    ];

  return points.map(
    (point) => {
      if (
        point.id ===
        start.id
      ) {
        const {
          bezierOut:
            _bezierOut,
          ...rest
        } = point;

        return {
          ...rest,
          pathInterpolation:
            "Auto",
        };
      }

      if (
        point.id ===
        end.id
      ) {
        const {
          bezierIn:
            _bezierIn,
          ...rest
        } = point;

        return rest;
      }

      return point;
    },
  );
}

export function updateManualBezierHandle(
  pathPoints:
    MovementPathPoint[],
  pointId:
    string,
  handle:
    "in" | "out",
  position:
    ReconstructionPosition,
): MovementPathPoint[] {
  const clean =
    stripPhysics(
      pathPoints,
    );

  const nextPosition =
    clampPosition(
      position,
    );

  return clean.map(
    (point) => {
      if (
        point.id !==
        pointId
      ) {
        return point;
      }

      return handle ===
        "in"
        ? {
            ...point,
            bezierIn:
              nextPosition,
            notes:
              addBezierNote(
                point.notes,
              ),
          }
        : {
            ...point,
            pathInterpolation:
              "Bezier",
            bezierOut:
              nextPosition,
            notes:
              addBezierNote(
                point.notes,
              ),
          };
    },
  );
}

export function shiftBezierHandlesWithAnchor(
  point:
    MovementPathPoint,
  nextPosition:
    ReconstructionPosition,
): Partial<MovementPathPoint> {
  const delta = {
    x:
      nextPosition.x -
      point.position.x,

    y:
      nextPosition.y -
      point.position.y,
  };

  return {
    position:
      nextPosition,

    bezierIn:
      point.bezierIn
        ? clampPosition({
            x:
              point
                .bezierIn
                .x +
              delta.x,

            y:
              point
                .bezierIn
                .y +
              delta.y,
          })
        : undefined,

    bezierOut:
      point.bezierOut
        ? clampPosition({
            x:
              point
                .bezierOut
                .x +
              delta.x,

            y:
              point
                .bezierOut
                .y +
              delta.y,
          })
        : undefined,
  };
}

function cubicPoint(
  start:
    ReconstructionPosition,
  controlOne:
    ReconstructionPosition,
  controlTwo:
    ReconstructionPosition,
  end:
    ReconstructionPosition,
  progress:
    number,
): ReconstructionPosition {
  const inverse =
    1 -
    progress;

  const inverseSquared =
    inverse *
    inverse;

  const progressSquared =
    progress *
    progress;

  return {
    x:
      inverseSquared *
        inverse *
        start.x +
      3 *
        inverseSquared *
        progress *
        controlOne.x +
      3 *
        inverse *
        progressSquared *
        controlTwo.x +
      progressSquared *
        progress *
        end.x,

    y:
      inverseSquared *
        inverse *
        start.y +
      3 *
        inverseSquared *
        progress *
        controlOne.y +
      3 *
        inverse *
        progressSquared *
        controlTwo.y +
      progressSquared *
        progress *
        end.y,
  };
}

function cubicTangent(
  start:
    ReconstructionPosition,
  controlOne:
    ReconstructionPosition,
  controlTwo:
    ReconstructionPosition,
  end:
    ReconstructionPosition,
  progress:
    number,
): ReconstructionPosition {
  const inverse =
    1 -
    progress;

  return {
    x:
      3 *
        inverse *
        inverse *
        (
          controlOne.x -
          start.x
        ) +
      6 *
        inverse *
        progress *
        (
          controlTwo.x -
          controlOne.x
        ) +
      3 *
        progress *
        progress *
        (
          end.x -
          controlTwo.x
        ),

    y:
      3 *
        inverse *
        inverse *
        (
          controlOne.y -
          start.y
        ) +
      6 *
        inverse *
        progress *
        (
          controlTwo.y -
          controlOne.y
        ) +
      3 *
        progress *
        progress *
        (
          end.y -
          controlTwo.y
        ),
  };
}

export function getBezierDisplayPositions(
  pathPoints:
    MovementPathPoint[],
): ReconstructionPosition[] {
  const points =
    getManualBezierAuthoredPoints(
      pathPoints,
    );

  if (
    points.length <
    2
  ) {
    return points.map(
      (point) => ({
        ...point.position,
      }),
    );
  }

  const result:
    ReconstructionPosition[] =
      [];

  for (
    let index = 0;
    index <
      points.length -
        1;
    index +=
      1
  ) {
    const start =
      points[index];

    const end =
      points[
        index +
        1
      ];

    if (
      index ===
      0
    ) {
      result.push({
        ...start.position,
      });
    }

    if (
      start
        .pathInterpolation !==
      "Bezier"
    ) {
      result.push({
        ...end.position,
      });

      continue;
    }

    const defaults =
      defaultSegmentHandles(
        points,
        index,
      );

    const controlOne =
      start.bezierOut ??
      defaults.controlOne;

    const controlTwo =
      end.bezierIn ??
      defaults.controlTwo;

    const subdivisions =
      Math.round(
        clamp(
          distance(
            start.position,
            end.position,
          ) *
            1.4,
          12,
          30,
        ),
      );

    for (
      let sampleIndex = 1;
      sampleIndex <=
        subdivisions;
      sampleIndex +=
        1
    ) {
      result.push(
        clampPosition(
          cubicPoint(
            start.position,
            controlOne,
            controlTwo,
            end.position,
            sampleIndex /
              subdivisions,
          ),
        ),
      );
    }
  }

  return result;
}

export function getManualBezierSegmentSvgPath(
  segment:
    ManualBezierSegmentView,
): string {
  const start =
    segment
      .startPoint
      .position;

  const end =
    segment
      .endPoint
      .position;

  const controlOne =
    segment
      .controlOne;

  const controlTwo =
    segment
      .controlTwo;

  return [
    `M ${start.x} ${start.y}`,
    `C ${controlOne.x} ${controlOne.y}, ${controlTwo.x} ${controlTwo.y}, ${end.x} ${end.y}`,
  ].join(" ");
}

export function hasManualBezierSegments(
  participant:
    Pick<
      ReconstructionVehicle,
      "pathPoints"
    >,
): boolean {
  return participant
    .pathPoints
    .some(
      (point) =>
        point
          .pathInterpolation ===
        "Bezier",
    );
}

function metricDistance(
  first:
    ReconstructionPosition,
  second:
    ReconstructionPosition,
  worldDimensions: {
    widthMetres:
      number;
    heightMetres:
      number;
  },
): number {
  return Math.hypot(
    (
      (
        second.x -
        first.x
      ) /
      100
    ) *
      Math.max(
        0.001,
        worldDimensions
          .widthMetres,
      ),

    (
      (
        second.y -
        first.y
      ) /
      100
    ) *
      Math.max(
        0.001,
        worldDimensions
          .heightMetres,
      ),
  );
}

function curveProgressAtDistanceFraction(
  start:
    ReconstructionPosition,
  controlOne:
    ReconstructionPosition,
  controlTwo:
    ReconstructionPosition,
  end:
    ReconstructionPosition,
  distanceFraction:
    number,
  worldDimensions: {
    widthMetres:
      number;
    heightMetres:
      number;
  },
): number {
  const subdivisions =
    32;

  const cumulative:
    {
      progress: number;
      distance: number;
    }[] = [
      {
        progress: 0,
        distance: 0,
      },
    ];

  let previous =
    start;

  let travelled =
    0;

  for (
    let index = 1;
    index <=
      subdivisions;
    index +=
      1
  ) {
    const progress =
      index /
      subdivisions;

    const position =
      cubicPoint(
        start,
        controlOne,
        controlTwo,
        end,
        progress,
      );

    travelled +=
      metricDistance(
        previous,
        position,
        worldDimensions,
      );

    cumulative.push({
      progress,
      distance:
        travelled,
    });

    previous =
      position;
  }

  if (
    travelled <
    0.000001
  ) {
    return clamp(
      distanceFraction,
      0,
      1,
    );
  }

  const target =
    travelled *
    clamp(
      distanceFraction,
      0,
      1,
    );

  for (
    let index = 1;
    index <
      cumulative.length;
    index +=
      1
  ) {
    const previousSample =
      cumulative[
        index -
          1
      ];

    const nextSample =
      cumulative[
        index
      ];

    if (
      target >
      nextSample.distance
    ) {
      continue;
    }

    const sectionDistance =
      Math.max(
        0.000001,
        nextSample.distance -
          previousSample.distance,
      );

    const local =
      clamp(
        (
          target -
          previousSample.distance
        ) /
          sectionDistance,
        0,
        1,
      );

    return (
      previousSample.progress +
      (
        nextSample.progress -
        previousSample.progress
      ) *
        local
    );
  }

  return 1;
}

export function sampleManualBezierAtTime(
  participant:
    ReconstructionVehicle,
  timeSeconds:
    number,
  worldDimensions: {
    widthMetres:
      number;
    heightMetres:
      number;
  },
): {
  position:
    ReconstructionPosition;
  rotationDegrees:
    number;
} | null {
  const points =
    getManualBezierAuthoredPoints(
      participant
        .pathPoints,
    );

  if (
    points.length <
    2
  ) {
    return null;
  }

  const segmentIndex =
    points.findIndex(
      (
        point,
        index,
      ) =>
        index <
          points.length -
            1 &&
        timeSeconds >=
          point.timeSeconds &&
        timeSeconds <=
          points[
            index +
              1
          ]
            .timeSeconds,
    );

  if (
    segmentIndex <
    0
  ) {
    return null;
  }

  const start =
    points[
      segmentIndex
    ];

  const end =
    points[
      segmentIndex +
        1
    ];

  if (
    start
      .pathInterpolation !==
    "Bezier"
  ) {
    return null;
  }

  const defaults =
    defaultSegmentHandles(
      points,
      segmentIndex,
    );

  const controlOne =
    start.bezierOut ??
    defaults.controlOne;

  const controlTwo =
    end.bezierIn ??
    defaults.controlTwo;

  const duration =
    Math.max(
      0.0001,
      end.timeSeconds -
        start.timeSeconds,
    );

  const timeProgress =
    clamp(
      (
        timeSeconds -
        start.timeSeconds
      ) /
        duration,
      0,
      1,
    );

  const distanceProgress =
    getIntegratedKinematicDistanceProgress(
      start.action ===
        "Stop"
        ? 0
        : start.speedKmh,

      end.action ===
        "Stop"
        ? 0
        : end.speedKmh,

      timeProgress,
    );

  const progress =
    curveProgressAtDistanceFraction(
      start.position,
      controlOne,
      controlTwo,
      end.position,
      distanceProgress,
      worldDimensions,
    );

  const position =
    clampPosition(
      cubicPoint(
        start.position,
        controlOne,
        controlTwo,
        end.position,
        progress,
      ),
    );

  const tangent =
    cubicTangent(
      start.position,
      controlOne,
      controlTwo,
      end.position,
      progress,
    );

  const metricX =
    (
      tangent.x /
      100
    ) *
    Math.max(
      0.001,
      worldDimensions
        .widthMetres,
    );

  const metricY =
    (
      tangent.y /
      100
    ) *
    Math.max(
      0.001,
      worldDimensions
        .heightMetres,
    );

  const rotationDegrees =
    (
      Math.atan2(
        metricY,
        metricX,
      ) *
        180 /
        Math.PI +
      360
    ) %
      360;

  return {
    position,
    rotationDegrees,
  };
}
