import type {
  AccidentReconstruction,
  MovementAction,
  MovementPathPoint,
  ReconstructionPosition,
  ReconstructionSceneObject,
  ReconstructionVehicle,
  SceneObjectType,
} from "../types/reconstruction";
import { AUTO_ROAD_CURVE_NOTE_MARKER } from "./reconstructionRoadRouting";
import {
  getIntegratedKinematicDistanceProgress,
  getSmoothKinematicSpeedKmh,
  type MetricSceneDimensions,
} from "./reconstructionMotionKinematics";


export interface ReconstructionImpactEffectState {
  active: boolean;
  impactTimeSeconds: number;
  intensity: number;
  position: ReconstructionPosition;
  participantIds: string[];
  progress: number;
}

interface Vector2 {
  x: number;
  y: number;
}

interface ParticipantMotionProfile {
  curveTension: number;
  straightAngleTolerance: number;
  cornerSpeedLoss: number;
  maximumWalkingSpeedKmh: number | null;
  gaitSwayScenePercent: number;
  gaitRotationDegrees: number;
}

interface SegmentMotionGeometry {
  position: ReconstructionPosition;
  tangent: Vector2;
  turnSeverityDegrees: number;
}

interface BezierArcLengthSample {
  progress: number;
  distance: number;
}

interface SegmentMotionSpline {
  linear: boolean;
  physicsControlled: boolean;
  roadGraphControlled: boolean;
  startPoint: MovementPathPoint;
  endPoint: MovementPathPoint;
  segmentDirection: Vector2;
  controlOne: ReconstructionPosition;
  controlTwo: ReconstructionPosition;
  arcLengthSamples: BezierArcLengthSample[];
  startTurnSeverityDegrees: number;
  endTurnSeverityDegrees: number;
}

const HUMAN_TYPES = new Set<
  ReconstructionVehicle["type"]
>([
  "Pedestrian",
  "Officer",
  "Witness",
]);

const PHYSICS_POINT_PREFIXES = [
  "physics-point-",
  "detected-impact-",
  "physics-transition-",
  "legacy-impact-",
] as const;

const PHYSICS_NOTE_MARKERS = [
  "Generated by the RoadSafe deterministic 2D physics preview.",
  "Generated at the first swept body contact found along the participant routes.",
  "Physics takes over from the participant's guided route",
  "Physics-generated event.",
] as const;

const PLACEHOLDER_REST_LABELS = new Set([
  "final position",
  "final resting position",
  "rest position",
  "natural stop",
]);

const POST_IMPACT_ACTIONS = new Set<MovementAction>([
  "Impact",
  "Ricochet",
  "Deflect",
  "Slide",
  "Fall",
  "Stop",
]);

export function clamp(
  value: number,
  minimum: number,
  maximum: number,
): number {
  return Math.min(
    maximum,
    Math.max(minimum, value),
  );
}

export function interpolate(
  start: number,
  end: number,
  progress: number,
): number {
  return start + (end - start) * progress;
}

function interpolateAngle(
  start: number,
  end: number,
  progress: number,
): number {
  const difference =
    ((end - start + 540) % 360) - 180;

  return start + difference * progress;
}

function degreesToRadians(
  degrees: number,
): number {
  return (degrees * Math.PI) / 180;
}

function vectorLength(
  vector: Vector2,
): number {
  return Math.hypot(vector.x, vector.y);
}

function subtractPositions(
  end: ReconstructionPosition,
  start: ReconstructionPosition,
): Vector2 {
  return {
    x: end.x - start.x,
    y: end.y - start.y,
  };
}

function normaliseVector(
  vector: Vector2,
  fallback: Vector2 = { x: 1, y: 0 },
): Vector2 {
  const length = vectorLength(vector);

  if (length < 0.000001) {
    const fallbackLength =
      vectorLength(fallback) || 1;

    return {
      x: fallback.x / fallbackLength,
      y: fallback.y / fallbackLength,
    };
  }

  return {
    x: vector.x / length,
    y: vector.y / length,
  };
}

function angleFromVector(
  vector: Vector2,
): number {
  return (
    (Math.atan2(vector.y, vector.x) * 180) /
      Math.PI +
    360
  ) % 360;
}

function angleDifferenceDegrees(
  first: Vector2,
  second: Vector2,
): number {
  const firstUnit = normaliseVector(first);
  const secondUnit = normaliseVector(second);

  const dot = clamp(
    firstUnit.x * secondUnit.x +
      firstUnit.y * secondUnit.y,
    -1,
    1,
  );

  return (Math.acos(dot) * 180) / Math.PI;
}

function distanceBetween(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
): number {
  return Math.hypot(
    second.x - first.x,
    second.y - first.y,
  );
}

function addScaledVector(
  position: ReconstructionPosition,
  direction: Vector2,
  distance: number,
): ReconstructionPosition {
  return {
    x: position.x + direction.x * distance,
    y: position.y + direction.y * distance,
  };
}

function getMotionProfile(
  participant: ReconstructionVehicle,
): ParticipantMotionProfile {
  switch (participant.type) {
    case "Bus":
      return {
        curveTension: 0.52,
        straightAngleTolerance: 4,
        cornerSpeedLoss: 0.52,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };

    case "Truck":
      return {
        curveTension: 0.48,
        straightAngleTolerance: 4,
        cornerSpeedLoss: 0.48,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };

    case "Motorcycle":
      return {
        curveTension: 0.74,
        straightAngleTolerance: 5,
        cornerSpeedLoss: 0.24,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };

    case "Bicycle":
      return {
        curveTension: 0.78,
        straightAngleTolerance: 6,
        cornerSpeedLoss: 0.28,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };

    case "Pedestrian":
    case "Officer":
    case "Witness":
      return {
        curveTension: 0.86,
        straightAngleTolerance: 8,
        cornerSpeedLoss: 0.08,
        maximumWalkingSpeedKmh: 6.5,
        gaitSwayScenePercent: 0.11,
        gaitRotationDegrees: 1.6,
      };

    case "Car":
    default:
      return {
        curveTension: 0.64,
        straightAngleTolerance: 4,
        cornerSpeedLoss: 0.34,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };
  }
}

function smoothStep(progress: number): number {
  const safe = clamp(progress, 0, 1);
  return safe * safe * (3 - 2 * safe);
}

function smootherStep(progress: number): number {
  const safe = clamp(progress, 0, 1);
  return (
    safe *
    safe *
    safe *
    (safe * (safe * 6 - 15) + 10)
  );
}

function getKinematicPositionProgress(
  participant: ReconstructionVehicle,
  start: MovementPathPoint,
  end: MovementPathPoint,
  timeProgress: number,
): number {
  const startSpeed =
    start.action === "Stop"
      ? 0
      : getCanonicalPlaybackSpeedKmh(
          participant,
          start.speedKmh,
          start.action,
        );

  const endSpeed =
    end.action === "Stop"
      ? 0
      : getCanonicalPlaybackSpeedKmh(
          participant,
          end.speedKmh,
          end.action,
        );

  return getIntegratedKinematicDistanceProgress(
    startSpeed,
    endSpeed,
    timeProgress,
  );
}

export function sortMovementPathPoints(
  points: MovementPathPoint[],
): MovementPathPoint[] {
  return [...points].sort(
    (first, second) =>
      first.timeSeconds - second.timeSeconds,
  );
}

export function isPhysicsGeneratedPathPoint(
  point: MovementPathPoint,
): boolean {
  return (
    PHYSICS_POINT_PREFIXES.some((prefix) =>
      point.id.startsWith(prefix),
    ) ||
    PHYSICS_NOTE_MARKERS.some((marker) =>
      point.notes?.includes(marker),
    )
  );
}

export function isPhysicsCalculatedRestPoint(
  point: MovementPathPoint,
): boolean {
  return (
    point.action === "Stop" &&
    isPhysicsGeneratedPathPoint(point)
  );
}

export function isUnverifiedAutoRestPoint(
  point: MovementPathPoint,
): boolean {
  if (point.action !== "Stop") {
    return false;
  }

  const label =
    point.label.trim().toLowerCase();

  const placeholderId =
    point.id.startsWith("path-stop-") ||
    point.id.startsWith("path-final-");

  const placeholderLabel =
    PLACEHOLDER_REST_LABELS.has(label);

  const hasInvestigatorEvidence =
    Boolean(point.linkedSceneObjectId) ||
    Boolean(point.notes?.trim());

  return (
    placeholderId &&
    placeholderLabel &&
    !hasInvestigatorEvidence &&
    !isPhysicsGeneratedPathPoint(point)
  );
}

export function isObservedRestPoint(
  point: MovementPathPoint,
): boolean {
  return (
    point.action === "Stop" &&
    !isPhysicsGeneratedPathPoint(point) &&
    !isUnverifiedAutoRestPoint(point)
  );
}

function samePosition(
  left: ReconstructionPosition,
  right: ReconstructionPosition,
): boolean {
  return (
    Math.abs(left.x - right.x) <= 0.0001 &&
    Math.abs(left.y - right.y) <= 0.0001
  );
}

function areDuplicatePoints(
  left: MovementPathPoint,
  right: MovementPathPoint,
): boolean {
  return (
    Math.abs(
      left.timeSeconds - right.timeSeconds,
    ) <= 0.0001 &&
    left.action === right.action &&
    samePosition(left.position, right.position) &&
    Math.abs(left.rotation - right.rotation) <=
      0.0001
  );
}

function isUnverifiedRouteContinuationPoint(
  point: MovementPathPoint,
  impactTimeSeconds: number | null,
): boolean {
  if (
    impactTimeSeconds === null ||
    point.timeSeconds <= impactTimeSeconds
  ) {
    return false;
  }

  if (
    isPhysicsGeneratedPathPoint(point) ||
    isObservedRestPoint(point)
  ) {
    return false;
  }

  const label =
    point.label.trim().toLowerCase();

  const looksLikeAutoRouteSample =
    /^route \d+$/.test(label) ||
    label === "natural stop";

  const hasInvestigatorEvidence =
    Boolean(point.linkedSceneObjectId) ||
    Boolean(point.notes?.trim());

  return (
    point.id.startsWith("path-point-") &&
    looksLikeAutoRouteSample &&
    !hasInvestigatorEvidence
  );
}

const sanitisedParticipantPathCache = new WeakMap<
  MovementPathPoint[],
  MovementPathPoint[]
>();

const participantPlaybackPathCache = new WeakMap<
  MovementPathPoint[],
  MovementPathPoint[]
>();

const participantMotionSplineCache = new WeakMap<
  MovementPathPoint[],
  Map<string, SegmentMotionSpline[]>
>();

/*
 * [RoadSafe:CanonicalMetricPlaybackGeometryV1]
 *
 * Reconstruction positions remain stored as 0–100 scene coordinates, but
 * travelled distance and trajectory heading are calculated in physical
 * metres. This prevents non-square scenes from stretching curves, headings
 * and physics input velocities.
 */
const DEFAULT_PLAYBACK_WORLD_DIMENSIONS:
  MetricSceneDimensions = {
    widthMetres: 100,
    heightMetres: 100,
  };

function normalisePlaybackWorldDimensions(
  worldDimensions?: MetricSceneDimensions,
): MetricSceneDimensions {
  const width =
    worldDimensions?.widthMetres;

  const height =
    worldDimensions?.heightMetres;

  return {
    widthMetres:
      Number.isFinite(width) &&
      Number(width) > 0
        ? Math.max(
            0.001,
            Number(width),
          )
        : DEFAULT_PLAYBACK_WORLD_DIMENSIONS.widthMetres,

    heightMetres:
      Number.isFinite(height) &&
      Number(height) > 0
        ? Math.max(
            0.001,
            Number(height),
          )
        : DEFAULT_PLAYBACK_WORLD_DIMENSIONS.heightMetres,
  };
}

function sceneVectorToMetres(
  vector: Vector2,
  worldDimensions: MetricSceneDimensions,
): Vector2 {
  return {
    x:
      (vector.x / 100) *
      worldDimensions.widthMetres,

    y:
      (vector.y / 100) *
      worldDimensions.heightMetres,
  };
}

function metricVectorBetween(
  end: ReconstructionPosition,
  start: ReconstructionPosition,
  worldDimensions: MetricSceneDimensions,
): Vector2 {
  return sceneVectorToMetres(
    subtractPositions(
      end,
      start,
    ),
    worldDimensions,
  );
}

function metricDistanceBetween(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
  worldDimensions: MetricSceneDimensions,
): number {
  return vectorLength(
    metricVectorBetween(
      second,
      first,
      worldDimensions,
    ),
  );
}

function metricDirectionBetween(
  end: ReconstructionPosition,
  start: ReconstructionPosition,
  worldDimensions: MetricSceneDimensions,
  fallback: Vector2 = {
    x: 1,
    y: 0,
  },
): Vector2 {
  return normaliseVector(
    metricVectorBetween(
      end,
      start,
      worldDimensions,
    ),
    fallback,
  );
}

function metricSplineCacheKey(
  participant: ReconstructionVehicle,
  worldDimensions: MetricSceneDimensions,
): string {
  return [
    participant.type,
    worldDimensions.widthMetres.toPrecision(12),
    worldDimensions.heightMetres.toPrecision(12),
  ].join("|");
}

export function sanitiseParticipantPathPoints(
  points: MovementPathPoint[],
): MovementPathPoint[] {
  const cached = sanitisedParticipantPathCache.get(points);
  if (cached) return cached;

  const sorted = sortMovementPathPoints(points);

  const firstAuthoredImpact = sorted.find(
    (point) =>
      point.action === "Impact" &&
      !isPhysicsGeneratedPathPoint(point),
  );

  const impactTimeSeconds =
    firstAuthoredImpact?.timeSeconds ?? null;

  const withoutUnverifiedGeneratedRoute =
    sorted.filter(
      (point) =>
        !isUnverifiedAutoRestPoint(point) &&
        !isUnverifiedRouteContinuationPoint(
          point,
          impactTimeSeconds,
        ),
    );

  const deduplicated =
    withoutUnverifiedGeneratedRoute.filter(
      (point, index, list) =>
        index === 0 ||
        !areDuplicatePoints(
          list[index - 1],
          point,
        ),
    );

  const hasImpact = deduplicated.some(
    (point) => point.action === "Impact",
  );

  const result =
    deduplicated.length >= 2 && hasImpact
      ? deduplicated
      : sorted;

  sanitisedParticipantPathCache.set(points, result);
  return result;
}

export function getInvestigatorPathPoints(
  participant: ReconstructionVehicle,
): MovementPathPoint[] {
  return sanitiseParticipantPathPoints(
    participant.pathPoints,
  ).filter(
    (point) =>
      !isPhysicsGeneratedPathPoint(point),
  );
}

export function getPhysicsPathPoints(
  participant: ReconstructionVehicle,
): MovementPathPoint[] {
  return sanitiseParticipantPathPoints(
    participant.pathPoints,
  ).filter(isPhysicsGeneratedPathPoint);
}

/**
 * Returns the path used only for animation playback.
 * Investigator-authored points remain preserved in participant.pathPoints,
 * but once an internal physics sample begins, later authored anchors are not
 * allowed to pull the moving body back to the collision marker.
 */

const VEHICLE_ROUTE_ANCHOR_ACTIONS = new Set<MovementAction>([
  "Start",
  "Enter Scene",
  "Brake",
  "Turn Left",
  "Turn Right",
  "Swerve",
  "Impact",
  "Ricochet",
  "Deflect",
  "Slide",
  "Fall",
  "Stop",
  "Exit Scene",
]);

function distanceFromPositionToSegment(
  position: ReconstructionPosition,
  start: ReconstructionPosition,
  end: ReconstructionPosition,
): number {
  const segmentX = end.x - start.x;
  const segmentY = end.y - start.y;
  const segmentLengthSquared =
    segmentX * segmentX +
    segmentY * segmentY;

  if (segmentLengthSquared < 0.000001) {
    return distanceBetween(position, start);
  }

  const projection = clamp(
    (
      (position.x - start.x) * segmentX +
      (position.y - start.y) * segmentY
    ) / segmentLengthSquared,
    0,
    1,
  );

  return Math.hypot(
    position.x -
      (start.x + segmentX * projection),
    position.y -
      (start.y + segmentY * projection),
  );
}

function simplifyMovementPathSection(
  points: MovementPathPoint[],
  tolerance: number,
): MovementPathPoint[] {
  if (points.length <= 2) {
    return points;
  }

  const first = points[0];
  const last = points[points.length - 1];

  let furthestIndex = -1;
  let furthestDistance = 0;

  for (
    let index = 1;
    index < points.length - 1;
    index += 1
  ) {
    const distance =
      distanceFromPositionToSegment(
        points[index].position,
        first.position,
        last.position,
      );

    if (distance > furthestDistance) {
      furthestDistance = distance;
      furthestIndex = index;
    }
  }

  if (
    furthestIndex < 0 ||
    furthestDistance <= tolerance
  ) {
    return [first, last];
  }

  const left = simplifyMovementPathSection(
    points.slice(0, furthestIndex + 1),
    tolerance,
  );

  const right = simplifyMovementPathSection(
    points.slice(furthestIndex),
    tolerance,
  );

  return [
    ...left.slice(0, -1),
    ...right,
  ];
}

function vehicleRouteStabilisationTolerance(
  participant: ReconstructionVehicle,
): number {
  switch (participant.type) {
    case "Bus":
    case "Truck":
      return 0.75;

    case "Motorcycle":
    case "Bicycle":
      return 0.45;

    case "Car":
    default:
      return 0.6;
  }
}

function stabiliseAuthoredVehiclePlaybackPath(
  participant: ReconstructionVehicle,
  points: MovementPathPoint[],
): MovementPathPoint[] {
  if (
    HUMAN_TYPES.has(participant.type) ||
    points.length < 3 ||
    points.some(
      (point) =>
        point.notes?.includes(
          AUTO_ROAD_CURVE_NOTE_MARKER,
        ) === true,
    )
  ) {
    return points;
  }

  const anchorIndices = points
    .map((point, index) => ({
      point,
      index,
    }))
    .filter(
      ({ point, index }) =>
        index === 0 ||
        index === points.length - 1 ||
        VEHICLE_ROUTE_ANCHOR_ACTIONS.has(
          point.action,
        ) ||
        point.pathInterpolation ===
          "Bezier" ||
        Boolean(
          point.bezierIn,
        ) ||
        Boolean(
          point.bezierOut,
        ) ||
        Boolean(point.linkedSceneObjectId),
    )
    .map(({ index }) => index);

  const uniqueAnchorIndices = [
    ...new Set(anchorIndices),
  ].sort((left, right) => left - right);

  const tolerance =
    vehicleRouteStabilisationTolerance(
      participant,
    );

  const stabilised: MovementPathPoint[] = [];

  for (
    let anchorIndex = 0;
    anchorIndex <
    uniqueAnchorIndices.length - 1;
    anchorIndex += 1
  ) {
    const startIndex =
      uniqueAnchorIndices[anchorIndex];

    const endIndex =
      uniqueAnchorIndices[anchorIndex + 1];

    const section =
      simplifyMovementPathSection(
        points.slice(
          startIndex,
          endIndex + 1,
        ),
        tolerance,
      );

    stabilised.push(
      ...(anchorIndex === 0
        ? section
        : section.slice(1)),
    );
  }

  return stabilised.length >= 2
    ? stabilised
    : points;
}

export function getParticipantPlaybackPathPoints(
  participant: ReconstructionVehicle,
): MovementPathPoint[] {
  const cached = participantPlaybackPathCache.get(
    participant.pathPoints,
  );
  if (cached) return cached;

  const points = sanitiseParticipantPathPoints(
    participant.pathPoints,
  );

  const firstPhysicsPoint = points.find(
    isPhysicsGeneratedPathPoint,
  );

  const stabilisedAuthoredPoints =
    stabiliseAuthoredVehiclePlaybackPath(
      participant,
      points.filter(
        (point) =>
          !isPhysicsGeneratedPathPoint(point),
      ),
    );

  if (!firstPhysicsPoint) {
    const result =
      stabilisedAuthoredPoints.length >= 2
        ? stabilisedAuthoredPoints
        : points;

    participantPlaybackPathCache.set(
      participant.pathPoints,
      result,
    );

    return result;
  }

  const authoredBeforePhysics =
    stabilisedAuthoredPoints.filter(
      (point) =>
        point.timeSeconds <
        firstPhysicsPoint.timeSeconds -
          0.0001,
    );

  const physicsPath = points.filter(
    (point) =>
      isPhysicsGeneratedPathPoint(point) &&
      point.timeSeconds >=
        firstPhysicsPoint.timeSeconds -
          0.0001,
  );

  const playback = sortMovementPathPoints([
    ...authoredBeforePhysics,
    ...physicsPath,
  ]);

  const result =
    playback.length >= 2
      ? playback
      : points;

  participantPlaybackPathCache.set(
    participant.pathPoints,
    result,
  );

  return result;
}

export function getParticipantRestPoint(
  participant: ReconstructionVehicle,
): MovementPathPoint | null {
  const points = sanitiseParticipantPathPoints(
    participant.pathPoints,
  );

  return (
    [...points]
      .reverse()
      .find(isObservedRestPoint) ??
    [...points]
      .reverse()
      .find(isPhysicsCalculatedRestPoint) ??
    null
  );
}

export function getPointsCentroid(
  points: ReconstructionPosition[],
): ReconstructionPosition {
  if (points.length === 0) {
    return { x: 50, y: 50 };
  }

  const total = points.reduce(
    (result, point) => ({
      x: result.x + point.x,
      y: result.y + point.y,
    }),
    { x: 0, y: 0 },
  );

  return {
    x: total.x / points.length,
    y: total.y / points.length,
  };
}

function deduplicateCurvePositions(
  positions: ReconstructionPosition[],
): ReconstructionPosition[] {
  const result: ReconstructionPosition[] = [];

  positions.forEach((position) => {
    const previous = result[result.length - 1];

    if (
      !previous ||
      distanceBetween(previous, position) > 0.03
    ) {
      result.push({
        x: clamp(position.x, 0, 100),
        y: clamp(position.y, 0, 100),
      });
    }
  });

  return result;
}

function getSmoothSegmentControls(
  points: ReconstructionPosition[],
  segmentIndex: number,
  smoothing: number,
  roadGraphControlled: boolean,
  turnSeverityDegrees: number,
): {
  controlOne: ReconstructionPosition;
  controlTwo: ReconstructionPosition;
} {
  const start = points[segmentIndex];
  const end = points[segmentIndex + 1];

  const previous =
    points[Math.max(0, segmentIndex - 1)];

  const following =
    points[
      Math.min(
        points.length - 1,
        segmentIndex + 2,
      )
    ];

  const segmentLength = Math.max(
    0.001,
    distanceBetween(start, end),
  );

  /*
   * The shared Catmull-Rom style tangent direction makes adjacent cubic
   * segments meet without a visible heading snap. Automatically generated
   * road routes use slightly shorter handles so the smoothed curve remains
   * close to the already road-valid centre-line samples.
   */
  const startTangent = normaliseVector(
    subtractPositions(end, previous),
    subtractPositions(end, start),
  );

  const endTangent = normaliseVector(
    subtractPositions(following, start),
    subtractPositions(end, start),
  );

  const previousLength = Math.max(
    0.001,
    distanceBetween(previous, start),
  );

  const nextLength = Math.max(
    0.001,
    distanceBetween(end, following),
  );

  const turnRatio = clamp(
    turnSeverityDegrees / 150,
    0,
    1,
  );

  const roadHandleScale =
    roadGraphControlled ? 0.72 : 1;

  const sharpTurnScale =
    interpolate(1, 0.72, turnRatio);

  const effectiveSmoothing =
    smoothing *
    roadHandleScale *
    sharpTurnScale;

  const controlOneDistance = Math.min(
    segmentLength * 0.38 * effectiveSmoothing,
    previousLength * 0.42,
    segmentLength * 0.46,
  );

  const controlTwoDistance = Math.min(
    segmentLength * 0.38 * effectiveSmoothing,
    nextLength * 0.42,
    segmentLength * 0.46,
  );

  const controlOne = addScaledVector(
    start,
    startTangent,
    controlOneDistance,
  );

  const controlTwo = addScaledVector(
    end,
    endTangent,
    -controlTwoDistance,
  );

  return {
    controlOne: {
      x: clamp(controlOne.x, 0, 100),
      y: clamp(controlOne.y, 0, 100),
    },
    controlTwo: {
      x: clamp(controlTwo.x, 0, 100),
      y: clamp(controlTwo.y, 0, 100),
    },
  };
}

function cubicBezierPoint(
  start: ReconstructionPosition,
  controlOne: ReconstructionPosition,
  controlTwo: ReconstructionPosition,
  end: ReconstructionPosition,
  progress: number,
): ReconstructionPosition {
  const inverse = 1 - progress;
  const inverseSquared = inverse * inverse;
  const progressSquared = progress * progress;

  return {
    x:
      inverseSquared * inverse * start.x +
      3 * inverseSquared * progress *
        controlOne.x +
      3 * inverse * progressSquared *
        controlTwo.x +
      progressSquared * progress * end.x,
    y:
      inverseSquared * inverse * start.y +
      3 * inverseSquared * progress *
        controlOne.y +
      3 * inverse * progressSquared *
        controlTwo.y +
      progressSquared * progress * end.y,
  };
}

function cubicBezierTangent(
  start: ReconstructionPosition,
  controlOne: ReconstructionPosition,
  controlTwo: ReconstructionPosition,
  end: ReconstructionPosition,
  progress: number,
): Vector2 {
  const inverse = 1 - progress;

  return {
    x:
      3 * inverse * inverse *
        (controlOne.x - start.x) +
      6 * inverse * progress *
        (controlTwo.x - controlOne.x) +
      3 * progress * progress *
        (end.x - controlTwo.x),
    y:
      3 * inverse * inverse *
        (controlOne.y - start.y) +
      6 * inverse * progress *
        (controlTwo.y - controlOne.y) +
      3 * progress * progress *
        (end.y - controlTwo.y),
  };
}

function createBezierArcLengthSamples(
  start: ReconstructionPosition,
  controlOne: ReconstructionPosition,
  controlTwo: ReconstructionPosition,
  end: ReconstructionPosition,
  turnSeverityDegrees: number,
  worldDimensions: MetricSceneDimensions,
): BezierArcLengthSample[] {
  const dimensions =
    normalisePlaybackWorldDimensions(
      worldDimensions,
    );

  const subdivisionCount = Math.round(
    interpolate(
      20,
      38,
      clamp(
        turnSeverityDegrees / 120,
        0,
        1,
      ),
    ),
  );

  const samples: BezierArcLengthSample[] = [
    {
      progress: 0,
      distance: 0,
    },
  ];

  let previous = start;
  let cumulativeDistance = 0;

  for (
    let index = 1;
    index <= subdivisionCount;
    index += 1
  ) {
    const progress =
      index / subdivisionCount;

    const position =
      cubicBezierPoint(
        start,
        controlOne,
        controlTwo,
        end,
        progress,
      );

    cumulativeDistance +=
      metricDistanceBetween(
        previous,
        position,
        dimensions,
      );

    samples.push({
      progress,
      distance: cumulativeDistance,
    });

    previous = position;
  }

  return samples;
}

function getBezierProgressAtDistanceFraction(
  samples: BezierArcLengthSample[],
  distanceFraction: number,
): number {
  if (samples.length < 2) {
    return clamp(distanceFraction, 0, 1);
  }

  const totalDistance =
    samples[samples.length - 1].distance;

  if (totalDistance < 0.000001) {
    return clamp(distanceFraction, 0, 1);
  }

  const targetDistance =
    clamp(distanceFraction, 0, 1) *
    totalDistance;

  let low = 0;
  let high = samples.length - 1;

  while (low + 1 < high) {
    const middle = Math.floor((low + high) / 2);

    if (
      samples[middle].distance <
      targetDistance
    ) {
      low = middle;
    } else {
      high = middle;
    }
  }

  const startSample = samples[low];
  const endSample = samples[high];
  const sampleDistance = Math.max(
    0.000001,
    endSample.distance -
      startSample.distance,
  );

  const sampleProgress = clamp(
    (targetDistance -
      startSample.distance) /
      sampleDistance,
    0,
    1,
  );

  return interpolate(
    startSample.progress,
    endSample.progress,
    sampleProgress,
  );
}

function getSmoothedBezierTangent(
  spline: SegmentMotionSpline,
  progress: number,
  worldDimensions: MetricSceneDimensions,
): Vector2 {
  const dimensions =
    normalisePlaybackWorldDimensions(
      worldDimensions,
    );

  const sampleWindow =
    spline.roadGraphControlled
      ? 0.025
      : 0.018;

  const before = normaliseVector(
    sceneVectorToMetres(
      cubicBezierTangent(
        spline.startPoint.position,
        spline.controlOne,
        spline.controlTwo,
        spline.endPoint.position,
        clamp(
          progress - sampleWindow,
          0,
          1,
        ),
      ),
      dimensions,
    ),
    spline.segmentDirection,
  );

  const current = normaliseVector(
    sceneVectorToMetres(
      cubicBezierTangent(
        spline.startPoint.position,
        spline.controlOne,
        spline.controlTwo,
        spline.endPoint.position,
        progress,
      ),
      dimensions,
    ),
    spline.segmentDirection,
  );

  const after = normaliseVector(
    sceneVectorToMetres(
      cubicBezierTangent(
        spline.startPoint.position,
        spline.controlOne,
        spline.controlTwo,
        spline.endPoint.position,
        clamp(
          progress + sampleWindow,
          0,
          1,
        ),
      ),
      dimensions,
    ),
    spline.segmentDirection,
  );

  return normaliseVector(
    {
      x:
        before.x * 0.2 +
        current.x * 0.6 +
        after.x * 0.2,

      y:
        before.y * 0.2 +
        current.y * 0.6 +
        after.y * 0.2,
    },
    current,
  );
}

function createSegmentMotionSpline(
  participant: ReconstructionVehicle,
  points: MovementPathPoint[],
  segmentIndex: number,
  worldDimensions: MetricSceneDimensions,
): SegmentMotionSpline {
  const dimensions =
    normalisePlaybackWorldDimensions(
      worldDimensions,
    );

  const profile =
    getMotionProfile(participant);

  const startPoint =
    points[segmentIndex];

  const endPoint =
    points[segmentIndex + 1];

  const previousPoint =
    points[
      Math.max(
        0,
        segmentIndex - 1,
      )
    ];

  const nextPoint =
    points[
      Math.min(
        points.length - 1,
        segmentIndex + 2,
      )
    ];

  const segmentVector =
    metricVectorBetween(
      endPoint.position,
      startPoint.position,
      dimensions,
    );

  const segmentLength =
    vectorLength(segmentVector);

  const segmentDirection =
    normaliseVector(
      segmentVector,
      {
        x: Math.cos(
          degreesToRadians(
            startPoint.rotation,
          ),
        ),

        y: Math.sin(
          degreesToRadians(
            startPoint.rotation,
          ),
        ),
      },
    );

  const incomingDirection =
    normaliseVector(
      metricVectorBetween(
        startPoint.position,
        previousPoint.position,
        dimensions,
      ),
      segmentDirection,
    );

  const outgoingDirection =
    normaliseVector(
      metricVectorBetween(
        nextPoint.position,
        endPoint.position,
        dimensions,
      ),
      segmentDirection,
    );

  let startTurnSeverityDegrees =
    angleDifferenceDegrees(
      incomingDirection,
      segmentDirection,
    );

  let endTurnSeverityDegrees =
    angleDifferenceDegrees(
      segmentDirection,
      outgoingDirection,
    );

  if (
    startPoint.action === "Turn Left" ||
    startPoint.action === "Turn Right"
  ) {
    startTurnSeverityDegrees =
      Math.max(
        startTurnSeverityDegrees,
        35,
      );
  }

  if (
    endPoint.action === "Turn Left" ||
    endPoint.action === "Turn Right"
  ) {
    endTurnSeverityDegrees =
      Math.max(
        endTurnSeverityDegrees,
        35,
      );
  }

  const physicsControlled =
    isPhysicsGeneratedPathPoint(startPoint) ||
    isPhysicsGeneratedPathPoint(endPoint) ||
    POST_IMPACT_ACTIONS.has(
      startPoint.action,
    );

  const roadGraphControlled =
    startPoint.notes?.includes(
      AUTO_ROAD_CURVE_NOTE_MARKER,
    ) === true ||
    endPoint.notes?.includes(
      AUTO_ROAD_CURVE_NOTE_MARKER,
    ) === true;

  /*
   * [RoadSafe:ManualBezierSplineV1]
   *
   * The segment mode lives on the start anchor. Physics-generated segments
   * remain authoritative/linear; otherwise an investigator-controlled Bezier
   * overrides automatic straight/wobble suppression.
   */
  const manualBezierControlled =
    startPoint
      .pathInterpolation ===
    "Bezier";

  const maximumTurnSeverity =
    Math.max(
      startTurnSeverityDegrees,
      endTurnSeverityDegrees,
    );

  const effectivelyStraight =
    maximumTurnSeverity <=
    profile.straightAngleTolerance;

  const deliberateCurveAction = [
    startPoint.action,
    endPoint.action,
  ].some(
    (action) =>
      action === "Turn Left" ||
      action === "Turn Right" ||
      action === "Swerve",
  );

  const routeWobbleTolerance =
    HUMAN_TYPES.has(participant.type)
      ? 9
      : 12;

  const looksLikeMinorRouteNoise =
    !roadGraphControlled &&
    !deliberateCurveAction &&
    maximumTurnSeverity <=
      routeWobbleTolerance;

  const linear =
    physicsControlled ||
    (
      !manualBezierControlled &&
      (
        effectivelyStraight ||
        looksLikeMinorRouteNoise
      )
    ) ||
    segmentLength < 0.001;

  if (linear) {
    return {
      linear: true,
      physicsControlled,
      roadGraphControlled,
      startPoint,
      endPoint,
      segmentDirection,
      controlOne:
        startPoint.position,

      controlTwo:
        endPoint.position,

      arcLengthSamples: [
        {
          progress: 0,
          distance: 0,
        },
        {
          progress: 1,
          distance: segmentLength,
        },
      ],

      startTurnSeverityDegrees,
      endTurnSeverityDegrees,
    };
  }

  const automaticControls =
    getSmoothSegmentControls(
      points.map(
        (point) =>
          point.position,
      ),
      segmentIndex,
      profile.curveTension,
      roadGraphControlled,
      maximumTurnSeverity,
    );

  const controls =
    manualBezierControlled
      ? {
          controlOne:
            startPoint.bezierOut
              ? {
                  x:
                    clamp(
                      startPoint
                        .bezierOut
                        .x,
                      0,
                      100,
                    ),
                  y:
                    clamp(
                      startPoint
                        .bezierOut
                        .y,
                      0,
                      100,
                    ),
                }
              : automaticControls
                  .controlOne,

          controlTwo:
            endPoint.bezierIn
              ? {
                  x:
                    clamp(
                      endPoint
                        .bezierIn
                        .x,
                      0,
                      100,
                    ),
                  y:
                    clamp(
                      endPoint
                        .bezierIn
                        .y,
                      0,
                      100,
                    ),
                }
              : automaticControls
                  .controlTwo,
        }
      : automaticControls;

  return {
    linear: false,
    physicsControlled,
    roadGraphControlled,
    startPoint,
    endPoint,
    segmentDirection,

    controlOne:
      controls.controlOne,

    controlTwo:
      controls.controlTwo,

    arcLengthSamples:
      createBezierArcLengthSamples(
        startPoint.position,
        controls.controlOne,
        controls.controlTwo,
        endPoint.position,
        maximumTurnSeverity,
        dimensions,
      ),

    startTurnSeverityDegrees,
    endTurnSeverityDegrees,
  };
}

function getParticipantMotionSplines(
  participant: ReconstructionVehicle,
  points: MovementPathPoint[],
  worldDimensions?: MetricSceneDimensions,
): SegmentMotionSpline[] {
  const dimensions =
    normalisePlaybackWorldDimensions(
      worldDimensions,
    );

  let dimensionCache =
    participantMotionSplineCache.get(
      points,
    );

  if (!dimensionCache) {
    dimensionCache =
      new Map();

    participantMotionSplineCache.set(
      points,
      dimensionCache,
    );
  }

  const cacheKey =
    metricSplineCacheKey(
      participant,
      dimensions,
    );

  const cached =
    dimensionCache.get(
      cacheKey,
    );

  if (cached) {
    return cached;
  }

  const splines =
    Array.from(
      {
        length:
          Math.max(
            0,
            points.length - 1,
          ),
      },
      (_, index) =>
        createSegmentMotionSpline(
          participant,
          points,
          index,
          dimensions,
        ),
    );

  dimensionCache.set(
    cacheKey,
    splines,
  );

  return splines;
}

/*
 * [RoadSafe:CanonicalMetricPlaybackSegmentLengthsV1]
 *
 * Provides authoring controls with the exact same metric spline lengths used
 * by 2D, 3D, AR, exported frames and physics state sampling.
 */
export function getParticipantMetricPlaybackSegmentLengthsMetres(
  participant: ReconstructionVehicle,
  points: MovementPathPoint[],
  worldDimensions?: MetricSceneDimensions,
): number[] {
  const dimensions =
    normalisePlaybackWorldDimensions(
      worldDimensions,
    );

  return getParticipantMotionSplines(
    participant,
    points,
    dimensions,
  ).map(
    (spline) =>
      Math.max(
        0,
        spline.arcLengthSamples[
          spline.arcLengthSamples.length -
            1
        ]?.distance ?? 0,
      ),
  );
}

function getSegmentMotionGeometry(
  participant: ReconstructionVehicle,
  points: MovementPathPoint[],
  segmentIndex: number,
  distanceProgress: number,
  worldDimensions?: MetricSceneDimensions,
): SegmentMotionGeometry {
  const dimensions =
    normalisePlaybackWorldDimensions(
      worldDimensions,
    );

  const splines =
    getParticipantMotionSplines(
      participant,
      points,
      dimensions,
    );

  const spline =
    splines[segmentIndex];

  if (!spline) {
    const startPoint =
      points[segmentIndex];

    const endPoint =
      points[segmentIndex + 1] ??
      startPoint;

    const direction =
      metricDirectionBetween(
        endPoint.position,
        startPoint.position,
        dimensions,
      );

    return {
      position:
        startPoint.position,

      tangent:
        direction,

      turnSeverityDegrees:
        0,
    };
  }

  const localTurnSeverity =
    interpolate(
      spline.startTurnSeverityDegrees,
      spline.endTurnSeverityDegrees,
      smoothStep(
        distanceProgress,
      ),
    );

  if (spline.linear) {
    return {
      position: {
        x:
          interpolate(
            spline.startPoint.position.x,
            spline.endPoint.position.x,
            distanceProgress,
          ),

        y:
          interpolate(
            spline.startPoint.position.y,
            spline.endPoint.position.y,
            distanceProgress,
          ),
      },

      tangent:
        spline.segmentDirection,

      turnSeverityDegrees:
        localTurnSeverity,
    };
  }

  const curveProgress =
    getBezierProgressAtDistanceFraction(
      spline.arcLengthSamples,
      distanceProgress,
    );

  return {
    position:
      cubicBezierPoint(
        spline.startPoint.position,
        spline.controlOne,
        spline.controlTwo,
        spline.endPoint.position,
        curveProgress,
      ),

    tangent:
      getSmoothedBezierTangent(
        spline,
        curveProgress,
        dimensions,
      ),

    turnSeverityDegrees:
      localTurnSeverity,
  };
}

function getCanonicalPlaybackSpeedKmh(
  participant: ReconstructionVehicle,
  requestedSpeedKmh: number,
  action: MovementAction,
): number {
  const profile =
    getMotionProfile(participant);

  let speed =
    Math.max(
      0,
      requestedSpeedKmh,
    );

  /*
   * A participant's returned speed must describe the same progress used to
   * calculate its position. Corner losses are therefore not applied as a
   * second display-only multiplier. Investigators express actual braking or
   * corner speed changes through the authored point speeds and timestamps.
   */
  if (
    profile.maximumWalkingSpeedKmh !== null &&
    action !== "Accelerate"
  ) {
    speed =
      Math.min(
        speed,
        profile.maximumWalkingSpeedKmh,
      );
  }

  return speed;
}

function applyHumanWalkingMotion(
  participant: ReconstructionVehicle,
  position: ReconstructionPosition,
  headingDegrees: number,
  speedKmh: number,
  currentTime: number,
  action: MovementAction,
  physicsControlled: boolean,
): {
  position: ReconstructionPosition;
  rotation: number;
} {
  if (
    !HUMAN_TYPES.has(participant.type) ||
    physicsControlled ||
    POST_IMPACT_ACTIONS.has(action) ||
    speedKmh < 0.7
  ) {
    return {
      position,
      rotation: headingDegrees,
    };
  }

  const profile = getMotionProfile(participant);

  const walkingRatio = clamp(
    speedKmh / 6.5,
    0.25,
    1,
  );

  const cadenceHz = interpolate(
    1.35,
    1.85,
    walkingRatio,
  );

  const phase =
    currentTime * cadenceHz * Math.PI * 2;

  const lateralSway =
    Math.sin(phase) *
    profile.gaitSwayScenePercent *
    walkingRatio;

  const headingRadians =
    degreesToRadians(headingDegrees);

  const perpendicular = {
    x: -Math.sin(headingRadians),
    y: Math.cos(headingRadians),
  };

  return {
    position: {
      x: clamp(
        position.x +
          perpendicular.x * lateralSway,
        0,
        100,
      ),
      y: clamp(
        position.y +
          perpendicular.y * lateralSway,
        0,
        100,
      ),
    },
    rotation:
      headingDegrees +
      Math.sin(phase) *
        profile.gaitRotationDegrees *
        walkingRatio,
  };
}

export function getParticipantStateAtTime(
  participant: ReconstructionVehicle,
  currentTime: number,
  worldDimensions?: MetricSceneDimensions,
): {
  position: ReconstructionPosition;
  rotation: number;
  speedKmh: number;
  activePointId: string;
} {
  const dimensions =
    normalisePlaybackWorldDimensions(
      worldDimensions,
    );

  const points =
    getParticipantPlaybackPathPoints(
      participant,
    );

  if (points.length === 0) {
    return {
      position:
        participant.startPosition,

      rotation:
        participant.startRotation,

      speedKmh:
        participant.estimatedSpeedKmh,

      activePointId:
        "",
    };
  }

  if (
    currentTime <=
    points[0].timeSeconds
  ) {
    const first =
      points[0];

    const next =
      points[1] ??
      first;

    const fallbackTangent =
      metricDirectionBetween(
        next.position,
        first.position,
        dimensions,
        {
          x:
            Math.cos(
              degreesToRadians(
                first.rotation,
              ),
            ),

          y:
            Math.sin(
              degreesToRadians(
                first.rotation,
              ),
            ),
        },
      );

    const tangent =
      points.length >= 2
        ? getSegmentMotionGeometry(
            participant,
            points,
            0,
            0,
            dimensions,
          ).tangent
        : fallbackTangent;

    const heading =
      angleFromVector(
        tangent,
      );

    const speedKmh =
      first.action === "Stop"
        ? 0
        : getCanonicalPlaybackSpeedKmh(
            participant,
            first.speedKmh,
            first.action,
          );

    const walkingMotion =
      applyHumanWalkingMotion(
        participant,
        first.position,
        heading,
        speedKmh,
        currentTime,
        first.action,
        isPhysicsGeneratedPathPoint(
          first,
        ),
      );

    return {
      position:
        walkingMotion.position,

      rotation:
        walkingMotion.rotation,

      speedKmh,

      activePointId:
        first.id,
    };
  }

  const finalPoint =
    points[
      points.length - 1
    ];

  if (
    currentTime >=
    finalPoint.timeSeconds
  ) {
    const previous =
      points[
        Math.max(
          0,
          points.length - 2,
        )
      ];

    const fallbackTangent =
      metricDirectionBetween(
        finalPoint.position,
        previous.position,
        dimensions,
        {
          x:
            Math.cos(
              degreesToRadians(
                finalPoint.rotation,
              ),
            ),

          y:
            Math.sin(
              degreesToRadians(
                finalPoint.rotation,
              ),
            ),
        },
      );

    const tangent =
      points.length >= 2
        ? getSegmentMotionGeometry(
            participant,
            points,
            points.length - 2,
            1,
            dimensions,
          ).tangent
        : fallbackTangent;

    const physicsControlled =
      isPhysicsGeneratedPathPoint(
        finalPoint,
      ) ||
      POST_IMPACT_ACTIONS.has(
        finalPoint.action,
      );

    const heading =
      physicsControlled
        ? finalPoint.rotation
        : angleFromVector(
            tangent,
          );

    const speedKmh =
      finalPoint.action === "Stop"
        ? 0
        : getCanonicalPlaybackSpeedKmh(
            participant,
            finalPoint.speedKmh,
            finalPoint.action,
          );

    const walkingMotion =
      applyHumanWalkingMotion(
        participant,
        finalPoint.position,
        heading,
        speedKmh,
        currentTime,
        finalPoint.action,
        physicsControlled,
      );

    return {
      position:
        walkingMotion.position,

      rotation:
        walkingMotion.rotation,

      speedKmh,

      activePointId:
        finalPoint.id,
    };
  }

  const segmentIndex =
    points.findIndex(
      (point, index) =>
        index <
          points.length - 1 &&
        currentTime >=
          point.timeSeconds &&
        currentTime <=
          points[index + 1]
            .timeSeconds,
    );

  const safeIndex =
    Math.max(
      0,
      segmentIndex,
    );

  const start =
    points[safeIndex];

  const end =
    points[safeIndex + 1];

  const duration =
    Math.max(
      end.timeSeconds -
        start.timeSeconds,
      0.001,
    );

  const timeProgress =
    clamp(
      (
        currentTime -
        start.timeSeconds
      ) /
        duration,
      0,
      1,
    );

  const positionProgress =
    getKinematicPositionProgress(
      participant,
      start,
      end,
      timeProgress,
    );

  const geometry =
    getSegmentMotionGeometry(
      participant,
      points,
      safeIndex,
      positionProgress,
      dimensions,
    );

  const physicsControlled =
    isPhysicsGeneratedPathPoint(
      start,
    ) ||
    isPhysicsGeneratedPathPoint(
      end,
    ) ||
    POST_IMPACT_ACTIONS.has(
      start.action,
    );

  const pathHeading =
    angleFromVector(
      geometry.tangent,
    );

  const physicsRotation =
    interpolateAngle(
      start.rotation,
      end.rotation,
      smootherStep(
        positionProgress,
      ),
    );

  let rotation =
    physicsControlled
      ? physicsRotation
      : pathHeading;

  if (
    physicsControlled &&
    safeIndex > 0 &&
    POST_IMPACT_ACTIONS.has(
      start.action,
    ) &&
    positionProgress < 0.16
  ) {
    const previousGeometry =
      getSegmentMotionGeometry(
        participant,
        points,
        safeIndex - 1,
        1,
        dimensions,
      );

    const previousHeading =
      angleFromVector(
        previousGeometry.tangent,
      );

    rotation =
      interpolateAngle(
        previousHeading,
        physicsRotation,
        smootherStep(
          positionProgress /
            0.16,
        ),
      );
  }

  const canonicalStartSpeed =
    start.action === "Stop"
      ? 0
      : getCanonicalPlaybackSpeedKmh(
          participant,
          start.speedKmh,
          start.action,
        );

  const canonicalEndSpeed =
    end.action === "Stop"
      ? 0
      : getCanonicalPlaybackSpeedKmh(
          participant,
          end.speedKmh,
          end.action,
        );

  const speedKmh =
    getSmoothKinematicSpeedKmh(
      canonicalStartSpeed,
      canonicalEndSpeed,
      timeProgress,
    );

  const activeAction =
    timeProgress < 0.5
      ? start.action
      : end.action;

  const walkingMotion =
    applyHumanWalkingMotion(
      participant,
      geometry.position,
      rotation,
      speedKmh,
      currentTime,
      activeAction,
      physicsControlled,
    );

  return {
    position:
      walkingMotion.position,

    rotation:
      walkingMotion.rotation,

    speedKmh,

    activePointId:
      timeProgress < 0.5
        ? start.id
        : end.id,
  };
}

export function getReconstructionImpactEffectState(
  reconstruction: AccidentReconstruction,
  currentTime: number,
): ReconstructionImpactEffectState {
  const participantCollisionEvent =
    reconstruction.lastPhysicsSimulation
      ?.collisionEvents
      .filter(
        (event) =>
          event.type === "Participant-Participant",
      )
      .sort(
        (left, right) =>
          left.timeSeconds - right.timeSeconds,
      )[0];

  const impactPoints =
    reconstruction.vehicles
      .map((participant) =>
        sanitiseParticipantPathPoints(
          participant.pathPoints,
        ).find(
          (point) =>
            point.action === "Impact",
        ),
      )
      .filter(
        (
          point,
        ): point is MovementPathPoint =>
          Boolean(point),
      );

  const fallbackTime = impactPoints.length
    ? [...impactPoints].sort(
        (left, right) =>
          left.timeSeconds -
          right.timeSeconds,
      )[
        Math.floor(impactPoints.length / 2)
      ].timeSeconds
    : reconstruction.durationSeconds / 2;

  const impactTimeSeconds =
    participantCollisionEvent?.timeSeconds ??
    fallbackTime;

  const showImpactEffects =
    reconstruction.physicsSettings
      ?.showImpactEffects ?? true;

  const elapsed =
    currentTime - impactTimeSeconds;

  const effectDuration = 1.05;

  const energy =
    participantCollisionEvent
      ?.estimatedEnergyKj ??
    reconstruction.lastPhysicsSimulation
      ?.estimatedImpactEnergyKj ??
    0;

  const fallbackSpeed = Math.max(
    0,
    ...impactPoints.map(
      (point) => point.speedKmh,
    ),
  );

  return {
    active:
      showImpactEffects &&
      Boolean(participantCollisionEvent) &&
      elapsed >= 0 &&
      elapsed <= effectDuration,
    impactTimeSeconds,
    intensity: clamp(
      energy > 0
        ? 0.6 +
            Math.log10(1 + energy) / 3
        : 0.55 + fallbackSpeed / 140,
      0.55,
      1.35,
    ),
    position:
      participantCollisionEvent
        ?.contactPoint ??
      reconstruction.collisionPoint,
    participantIds:
      participantCollisionEvent
        ?.participantIds ?? [],
    progress: clamp(
      elapsed / effectDuration,
      0,
      1,
    ),
  };
}

export function buildSmoothSvgPath(
  positions: ReconstructionPosition[],
  smoothing = 0.88,
): string {
  const points = deduplicateCurvePositions(
    positions,
  );

  if (points.length === 0) {
    return "";
  }

  if (points.length === 1) {
    return `M ${points[0].x} ${points[0].y}`;
  }

  if (points.length === 2) {
    return (
      `M ${points[0].x} ${points[0].y} ` +
      `L ${points[1].x} ${points[1].y}`
    );
  }

  const normalisedSmoothing = clamp(
    smoothing,
    0.35,
    1,
  );

  let path =
    `M ${points[0].x} ${points[0].y}`;

  for (
    let index = 0;
    index < points.length - 1;
    index += 1
  ) {
    const controls = getSmoothSegmentControls(
      points,
      index,
      normalisedSmoothing,
      false,
      0,
    );

    const end = points[index + 1];

    path +=
      ` C ${controls.controlOne.x} ${controls.controlOne.y}, ` +
      `${controls.controlTwo.x} ${controls.controlTwo.y}, ` +
      `${end.x} ${end.y}`;
  }

  return path;
}

export function createOffsetTracePoints(
  points: ReconstructionPosition[],
  offset: number,
): ReconstructionPosition[] {
  if (points.length < 2) {
    return points;
  }

  return points.map((point, index) => {
    const previous =
      points[Math.max(0, index - 1)];

    const next =
      points[
        Math.min(points.length - 1, index + 1)
      ];

    const directionX = next.x - previous.x;
    const directionY = next.y - previous.y;

    const length =
      Math.hypot(directionX, directionY) || 1;

    return {
      x: clamp(
        point.x +
          (-directionY / length) * offset,
        0,
        100,
      ),
      y: clamp(
        point.y +
          (directionX / length) * offset,
        0,
        100,
      ),
    };
  });
}

export function isTraceableSceneObjectType(
  type: SceneObjectType,
): boolean {
  return (
    type === "Skid Mark" ||
    type === "Tyre Mark" ||
    type === "Road Crack"
  );
}

export function shiftSceneObjectTrace(
  object: ReconstructionSceneObject,
  nextPosition: ReconstructionPosition,
): ReconstructionPosition[] | undefined {
  if (
    !object.tracePoints ||
    object.tracePoints.length === 0
  ) {
    return object.tracePoints;
  }

  const differenceX =
    nextPosition.x - object.position.x;

  const differenceY =
    nextPosition.y - object.position.y;

  return object.tracePoints.map((point) => ({
    x: clamp(
      point.x + differenceX,
      0,
      100,
    ),
    y: clamp(
      point.y + differenceY,
      0,
      100,
    ),
  }));
}

export function syncLegacyParticipantFields(
  participant: ReconstructionVehicle,
): ReconstructionVehicle {
  const points = sanitiseParticipantPathPoints(
    participant.pathPoints,
  );

  if (points.length === 0) {
    return {
      ...participant,
      pathPoints: [],
    };
  }

  const start = points[0];

  const impact =
    points.find(
      (point) => point.action === "Impact",
    ) ??
    points[Math.floor(points.length / 2)];

  const restPoint =
    [...points]
      .reverse()
      .find(isObservedRestPoint) ??
    [...points]
      .reverse()
      .find(isPhysicsCalculatedRestPoint) ??
    null;

  const legacyFinal = restPoint ?? impact;

  return {
    ...participant,
    pathPoints: points,
    startPosition: start.position,
    collisionPosition: impact.position,
    finalPosition: legacyFinal.position,
    startRotation: start.rotation,
    collisionRotation: impact.rotation,
    finalRotation: legacyFinal.rotation,
    collisionTimeSeconds: impact.timeSeconds,
    estimatedSpeedKmh: start.speedKmh,
  };
}
