import type {
  AccidentReconstruction,
  MovementAction,
  MovementPathPoint,
  ReconstructionPosition,
  ReconstructionSceneObject,
  ReconstructionVehicle,
  SceneObjectType,
} from "../types/reconstruction";

export interface ReconstructionImpactEffectState {
  active: boolean;
  impactTimeSeconds: number;
  intensity: number;
  position: ReconstructionPosition;
  progress: number;
}

interface Vector2 {
  x: number;
  y: number;
}

interface ParticipantMotionProfile {
  curveTension: number;
  straightAngleTolerance: number;
  cornerSpeedLoss: number;
  maximumWalkingSpeedKmh: number | null;
  gaitSwayScenePercent: number;
  gaitRotationDegrees: number;
}

interface SegmentMotionGeometry {
  position: ReconstructionPosition;
  tangent: Vector2;
  turnSeverityDegrees: number;
}

const HUMAN_TYPES = new Set<
  ReconstructionVehicle["type"]
>([
  "Pedestrian",
  "Officer",
  "Witness",
]);

const PHYSICS_POINT_PREFIXES = [
  "physics-point-",
  "detected-impact-",
  "physics-transition-",
  "legacy-impact-",
] as const;

const PHYSICS_NOTE_MARKERS = [
  "Generated by the RoadSafe deterministic 2D physics preview.",
  "Generated at the first swept body contact found along the participant routes.",
  "Physics takes over from the participant's guided route",
  "Physics-generated event.",
] as const;

const PLACEHOLDER_REST_LABELS = new Set([
  "final position",
  "final resting position",
  "rest position",
  "natural stop",
]);

const POST_IMPACT_ACTIONS = new Set<MovementAction>([
  "Impact",
  "Ricochet",
  "Deflect",
  "Slide",
  "Fall",
  "Stop",
]);

export function clamp(
  value: number,
  minimum: number,
  maximum: number,
): number {
  return Math.min(
    maximum,
    Math.max(minimum, value),
  );
}

export function interpolate(
  start: number,
  end: number,
  progress: number,
): number {
  return start + (end - start) * progress;
}

function interpolateAngle(
  start: number,
  end: number,
  progress: number,
): number {
  const difference =
    ((end - start + 540) % 360) - 180;

  return start + difference * progress;
}

function degreesToRadians(
  degrees: number,
): number {
  return (degrees * Math.PI) / 180;
}

function vectorLength(
  vector: Vector2,
): number {
  return Math.hypot(vector.x, vector.y);
}

function subtractPositions(
  end: ReconstructionPosition,
  start: ReconstructionPosition,
): Vector2 {
  return {
    x: end.x - start.x,
    y: end.y - start.y,
  };
}

function normaliseVector(
  vector: Vector2,
  fallback: Vector2 = { x: 1, y: 0 },
): Vector2 {
  const length = vectorLength(vector);

  if (length < 0.000001) {
    const fallbackLength =
      vectorLength(fallback) || 1;

    return {
      x: fallback.x / fallbackLength,
      y: fallback.y / fallbackLength,
    };
  }

  return {
    x: vector.x / length,
    y: vector.y / length,
  };
}

function angleFromVector(
  vector: Vector2,
): number {
  return (
    (Math.atan2(vector.y, vector.x) * 180) /
      Math.PI +
    360
  ) % 360;
}

function angleDifferenceDegrees(
  first: Vector2,
  second: Vector2,
): number {
  const firstUnit = normaliseVector(first);
  const secondUnit = normaliseVector(second);

  const dot = clamp(
    firstUnit.x * secondUnit.x +
      firstUnit.y * secondUnit.y,
    -1,
    1,
  );

  return (Math.acos(dot) * 180) / Math.PI;
}

function distanceBetween(
  first: ReconstructionPosition,
  second: ReconstructionPosition,
): number {
  return Math.hypot(
    second.x - first.x,
    second.y - first.y,
  );
}

function addScaledVector(
  position: ReconstructionPosition,
  direction: Vector2,
  distance: number,
): ReconstructionPosition {
  return {
    x: position.x + direction.x * distance,
    y: position.y + direction.y * distance,
  };
}

function getMotionProfile(
  participant: ReconstructionVehicle,
): ParticipantMotionProfile {
  switch (participant.type) {
    case "Bus":
      return {
        curveTension: 0.52,
        straightAngleTolerance: 4,
        cornerSpeedLoss: 0.52,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };

    case "Truck":
      return {
        curveTension: 0.48,
        straightAngleTolerance: 4,
        cornerSpeedLoss: 0.48,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };

    case "Motorcycle":
      return {
        curveTension: 0.74,
        straightAngleTolerance: 5,
        cornerSpeedLoss: 0.24,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };

    case "Bicycle":
      return {
        curveTension: 0.78,
        straightAngleTolerance: 6,
        cornerSpeedLoss: 0.28,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };

    case "Pedestrian":
    case "Officer":
    case "Witness":
      return {
        curveTension: 0.86,
        straightAngleTolerance: 8,
        cornerSpeedLoss: 0.08,
        maximumWalkingSpeedKmh: 6.5,
        gaitSwayScenePercent: 0.11,
        gaitRotationDegrees: 1.6,
      };

    case "Car":
    default:
      return {
        curveTension: 0.64,
        straightAngleTolerance: 4,
        cornerSpeedLoss: 0.34,
        maximumWalkingSpeedKmh: null,
        gaitSwayScenePercent: 0,
        gaitRotationDegrees: 0,
      };
  }
}

function getKinematicPositionProgress(
  start: MovementPathPoint,
  end: MovementPathPoint,
  timeProgress: number,
): number {
  const startSpeed =
    start.action === "Stop"
      ? 0
      : Math.max(0, start.speedKmh);

  const endSpeed =
    end.action === "Stop"
      ? 0
      : Math.max(0, end.speedKmh);

  const averageSpeed =
    (startSpeed + endSpeed) / 2;

  if (averageSpeed < 0.01) {
    return (
      timeProgress *
      timeProgress *
      (3 - 2 * timeProgress)
    );
  }

  const distanceFraction =
    (startSpeed * timeProgress +
      0.5 *
        (endSpeed - startSpeed) *
        timeProgress *
        timeProgress) /
    averageSpeed;

  return clamp(distanceFraction, 0, 1);
}

export function sortMovementPathPoints(
  points: MovementPathPoint[],
): MovementPathPoint[] {
  return [...points].sort(
    (first, second) =>
      first.timeSeconds - second.timeSeconds,
  );
}

export function isPhysicsGeneratedPathPoint(
  point: MovementPathPoint,
): boolean {
  return (
    PHYSICS_POINT_PREFIXES.some((prefix) =>
      point.id.startsWith(prefix),
    ) ||
    PHYSICS_NOTE_MARKERS.some((marker) =>
      point.notes?.includes(marker),
    )
  );
}

export function isPhysicsCalculatedRestPoint(
  point: MovementPathPoint,
): boolean {
  return (
    point.action === "Stop" &&
    isPhysicsGeneratedPathPoint(point)
  );
}

export function isUnverifiedAutoRestPoint(
  point: MovementPathPoint,
): boolean {
  if (point.action !== "Stop") {
    return false;
  }

  const label =
    point.label.trim().toLowerCase();

  const placeholderId =
    point.id.startsWith("path-stop-") ||
    point.id.startsWith("path-final-");

  const placeholderLabel =
    PLACEHOLDER_REST_LABELS.has(label);

  const hasInvestigatorEvidence =
    Boolean(point.linkedSceneObjectId) ||
    Boolean(point.notes?.trim());

  return (
    placeholderId &&
    placeholderLabel &&
    !hasInvestigatorEvidence &&
    !isPhysicsGeneratedPathPoint(point)
  );
}

export function isObservedRestPoint(
  point: MovementPathPoint,
): boolean {
  return (
    point.action === "Stop" &&
    !isPhysicsGeneratedPathPoint(point) &&
    !isUnverifiedAutoRestPoint(point)
  );
}

function samePosition(
  left: ReconstructionPosition,
  right: ReconstructionPosition,
): boolean {
  return (
    Math.abs(left.x - right.x) <= 0.0001 &&
    Math.abs(left.y - right.y) <= 0.0001
  );
}

function areDuplicatePoints(
  left: MovementPathPoint,
  right: MovementPathPoint,
): boolean {
  return (
    Math.abs(
      left.timeSeconds - right.timeSeconds,
    ) <= 0.0001 &&
    left.action === right.action &&
    samePosition(left.position, right.position) &&
    Math.abs(left.rotation - right.rotation) <=
      0.0001
  );
}

function isUnverifiedRouteContinuationPoint(
  point: MovementPathPoint,
  impactTimeSeconds: number | null,
): boolean {
  if (
    impactTimeSeconds === null ||
    point.timeSeconds <= impactTimeSeconds
  ) {
    return false;
  }

  if (
    isPhysicsGeneratedPathPoint(point) ||
    isObservedRestPoint(point)
  ) {
    return false;
  }

  const label =
    point.label.trim().toLowerCase();

  const looksLikeAutoRouteSample =
    /^route \d+$/.test(label) ||
    label === "natural stop";

  const hasInvestigatorEvidence =
    Boolean(point.linkedSceneObjectId) ||
    Boolean(point.notes?.trim());

  return (
    point.id.startsWith("path-point-") &&
    looksLikeAutoRouteSample &&
    !hasInvestigatorEvidence
  );
}

export function sanitiseParticipantPathPoints(
  points: MovementPathPoint[],
): MovementPathPoint[] {
  const sorted = sortMovementPathPoints(points);

  const firstAuthoredImpact = sorted.find(
    (point) =>
      point.action === "Impact" &&
      !isPhysicsGeneratedPathPoint(point),
  );

  const impactTimeSeconds =
    firstAuthoredImpact?.timeSeconds ?? null;

  const withoutUnverifiedGeneratedRoute =
    sorted.filter(
      (point) =>
        !isUnverifiedAutoRestPoint(point) &&
        !isUnverifiedRouteContinuationPoint(
          point,
          impactTimeSeconds,
        ),
    );

  const deduplicated =
    withoutUnverifiedGeneratedRoute.filter(
      (point, index, list) =>
        index === 0 ||
        !areDuplicatePoints(
          list[index - 1],
          point,
        ),
    );

  const hasImpact = deduplicated.some(
    (point) => point.action === "Impact",
  );

  if (
    deduplicated.length >= 2 &&
    hasImpact
  ) {
    return deduplicated;
  }

  return sorted;
}

export function getInvestigatorPathPoints(
  participant: ReconstructionVehicle,
): MovementPathPoint[] {
  return sanitiseParticipantPathPoints(
    participant.pathPoints,
  ).filter(
    (point) =>
      !isPhysicsGeneratedPathPoint(point),
  );
}

export function getPhysicsPathPoints(
  participant: ReconstructionVehicle,
): MovementPathPoint[] {
  return sanitiseParticipantPathPoints(
    participant.pathPoints,
  ).filter(isPhysicsGeneratedPathPoint);
}

export function getParticipantRestPoint(
  participant: ReconstructionVehicle,
): MovementPathPoint | null {
  const points = sanitiseParticipantPathPoints(
    participant.pathPoints,
  );

  return (
    [...points]
      .reverse()
      .find(isObservedRestPoint) ??
    [...points]
      .reverse()
      .find(isPhysicsCalculatedRestPoint) ??
    null
  );
}

export function getPointsCentroid(
  points: ReconstructionPosition[],
): ReconstructionPosition {
  if (points.length === 0) {
    return { x: 50, y: 50 };
  }

  const total = points.reduce(
    (result, point) => ({
      x: result.x + point.x,
      y: result.y + point.y,
    }),
    { x: 0, y: 0 },
  );

  return {
    x: total.x / points.length,
    y: total.y / points.length,
  };
}

function deduplicateCurvePositions(
  positions: ReconstructionPosition[],
): ReconstructionPosition[] {
  const result: ReconstructionPosition[] = [];

  positions.forEach((position) => {
    const previous = result[result.length - 1];

    if (
      !previous ||
      distanceBetween(previous, position) > 0.03
    ) {
      result.push({
        x: clamp(position.x, 0, 100),
        y: clamp(position.y, 0, 100),
      });
    }
  });

  return result;
}

function getSmoothSegmentControls(
  points: ReconstructionPosition[],
  segmentIndex: number,
  smoothing: number,
): {
  controlOne: ReconstructionPosition;
  controlTwo: ReconstructionPosition;
} {
  const start = points[segmentIndex];
  const end = points[segmentIndex + 1];

  const previous =
    points[Math.max(0, segmentIndex - 1)];

  const following =
    points[
      Math.min(
        points.length - 1,
        segmentIndex + 2,
      )
    ];

  const segmentLength = Math.max(
    0.001,
    distanceBetween(start, end),
  );

  const incomingDirection = normaliseVector(
    subtractPositions(end, previous),
    subtractPositions(end, start),
  );

  const outgoingDirection = normaliseVector(
    subtractPositions(following, start),
    subtractPositions(end, start),
  );

  const previousLength = Math.max(
    0.001,
    distanceBetween(previous, start),
  );

  const nextLength = Math.max(
    0.001,
    distanceBetween(end, following),
  );

  const controlOneDistance = Math.min(
    segmentLength * 0.42 * smoothing,
    previousLength * 0.5,
  );

  const controlTwoDistance = Math.min(
    segmentLength * 0.42 * smoothing,
    nextLength * 0.5,
  );

  const controlOne = addScaledVector(
    start,
    incomingDirection,
    controlOneDistance,
  );

  const controlTwo = addScaledVector(
    end,
    outgoingDirection,
    -controlTwoDistance,
  );

  return {
    controlOne: {
      x: clamp(controlOne.x, 0, 100),
      y: clamp(controlOne.y, 0, 100),
    },
    controlTwo: {
      x: clamp(controlTwo.x, 0, 100),
      y: clamp(controlTwo.y, 0, 100),
    },
  };
}

function cubicBezierPoint(
  start: ReconstructionPosition,
  controlOne: ReconstructionPosition,
  controlTwo: ReconstructionPosition,
  end: ReconstructionPosition,
  progress: number,
): ReconstructionPosition {
  const inverse = 1 - progress;
  const inverseSquared = inverse * inverse;
  const progressSquared = progress * progress;

  return {
    x:
      inverseSquared * inverse * start.x +
      3 * inverseSquared * progress *
        controlOne.x +
      3 * inverse * progressSquared *
        controlTwo.x +
      progressSquared * progress * end.x,
    y:
      inverseSquared * inverse * start.y +
      3 * inverseSquared * progress *
        controlOne.y +
      3 * inverse * progressSquared *
        controlTwo.y +
      progressSquared * progress * end.y,
  };
}

function cubicBezierTangent(
  start: ReconstructionPosition,
  controlOne: ReconstructionPosition,
  controlTwo: ReconstructionPosition,
  end: ReconstructionPosition,
  progress: number,
): Vector2 {
  const inverse = 1 - progress;

  return {
    x:
      3 * inverse * inverse *
        (controlOne.x - start.x) +
      6 * inverse * progress *
        (controlTwo.x - controlOne.x) +
      3 * progress * progress *
        (end.x - controlTwo.x),
    y:
      3 * inverse * inverse *
        (controlOne.y - start.y) +
      6 * inverse * progress *
        (controlTwo.y - controlOne.y) +
      3 * progress * progress *
        (end.y - controlTwo.y),
  };
}

function getSegmentMotionGeometry(
  participant: ReconstructionVehicle,
  points: MovementPathPoint[],
  segmentIndex: number,
  progress: number,
): SegmentMotionGeometry {
  const profile = getMotionProfile(participant);

  const startPoint = points[segmentIndex];
  const endPoint = points[segmentIndex + 1];

  const previousPoint =
    points[Math.max(0, segmentIndex - 1)];

  const nextPoint =
    points[
      Math.min(
        points.length - 1,
        segmentIndex + 2,
      )
    ];

  const segmentVector = subtractPositions(
    endPoint.position,
    startPoint.position,
  );

  const segmentLength = vectorLength(segmentVector);
  const segmentDirection = normaliseVector(
    segmentVector,
  );

  const incomingDirection = normaliseVector(
    subtractPositions(
      startPoint.position,
      previousPoint.position,
    ),
    segmentDirection,
  );

  const outgoingDirection = normaliseVector(
    subtractPositions(
      nextPoint.position,
      endPoint.position,
    ),
    segmentDirection,
  );

  const startTurnSeverity =
    angleDifferenceDegrees(
      incomingDirection,
      segmentDirection,
    );

  const endTurnSeverity =
    angleDifferenceDegrees(
      segmentDirection,
      outgoingDirection,
    );

  const hasExplicitTurn =
    startPoint.action === "Turn Left" ||
    startPoint.action === "Turn Right" ||
    endPoint.action === "Turn Left" ||
    endPoint.action === "Turn Right";

  const turnSeverityDegrees = Math.max(
    startTurnSeverity,
    endTurnSeverity,
    hasExplicitTurn ? 35 : 0,
  );

  const physicsControlled =
    isPhysicsGeneratedPathPoint(startPoint) ||
    isPhysicsGeneratedPathPoint(endPoint) ||
    POST_IMPACT_ACTIONS.has(startPoint.action);

  const effectivelyStraight =
    turnSeverityDegrees <=
    profile.straightAngleTolerance;

  if (
    physicsControlled ||
    effectivelyStraight ||
    segmentLength < 0.001
  ) {
    return {
      position: {
        x: interpolate(
          startPoint.position.x,
          endPoint.position.x,
          progress,
        ),
        y: interpolate(
          startPoint.position.y,
          endPoint.position.y,
          progress,
        ),
      },
      tangent: segmentDirection,
      turnSeverityDegrees,
    };
  }

  const controls = getSmoothSegmentControls(
    points.map((point) => point.position),
    segmentIndex,
    profile.curveTension,
  );

  return {
    position: cubicBezierPoint(
      startPoint.position,
      controls.controlOne,
      controls.controlTwo,
      endPoint.position,
      progress,
    ),
    tangent: normaliseVector(
      cubicBezierTangent(
        startPoint.position,
        controls.controlOne,
        controls.controlTwo,
        endPoint.position,
        progress,
      ),
      segmentDirection,
    ),
    turnSeverityDegrees,
  };
}

function getCornerAdjustedSpeed(
  participant: ReconstructionVehicle,
  requestedSpeedKmh: number,
  turnSeverityDegrees: number,
  action: MovementAction,
): number {
  const profile = getMotionProfile(participant);
  let speed = Math.max(0, requestedSpeedKmh);

  if (
    profile.maximumWalkingSpeedKmh !== null &&
    action !== "Accelerate"
  ) {
    speed = Math.min(
      speed,
      profile.maximumWalkingSpeedKmh,
    );
  }

  const turnRatio = clamp(
    turnSeverityDegrees / 120,
    0,
    1,
  );

  return Math.max(
    0,
    speed *
      (1 - profile.cornerSpeedLoss * turnRatio),
  );
}

function applyHumanWalkingMotion(
  participant: ReconstructionVehicle,
  position: ReconstructionPosition,
  headingDegrees: number,
  speedKmh: number,
  currentTime: number,
  action: MovementAction,
  physicsControlled: boolean,
): {
  position: ReconstructionPosition;
  rotation: number;
} {
  if (
    !HUMAN_TYPES.has(participant.type) ||
    physicsControlled ||
    POST_IMPACT_ACTIONS.has(action) ||
    speedKmh < 0.7
  ) {
    return {
      position,
      rotation: headingDegrees,
    };
  }

  const profile = getMotionProfile(participant);

  const walkingRatio = clamp(
    speedKmh / 6.5,
    0.25,
    1,
  );

  const cadenceHz = interpolate(
    1.35,
    1.85,
    walkingRatio,
  );

  const phase =
    currentTime * cadenceHz * Math.PI * 2;

  const lateralSway =
    Math.sin(phase) *
    profile.gaitSwayScenePercent *
    walkingRatio;

  const headingRadians =
    degreesToRadians(headingDegrees);

  const perpendicular = {
    x: -Math.sin(headingRadians),
    y: Math.cos(headingRadians),
  };

  return {
    position: {
      x: clamp(
        position.x +
          perpendicular.x * lateralSway,
        0,
        100,
      ),
      y: clamp(
        position.y +
          perpendicular.y * lateralSway,
        0,
        100,
      ),
    },
    rotation:
      headingDegrees +
      Math.sin(phase) *
        profile.gaitRotationDegrees *
        walkingRatio,
  };
}

export function getParticipantStateAtTime(
  participant: ReconstructionVehicle,
  currentTime: number,
): {
  position: ReconstructionPosition;
  rotation: number;
  speedKmh: number;
  activePointId: string;
} {
  const points = sanitiseParticipantPathPoints(
    participant.pathPoints,
  );

  if (points.length === 0) {
    return {
      position: participant.startPosition,
      rotation: participant.startRotation,
      speedKmh: participant.estimatedSpeedKmh,
      activePointId: "",
    };
  }

  if (currentTime <= points[0].timeSeconds) {
    const first = points[0];
    const next = points[1] ?? first;

    const tangent = normaliseVector(
      subtractPositions(
        next.position,
        first.position,
      ),
      {
        x: Math.cos(
          degreesToRadians(first.rotation),
        ),
        y: Math.sin(
          degreesToRadians(first.rotation),
        ),
      },
    );

    const heading = angleFromVector(tangent);

    const speedKmh = getCornerAdjustedSpeed(
      participant,
      first.speedKmh,
      0,
      first.action,
    );

    const walkingMotion = applyHumanWalkingMotion(
      participant,
      first.position,
      heading,
      speedKmh,
      currentTime,
      first.action,
      isPhysicsGeneratedPathPoint(first),
    );

    return {
      position: walkingMotion.position,
      rotation: walkingMotion.rotation,
      speedKmh,
      activePointId: first.id,
    };
  }

  const finalPoint = points[points.length - 1];

  if (currentTime >= finalPoint.timeSeconds) {
    const previous =
      points[Math.max(0, points.length - 2)];

    const tangent = normaliseVector(
      subtractPositions(
        finalPoint.position,
        previous.position,
      ),
      {
        x: Math.cos(
          degreesToRadians(finalPoint.rotation),
        ),
        y: Math.sin(
          degreesToRadians(finalPoint.rotation),
        ),
      },
    );

    const physicsControlled =
      isPhysicsGeneratedPathPoint(finalPoint) ||
      POST_IMPACT_ACTIONS.has(finalPoint.action);

    const heading = physicsControlled
      ? finalPoint.rotation
      : angleFromVector(tangent);

    const speedKmh =
      finalPoint.action === "Stop"
        ? 0
        : getCornerAdjustedSpeed(
            participant,
            finalPoint.speedKmh,
            0,
            finalPoint.action,
          );

    const walkingMotion = applyHumanWalkingMotion(
      participant,
      finalPoint.position,
      heading,
      speedKmh,
      currentTime,
      finalPoint.action,
      physicsControlled,
    );

    return {
      position: walkingMotion.position,
      rotation: walkingMotion.rotation,
      speedKmh,
      activePointId: finalPoint.id,
    };
  }

  const segmentIndex = points.findIndex(
    (point, index) =>
      index < points.length - 1 &&
      currentTime >= point.timeSeconds &&
      currentTime <=
        points[index + 1].timeSeconds,
  );

  const safeIndex = Math.max(0, segmentIndex);
  const start = points[safeIndex];
  const end = points[safeIndex + 1];

  const duration = Math.max(
    end.timeSeconds - start.timeSeconds,
    0.001,
  );

  const timeProgress = clamp(
    (currentTime - start.timeSeconds) /
      duration,
    0,
    1,
  );

  const positionProgress =
    getKinematicPositionProgress(
      start,
      end,
      timeProgress,
    );

  const geometry = getSegmentMotionGeometry(
    participant,
    points,
    safeIndex,
    positionProgress,
  );

  const physicsControlled =
    isPhysicsGeneratedPathPoint(start) ||
    isPhysicsGeneratedPathPoint(end) ||
    POST_IMPACT_ACTIONS.has(start.action);

  const pathHeading = angleFromVector(
    geometry.tangent,
  );

  const rotation = physicsControlled
    ? interpolateAngle(
        start.rotation,
        end.rotation,
        positionProgress,
      )
    : pathHeading;

  const endSpeed =
    end.action === "Stop" ? 0 : end.speedKmh;

  const interpolatedSpeed = Math.max(
    0,
    interpolate(
      start.speedKmh,
      endSpeed,
      timeProgress,
    ),
  );

  const activeAction =
    timeProgress < 0.5
      ? start.action
      : end.action;

  const speedKmh = getCornerAdjustedSpeed(
    participant,
    interpolatedSpeed,
    geometry.turnSeverityDegrees,
    activeAction,
  );

  const walkingMotion = applyHumanWalkingMotion(
    participant,
    geometry.position,
    rotation,
    speedKmh,
    currentTime,
    activeAction,
    physicsControlled,
  );

  return {
    position: walkingMotion.position,
    rotation: walkingMotion.rotation,
    speedKmh,
    activePointId:
      timeProgress < 0.5
        ? start.id
        : end.id,
  };
}

export function getReconstructionImpactEffectState(
  reconstruction: AccidentReconstruction,
  currentTime: number,
): ReconstructionImpactEffectState {
  const participantCollisionEvent =
    reconstruction.lastPhysicsSimulation
      ?.collisionEvents
      .filter(
        (event) =>
          event.type === "Participant-Participant",
      )
      .sort(
        (left, right) =>
          left.timeSeconds - right.timeSeconds,
      )[0];

  const impactPoints =
    reconstruction.vehicles
      .map((participant) =>
        sanitiseParticipantPathPoints(
          participant.pathPoints,
        ).find(
          (point) =>
            point.action === "Impact",
        ),
      )
      .filter(
        (
          point,
        ): point is MovementPathPoint =>
          Boolean(point),
      );

  const fallbackTime = impactPoints.length
    ? [...impactPoints].sort(
        (left, right) =>
          left.timeSeconds -
          right.timeSeconds,
      )[
        Math.floor(impactPoints.length / 2)
      ].timeSeconds
    : reconstruction.durationSeconds / 2;

  const impactTimeSeconds =
    participantCollisionEvent?.timeSeconds ??
    fallbackTime;

  const showImpactEffects =
    reconstruction.physicsSettings
      ?.showImpactEffects ?? true;

  const elapsed =
    currentTime - impactTimeSeconds;

  const effectDuration = 1.05;

  const energy =
    participantCollisionEvent
      ?.estimatedEnergyKj ??
    reconstruction.lastPhysicsSimulation
      ?.estimatedImpactEnergyKj ??
    0;

  const fallbackSpeed = Math.max(
    0,
    ...impactPoints.map(
      (point) => point.speedKmh,
    ),
  );

  return {
    active:
      showImpactEffects &&
      Boolean(participantCollisionEvent) &&
      elapsed >= 0 &&
      elapsed <= effectDuration,
    impactTimeSeconds,
    intensity: clamp(
      energy > 0
        ? 0.6 +
            Math.log10(1 + energy) / 3
        : 0.55 + fallbackSpeed / 140,
      0.55,
      1.35,
    ),
    position:
      participantCollisionEvent
        ?.contactPoint ??
      reconstruction.collisionPoint,
    progress: clamp(
      elapsed / effectDuration,
      0,
      1,
    ),
  };
}

export function buildSmoothSvgPath(
  positions: ReconstructionPosition[],
  smoothing = 0.88,
): string {
  const points = deduplicateCurvePositions(
    positions,
  );

  if (points.length === 0) {
    return "";
  }

  if (points.length === 1) {
    return `M ${points[0].x} ${points[0].y}`;
  }

  if (points.length === 2) {
    return (
      `M ${points[0].x} ${points[0].y} ` +
      `L ${points[1].x} ${points[1].y}`
    );
  }

  const normalisedSmoothing = clamp(
    smoothing,
    0.35,
    1,
  );

  let path =
    `M ${points[0].x} ${points[0].y}`;

  for (
    let index = 0;
    index < points.length - 1;
    index += 1
  ) {
    const controls = getSmoothSegmentControls(
      points,
      index,
      normalisedSmoothing,
    );

    const end = points[index + 1];

    path +=
      ` C ${controls.controlOne.x} ${controls.controlOne.y}, ` +
      `${controls.controlTwo.x} ${controls.controlTwo.y}, ` +
      `${end.x} ${end.y}`;
  }

  return path;
}

export function createOffsetTracePoints(
  points: ReconstructionPosition[],
  offset: number,
): ReconstructionPosition[] {
  if (points.length < 2) {
    return points;
  }

  return points.map((point, index) => {
    const previous =
      points[Math.max(0, index - 1)];

    const next =
      points[
        Math.min(points.length - 1, index + 1)
      ];

    const directionX = next.x - previous.x;
    const directionY = next.y - previous.y;

    const length =
      Math.hypot(directionX, directionY) || 1;

    return {
      x: clamp(
        point.x +
          (-directionY / length) * offset,
        0,
        100,
      ),
      y: clamp(
        point.y +
          (directionX / length) * offset,
        0,
        100,
      ),
    };
  });
}

export function isTraceableSceneObjectType(
  type: SceneObjectType,
): boolean {
  return (
    type === "Skid Mark" ||
    type === "Tyre Mark" ||
    type === "Road Crack"
  );
}

export function shiftSceneObjectTrace(
  object: ReconstructionSceneObject,
  nextPosition: ReconstructionPosition,
): ReconstructionPosition[] | undefined {
  if (
    !object.tracePoints ||
    object.tracePoints.length === 0
  ) {
    return object.tracePoints;
  }

  const differenceX =
    nextPosition.x - object.position.x;

  const differenceY =
    nextPosition.y - object.position.y;

  return object.tracePoints.map((point) => ({
    x: clamp(
      point.x + differenceX,
      0,
      100,
    ),
    y: clamp(
      point.y + differenceY,
      0,
      100,
    ),
  }));
}

export function syncLegacyParticipantFields(
  participant: ReconstructionVehicle,
): ReconstructionVehicle {
  const points = sanitiseParticipantPathPoints(
    participant.pathPoints,
  );

  if (points.length === 0) {
    return {
      ...participant,
      pathPoints: [],
    };
  }

  const start = points[0];

  const impact =
    points.find(
      (point) => point.action === "Impact",
    ) ??
    points[Math.floor(points.length / 2)];

  const restPoint =
    [...points]
      .reverse()
      .find(isObservedRestPoint) ??
    [...points]
      .reverse()
      .find(isPhysicsCalculatedRestPoint) ??
    null;

  const legacyFinal = restPoint ?? impact;

  return {
    ...participant,
    pathPoints: points,
    startPosition: start.position,
    collisionPosition: impact.position,
    finalPosition: legacyFinal.position,
    startRotation: start.rotation,
    collisionRotation: impact.rotation,
    finalRotation: legacyFinal.rotation,
    collisionTimeSeconds: impact.timeSeconds,
    estimatedSpeedKmh: start.speedKmh,
  };
}
