/*
 * [RoadSafe:PreImpactReactionModelV1]
 *
 * Deterministic pre-impact reaction behavior shared by 2D, 3D, AR and Rapier.
 *
 * This is NOT an inference that a real driver/pedestrian definitely reacted.
 * It is a reconstruction-behavior layer requested by the investigator.
 * Rapier records emergency-braking use in its simulation warnings/diagnostics.
 */

import type {
  MovementPathPoint,
  ReconstructionPosition,
  ReconstructionVehicle,
} from "../types/reconstruction";

export interface ParticipantAccidentReactionState {
  active: boolean;
  impactTimeSeconds?: number;
  impactPosition?: ReconstructionPosition;
  timeToImpactSeconds: number;

  reactionIntensity: number;

  /**
   * Additional short visual/heading attention toward the impact point.
   * Kept deliberately small for road vehicles.
   */
  headingAdjustmentDegrees: number;
  suggestedHeadingDegrees: number;

  /**
   * Useful for a human head/upper-body look without rotating the whole person
   * as much as the attention target.
   */
  lookYawDegrees: number;

  emergencyBraking: boolean;
  emergencyBrakeIntensity: number;
  emergencyBrakeStartSeconds?: number;
  brakingDecelerationMps2: number;
  adjustedSpeedKmh: number;
  explicitBrakeAuthored: boolean;
}

const HUMAN_TYPES =
  new Set<ReconstructionVehicle["type"]>([
    "Pedestrian",
    "Officer",
    "Witness",
  ]);

const BRAKABLE_TYPES =
  new Set<ReconstructionVehicle["type"]>([
    "Car",
    "Bus",
    "Truck",
    "Motorcycle",
    "Bicycle",
  ]);

const PHYSICS_POINT_PREFIXES = [
  "physics-point-",
  "detected-impact-",
  "physics-transition-",
  "legacy-impact-",
] as const;

function clamp(
  value: number,
  minimum: number,
  maximum: number,
): number {
  return Math.min(
    maximum,
    Math.max(
      minimum,
      value,
    ),
  );
}

function smoothStep(
  value: number,
): number {
  const t =
    clamp(
      value,
      0,
      1,
    );

  return (
    t *
    t *
    (
      3 -
      2 * t
    )
  );
}

function shortestAngleDegrees(
  from: number,
  to: number,
): number {
  return (
    (
      to -
      from +
      540
    ) %
      360
  ) -
    180;
}

function bearingDegrees(
  from: ReconstructionPosition,
  to: ReconstructionPosition,
): number {
  return (
    Math.atan2(
      to.y -
        from.y,
      to.x -
        from.x,
    ) *
      180 /
      Math.PI +
    360
  ) %
    360;
}

function isPhysicsGeneratedPoint(
  point: MovementPathPoint,
): boolean {
  return PHYSICS_POINT_PREFIXES.some(
    (prefix) =>
      point.id.startsWith(
        prefix,
      ),
  ) ||
    point.notes?.includes(
      "Physics-generated event.",
    ) ===
      true ||
    point.notes?.includes(
      "Generated by RoadSafe Rapier",
    ) ===
      true;
}

function sortedPoints(
  participant:
    ReconstructionVehicle,
): MovementPathPoint[] {
  return [
    ...participant.pathPoints,
  ].sort(
    (left, right) =>
      left.timeSeconds -
      right.timeSeconds,
  );
}

function findPrimaryAuthoredImpactPoint(
  participant:
    ReconstructionVehicle,
): MovementPathPoint | undefined {
  const points =
    sortedPoints(
      participant,
    );

  return (
    points.find(
      (point) =>
        point.action ===
          "Impact" &&
        !isPhysicsGeneratedPoint(
          point,
        ),
    ) ??
    points.find(
      (point) =>
        point.action ===
        "Impact",
    )
  );
}

function getReactionLeadSeconds(
  participant:
    ReconstructionVehicle,
): number {
  switch (
    participant.type
  ) {
    case "Truck":
      return 0.68;

    case "Bus":
      return 0.64;

    case "Car":
      return 0.58;

    case "Motorcycle":
      return 0.5;

    case "Bicycle":
      return 0.46;

    case "Pedestrian":
    case "Officer":
    case "Witness":
      return 0.48;

    default:
      return 0.5;
  }
}

function getAutomaticBrakeLeadSeconds(
  participant:
    ReconstructionVehicle,
): number {
  switch (
    participant.type
  ) {
    case "Truck":
      return 0.4;

    case "Bus":
      return 0.38;

    case "Car":
      return 0.34;

    case "Motorcycle":
      return 0.31;

    case "Bicycle":
      return 0.27;

    default:
      return 0;
  }
}

function getFallbackBrakingDeceleration(
  participant:
    ReconstructionVehicle,
): number {
  switch (
    participant.type
  ) {
    case "Truck":
      return 5.8;

    case "Bus":
      return 6.1;

    case "Motorcycle":
      return 7.1;

    case "Bicycle":
      return 4.1;

    case "Car":
    default:
      return 8.2;
  }
}

function getHeadingAttentionLimitDegrees(
  participant:
    ReconstructionVehicle,
): number {
  /*
   * [RoadSafe:BrakeNotSteerReactionV1]
   *
   * Drivers/riders react through braking, not by rotating the whole vehicle
   * toward Point Z. That old yaw cue made cars appear to turn sideways before
   * impact. Human participants may still make a small whole-body attention
   * turn in addition to the larger head-look animation.
   */
  return HUMAN_TYPES.has(
    participant.type,
  )
    ? 7.5
    : 0;
}

function getHumanLookLimitDegrees(
  participant:
    ReconstructionVehicle,
): number {
  return HUMAN_TYPES.has(
    participant.type,
  )
    ? 28
    : 0;
}

function findExplicitBrakePoint(
  participant:
    ReconstructionVehicle,
  impact:
    MovementPathPoint,
): MovementPathPoint | undefined {
  const brakePoints =
    sortedPoints(
      participant,
    ).filter(
      (point) =>
        point.action ===
          "Brake" &&
        point.timeSeconds <
          impact.timeSeconds &&
        !isPhysicsGeneratedPoint(
          point,
        ),
    );

  return brakePoints[
    brakePoints.length - 1
  ];
}

export function getParticipantAccidentReactionState(
  participant:
    ReconstructionVehicle,
  currentTimeSeconds: number,
  currentPosition:
    ReconstructionPosition,
  currentHeadingDegrees: number,
  currentSpeedKmh: number,
  impactTimeOverrideSeconds?: number,
): ParticipantAccidentReactionState {
  const impact =
    findPrimaryAuthoredImpactPoint(
      participant,
    );

  if (!impact) {
    return {
      active: false,
      timeToImpactSeconds:
        Number.POSITIVE_INFINITY,
      reactionIntensity: 0,
      headingAdjustmentDegrees:
        0,
      suggestedHeadingDegrees:
        currentHeadingDegrees,
      lookYawDegrees: 0,
      emergencyBraking:
        false,
      emergencyBrakeIntensity:
        0,
      brakingDecelerationMps2:
        participant.physics
          ?.brakingDecelerationMps2 ??
        getFallbackBrakingDeceleration(
          participant,
        ),
      adjustedSpeedKmh:
        Math.max(
          0,
          currentSpeedKmh,
        ),
      explicitBrakeAuthored:
        false,
    };
  }

  const effectiveImpactTimeSeconds =
    Number.isFinite(
      impactTimeOverrideSeconds,
    )
      ? Number(
          impactTimeOverrideSeconds,
        )
      : impact.timeSeconds;

  const timeToImpact =
    effectiveImpactTimeSeconds -
    currentTimeSeconds;

  const reactionLead =
    getReactionLeadSeconds(
      participant,
    );

  const reactionStart =
    effectiveImpactTimeSeconds -
    reactionLead;

  const preImpact =
    currentTimeSeconds >=
      reactionStart &&
    currentTimeSeconds <
      effectiveImpactTimeSeconds;

  const reactionIntensity =
    preImpact
      ? smoothStep(
          (
            currentTimeSeconds -
            reactionStart
          ) /
            Math.max(
              0.05,
              reactionLead,
            ),
        )
      : 0;

  const impactBearing =
    bearingDegrees(
      currentPosition,
      impact.position,
    );

  const bearingDifference =
    shortestAngleDegrees(
      currentHeadingDegrees,
      impactBearing,
    );

  const headingLimit =
    getHeadingAttentionLimitDegrees(
      participant,
    );

  const headingAdjustment =
    preImpact
      ? clamp(
          bearingDifference,
          -headingLimit,
          headingLimit,
        ) *
        reactionIntensity
      : 0;

  const lookLimit =
    getHumanLookLimitDegrees(
      participant,
    );

  const lookYaw =
    preImpact &&
    lookLimit >
      0
      ? clamp(
          bearingDifference,
          -lookLimit,
          lookLimit,
        ) *
        reactionIntensity
      : 0;

  const explicitBrake =
    findExplicitBrakePoint(
      participant,
      impact,
    );

  const automaticBrakeLead =
    getAutomaticBrakeLeadSeconds(
      participant,
    );

  const brakeStart =
    explicitBrake
      ? explicitBrake
          .timeSeconds
      : effectiveImpactTimeSeconds -
        automaticBrakeLead;

  const brakingDeceleration =
    Math.max(
      0.1,
      participant.physics
        ?.brakingDecelerationMps2 ??
        getFallbackBrakingDeceleration(
          participant,
        ),
    );

  const emergencyBraking =
    BRAKABLE_TYPES.has(
      participant.type,
    ) &&
    currentTimeSeconds >=
      brakeStart &&
    currentTimeSeconds <
      effectiveImpactTimeSeconds &&
    currentSpeedKmh >
      0.5;

  const brakeDuration =
    Math.max(
      0.05,
      effectiveImpactTimeSeconds -
      brakeStart,
    );

  const brakeElapsed =
    emergencyBraking
      ? Math.max(
          0,
          currentTimeSeconds -
          brakeStart,
        )
      : 0;

  const emergencyBrakeIntensity =
    emergencyBraking
      ? smoothStep(
          brakeElapsed /
          brakeDuration,
        )
      : 0;

  /*
   * This is the speed envelope supplied to Rapier during the pre-impact
   * reaction window. Actual Rapier stepping also removes velocity by the same
   * configured deceleration, so this preview/initialization value doesn't stand
   * alone as a fake display number.
   */
  const adjustedSpeedKmh =
    emergencyBraking
      ? Math.max(
          0,
          currentSpeedKmh -
          brakingDeceleration *
            brakeElapsed *
            3.6,
        )
      : Math.max(
          0,
          currentSpeedKmh,
        );

  return {
    active:
      preImpact,
    impactTimeSeconds:
      effectiveImpactTimeSeconds,
    impactPosition: {
      ...impact.position,
    },
    timeToImpactSeconds:
      timeToImpact,
    reactionIntensity,
    headingAdjustmentDegrees:
      headingAdjustment,
    suggestedHeadingDegrees:
      currentHeadingDegrees +
      headingAdjustment,
    lookYawDegrees:
      lookYaw,
    emergencyBraking,
    emergencyBrakeIntensity,
    emergencyBrakeStartSeconds:
      BRAKABLE_TYPES.has(
        participant.type,
      )
        ? brakeStart
        : undefined,
    brakingDecelerationMps2:
      brakingDeceleration,
    adjustedSpeedKmh,
    explicitBrakeAuthored:
      Boolean(
        explicitBrake,
      ),
  };
}

export function isHumanReconstructionParticipant(
  participant:
    ReconstructionVehicle,
): boolean {
  return HUMAN_TYPES.has(
    participant.type,
  );
}
